import Link from "next/link";
import { CircleUserRound, LayoutDashboard, LockKeyhole, MessageCircle, Settings, ShieldCheck, Sparkles } from "lucide-react";
import { Brand } from "@/components/site/site-shell";
import { signOut } from "@/app/auth/actions";
import { RecentActivity } from "./recent-activity";
import { MoneyPictureObservations } from "./money-picture-observations";
import { FinancialPeriodSelector } from "./financial-period-selector";
import { CategoryIntelligence } from "./category-intelligence";
import type { FilteredTransactionSummary, MoneyTransaction } from "@/lib/money-picture";
import type { CategoryIntelligencePayload } from "@/lib/category-intelligence";
import type { IntelligenceResult } from "@/lib/money-picture-intelligence";
import type { ObservationExplanationPayload } from "@/lib/money-picture-explanations";
import { formatFinancialPeriodDateRange, type ResolvedFinancialPeriod } from "@/lib/financial-periods";
import { displaySeparated } from "@/lib/presentation-separators";
import { TransactionUnderstanding } from "./transaction-understanding";
import styles from "./money-picture.module.css";

type Picture = { spendingByCategory: Array<{ category: string; amount: number; percentage: number }>; spending: number; income: number; net: number; currentMonth: { inflow: number; outflow: number; net: number }; largestExpenses: MoneyTransaction[]; trend: Array<{ label: string; inflow: number; outflow: number; net: number }>; insights: Array<{ title: string; body: string; range: string; support: string; question: string }>; categories: string[] };
type Account = { id: string; name: string; label: string; type: string; mask: string | null; currency: string; currentBalance: number | null; availableBalance: number | null; institution: string; syncStatus: string };
type AccountAnalytics = { accountId: string; accountLabel: string; transactionCount: number; identifiedInflows: number; identifiedOutflows: number; netCashFlow: number; transfersIn: number; transfersOut: number; largestExpenses: MoneyTransaction[]; commonCategories: string[]; spendingShare: number; depositShare: number; lastActivityDate: string | null; recurringPayments: null; recurringDeposits: null };
type FinancialData = null | { state: "unavailable" } | { state: "ready"; connectionStatus: string; syncStatus: string; lastSync: string | null; accounts: Account[]; transactionCount: number; transactions: MoneyTransaction[]; transactionSummary: FilteredTransactionSummary; cursor: string | null; period: ResolvedFinancialPeriod; financialEventCount: number; picture: Picture; categoryIntelligence: CategoryIntelligencePayload; accountAnalytics: AccountAnalytics[]; accountObservations: Array<{ title: string; body: string; question: string }>; intelligence: IntelligenceResult; explanations: ObservationExplanationPayload[] };
const navigation = [{ label: "Money Picture", icon: LayoutDashboard, href: "#money-picture", active: true }, { label: "Insights", icon: Sparkles, href: "#insights" }, { label: "Talk to Covarify", icon: MessageCircle, href: "#talk-to-covarify" }, { label: "Settings", icon: Settings, href: "/account/settings" }];
const money = (amount: number, currency = "USD") => new Intl.NumberFormat("en-US", { style: "currency", currency }).format(amount);
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Not yet available";
const freshness = (value: string | null) => {
  if (!value) return "Waiting for new activity";
  const days = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 86400000));
  return days === 0 ? "Updated today" : `Last updated ${days} day${days === 1 ? "" : "s"} ago`;
};

export function AuthenticatedWorkspace({ firstName, email, financialData, transactionUnderstandingEnabled = false }: { firstName: string; email: string; financialData: FinancialData; transactionUnderstandingEnabled?: boolean }) {
  const connected = financialData?.state === "ready" && financialData.connectionStatus === "active";
  if (!connected) return <div className="workspace-page"><header className="workspace-header"><div className="workspace-header-inner"><Brand /><div /><div className="workspace-profile"><div><span>{email}</span><small>Founder workspace</small></div><CircleUserRound size={29} /><form action={signOut}><button>Sign out</button></form></div></div></header><main className="workspace-main"><section className="workspace-welcome"><div><p className="eyebrow plain">Private founder workspace</p><h1>Your Money Picture</h1><p>{financialData?.state === "unavailable" ? "Your connection is safe, but this view could not refresh." : `Welcome, ${firstName}. Connect an account when you are ready.`}</p></div></section></main></div>;
  const allCurrent = financialData.accounts.every((account) => account.currentBalance !== null); const allAvailable = financialData.accounts.every((account) => account.availableBalance !== null); const currentTotal = financialData.accounts.reduce((sum, account) => sum + (account.currentBalance || 0), 0); const availableTotal = financialData.accounts.reduce((sum, account) => sum + (account.availableBalance || 0), 0); const maxTrend = Math.max(1, ...financialData.picture.trend.flatMap((month) => [month.inflow, month.outflow]));
  const periodDates = formatFinancialPeriodDateRange(financialData.period);
  return <div className="workspace-page"><header className="workspace-header"><div className="workspace-header-inner"><Brand /><nav className="workspace-nav" aria-label="Workspace navigation">{navigation.map(({ label, icon: Icon, href, active }) => <Link key={label} href={href} className={active ? "is-active" : undefined}><Icon size={17} /><span>{label}</span></Link>)}</nav><div className="workspace-profile"><div><span>{email}</span><small>Founder workspace</small></div><CircleUserRound size={29} /><form action={signOut}><button>Sign out</button></form></div></div></header>
    <main className={styles.main} id="money-picture"><section className={styles.hero}><div><p className={styles.eyebrow}><Sparkles size={14} />Private financial clarity</p><h1>Your Money Picture</h1><div className={styles.activePeriod}><strong>{financialData.period.label}</strong><span>{periodDates}</span></div><p>A clear view of your connected accounts, cash flow, spending, and financial activity.</p></div><div className={styles.sync}><span><i />Connection health</span><strong>Connected</strong><small>{displaySeparated("Data freshness", freshness(financialData.lastSync))}</small><Link className="button button-secondary" href="/connect">Add another institution</Link></div></section>
      <FinancialPeriodSelector
        key={`${financialData.period.key}:${financialData.period.start}:${financialData.period.end}`}
        period={financialData.period}
        financialEventCount={financialData.financialEventCount}
      />
      {financialData.transactionCount === 0 ? <section className={styles.periodEmpty}><h2>No connected activity was found for this period.</h2><p>Choose another period to continue exploring your Money Picture.</p></section> : <>
      <MoneyPictureObservations intelligence={financialData.intelligence} explanations={financialData.explanations} />
      <section aria-labelledby="snapshot-heading"><div className={styles.sectionHeading}><div><p>Financial snapshot</p><h2 id="snapshot-heading">Right now, at a glance</h2></div><span>Based on connected accounts</span></div><div className={styles.snapshot}><article><span>Connected accounts</span><strong>{financialData.accounts.length}</strong></article><article><span>Transactions imported</span><strong>{financialData.transactionCount.toLocaleString("en-US")}</strong></article><article><span>Last successful sync</span><strong className={styles.smallValue}>{date(financialData.lastSync)}</strong></article><article><span>Current sync status</span><strong className={styles.smallValue}>{financialData.syncStatus === "complete" ? "Complete" : "Pending"}</strong></article>{allCurrent && <article><span>Total current balance</span><strong>{money(currentTotal)}</strong></article>}{allAvailable && <article><span>Total available balance</span><strong>{money(availableTotal)}</strong></article>}</div></section>
      <section aria-labelledby="accounts-heading"><div className={styles.sectionHeading}><div><p>Connected accounts</p><h2 id="accounts-heading">Included in your picture</h2></div><span>{financialData.accounts.length} selected</span></div><div className={styles.accounts}>{financialData.accounts.map((account) => <article key={account.id}><div className={styles.accountTop}><span><LockKeyhole size={18} /></span><small>{account.institution}</small></div><h3>{account.name}</h3><p>{displaySeparated(account.type, account.mask ? `•••• ${account.mask}` : null)}</p><dl><div><dt>Current balance</dt><dd>{account.currentBalance === null ? "Balance unavailable" : money(account.currentBalance, account.currency)}</dd></div><div><dt>Available balance</dt><dd>{account.availableBalance === null ? "Balance unavailable" : money(account.availableBalance, account.currency)}</dd></div></dl><footer><ShieldCheck size={14} />Sync {account.syncStatus}</footer></article>)}</div></section>
      <section aria-labelledby="overview-heading"><div className={styles.sectionHeading}><div><p>Financial overview</p><h2 id="overview-heading">How money is moving</h2></div><span>{financialData.period.label}</span></div><div className={styles.overview}><CategoryIntelligence payload={financialData.categoryIntelligence} periodLabel={financialData.period.label} /><article><h3>Period cash flow</h3><p>{financialData.period.label}</p><dl className={styles.metrics}><div><dt>Identified inflow</dt><dd>{money(financialData.picture.currentMonth.inflow)}</dd></div><div><dt>Estimated spending</dt><dd>{money(financialData.picture.currentMonth.outflow)}</dd></div><div><dt>Net cash flow</dt><dd>{money(financialData.picture.currentMonth.net)}</dd></div></dl></article><article><h3>Income vs. spending</h3><p>{financialData.period.label}</p><dl className={styles.metrics}><div><dt>Estimated income</dt><dd>{money(financialData.picture.income)}</dd></div><div><dt>Estimated spending</dt><dd>{money(financialData.picture.spending)}</dd></div><div><dt>Difference</dt><dd>{money(financialData.picture.net)}</dd></div></dl><small>Deposits are counted as income only when categorized as income. Transfers, refunds, and pending activity are excluded.</small></article><article className={styles.wide}><header><div><h3>Net cash flow trend</h3><p>{financialData.period.label}</p></div></header><div className={styles.chart} role="img" aria-label="Monthly identified inflows and estimated outflows, with net cash flow values">{financialData.picture.trend.map((month) => <div key={month.label}><span>{month.label}</span><div><i className={styles.inflow} style={{ height: `${Math.max(4, month.inflow / maxTrend * 100)}%` }} /><i className={styles.outflow} style={{ height: `${Math.max(4, month.outflow / maxTrend * 100)}%` }} /></div><strong>{money(month.net)}</strong></div>)}</div><p className={styles.legend}><i className={styles.inflow} />Identified inflow <i className={styles.outflow} />Estimated outflow</p></article><article className={styles.wide}><header><div><h3>Largest expenses</h3><p>{displaySeparated("Top 5 non-transfer outflows", financialData.period.label)}</p></div></header>{financialData.picture.largestExpenses.length ? <ol className={styles.expenses}>{financialData.picture.largestExpenses.map((transaction) => <li key={transaction.id}><div><strong>{transaction.name}</strong><span>{displaySeparated(transaction.date, transaction.category)}</span></div><strong>{money(transaction.amount, transaction.currency)}</strong></li>)}</ol> : <p className={styles.empty}>No qualifying expenses were found in this period.</p>}</article></div></section>
      <section aria-labelledby="account-breakdown-heading"><div className={styles.sectionHeading}><div><p>Account-level clarity</p><h2 id="account-breakdown-heading">How each account contributes</h2></div><span>{financialData.period.label}</span></div><div className={styles.overview}>{financialData.accountAnalytics.map((account) => <article key={account.accountId}><h3>{account.accountLabel}</h3><p>Last activity {account.lastActivityDate || "not available"}</p><dl className={styles.metrics}><div><dt>Transactions</dt><dd>{account.transactionCount}</dd></div><div><dt>Identified inflows</dt><dd>{money(account.identifiedInflows)}</dd></div><div><dt>Identified outflows</dt><dd>{money(account.identifiedOutflows)}</dd></div><div><dt>Net cash flow</dt><dd>{money(account.netCashFlow)}</dd></div><div><dt>Transfers in / out</dt><dd>{account.transfersIn} / {account.transfersOut}</dd></div><div><dt>Share of spending</dt><dd>{account.spendingShare.toFixed(0)}%</dd></div><div><dt>Share of deposits</dt><dd>{account.depositShare.toFixed(0)}%</dd></div></dl><small>Most common categories: {account.commonCategories.join(", ") || "Not enough categorized activity"}. Recurring activity is not shown until patterns can be classified reliably.</small></article>)}</div></section>
      <RecentActivity key={`${financialData.period.start}:${financialData.period.end}`} initial={financialData.transactions} initialSummary={financialData.transactionSummary} total={financialData.transactionCount} accounts={financialData.accounts.map(({ id, label }) => ({ id, name: label }))} categories={financialData.picture.categories} initialCursor={financialData.cursor} period={financialData.period} />
      <section id="insights" aria-labelledby="insights-heading"><div className={styles.sectionHeading}><div><p>Financial insights</p><h2 id="insights-heading">Patterns worth understanding</h2></div><span>Explainable observations, not financial advice</span></div><div className={styles.insights}>{[...financialData.picture.insights.map((insight) => ({ title: insight.title, body: insight.body, supporting: displaySeparated(insight.range, insight.support), question: insight.question })), ...financialData.accountObservations.map((insight) => ({ title: insight.title, body: insight.body, supporting: financialData.period.label, question: insight.question }))].map((insight) => <article key={insight.title}><Sparkles size={18} /><h3>{insight.title}</h3><p>{insight.body}</p><small>{insight.supporting}</small><strong>Ask Covarify: {insight.question}</strong></article>)}<article><LockKeyhole size={18} /><h3>Recurring activity and expected upcoming bills</h3><p>Covarify needs more consistently classified transaction history before it can estimate recurring payments and upcoming bills reliably.</p><small>Based on your recent transaction patterns. Dates and amounts may vary.</small></article></div></section>
      {transactionUnderstandingEnabled ? <TransactionUnderstanding /> : null}</>}
    </main></div>;
}
