import Link from "next/link";
import { ArrowRight, CircleUserRound, LayoutDashboard, LockKeyhole, MessageCircle, Settings, ShieldCheck, Sparkles } from "lucide-react";
import { Brand } from "@/components/site/site-shell";
import { signOut } from "@/app/auth/actions";

const navigation = [
  { label: "Money Picture", icon: LayoutDashboard, href: "#money-picture", active: true },
  { label: "Decision Studio", icon: Sparkles, href: "#decision-studio" },
  { label: "Talk to Covarify", icon: MessageCircle, href: "#talk-to-covarify" },
  { label: "Settings", icon: Settings, href: "#settings" },
];

type FinancialData = null | { state: "unavailable" } | { state: "ready"; connectionStatus: string; syncStatus: string; accountCount: number; transactionCount: number; accounts: Array<{ id: string; name: string; type: string; mask: string | null }>; transactions: Array<{ id: string; name: string; amount: number; currency: string; date: string; pending: boolean }> };

function formatAmount(amount: number, currency: string) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency }).format(amount);
}

export function AuthenticatedWorkspace({ firstName, email, greeting, financialData }: { firstName: string; email: string; greeting: string; financialData: FinancialData }) {
  const connected = financialData?.state === "ready" && financialData.connectionStatus === "active";
  return <div className="workspace-page">
    <header className="workspace-header"><div className="workspace-header-inner"><Brand /><nav className="workspace-nav" aria-label="Workspace navigation">{navigation.map(({ label, icon: Icon, href, active }) => <Link key={label} href={href} className={active ? "is-active" : undefined} aria-current={active ? "page" : undefined}><Icon size={17} /><span>{label}</span></Link>)}</nav><div className="workspace-profile"><div><span>{email}</span><small>Founder workspace</small></div><CircleUserRound size={29} aria-hidden="true" /><form action={signOut}><button type="submit">Sign out</button></form></div></div></header>
    <main className="workspace-main">
      <section className="workspace-welcome"><div><p className="eyebrow plain"><Sparkles size={13} />Private founder workspace</p><h1>{greeting}, {firstName}.</h1><p>Your financial story stays connected.</p></div><span className="workspace-status"><ShieldCheck size={16} />Secure session</span></section>
      <section className="workspace-grid" id="money-picture">
        <article className="workspace-connection-card"><div className="connection-visual" aria-hidden="true"><span className="orbit-ring orbit-ring-one" /><span className="orbit-ring orbit-ring-two" /><span className="orbit-core"><LockKeyhole size={23} /></span></div><div className="connection-copy">{connected ? <><p className="card-kicker">Money Picture · Connected</p><h2>Your financial picture is taking shape.</h2><p>{financialData.accountCount} selected accounts are securely connected, with {financialData.transactionCount.toLocaleString("en-US")} transactions available.</p><div className="workspace-stat-row"><span><strong>{financialData.accountCount}</strong>Selected accounts</span><span><strong>{financialData.transactionCount.toLocaleString("en-US")}</strong>Transactions</span><span><strong>{financialData.syncStatus === "complete" ? "Complete" : "Pending"}</strong>Latest sync</span></div></> : <><p className="card-kicker">Money Picture · Ready when you are</p><h2>Bring your financial life into focus.</h2><p>Your first secure account connection will begin your Money Picture—organizing balances, cash flow, and the context behind your next decision in one calm view.</p><Link className="workspace-connect" href="/connect"><span>Review connection readiness</span><ArrowRight size={17} /></Link>{financialData?.state === "unavailable" && <p className="workspace-gate" role="status">Your connection is safe, but this view could not refresh. Please try once more.</p>}</>}</div></article>
        <aside className="workspace-side-card"><div><p className="card-kicker">{connected ? "Connection status" : "Your next chapter"}</p><h3>{connected ? "Your secure connection is active." : "The foundation is in place."}</h3><p>{connected ? "Only the accounts you selected are included in your private Money Picture." : "Your secure profile is active and ready for a controlled connection."}</p></div><div className="workspace-checks"><span><i>1</i>Secure founder access</span><span><i>2</i>Private Money Picture</span><span className={connected ? undefined : "is-muted"}><i>3</i>First controlled connection</span></div></aside>
      </section>
      {connected && <section className="workspace-accounts" aria-labelledby="connected-accounts-heading"><div className="workspace-section-heading"><div><p className="card-kicker">Included in your Money Picture</p><h2 id="connected-accounts-heading">Connected accounts</h2></div><span>{financialData.accountCount} selected</span></div><div className="workspace-account-grid">{financialData.accounts.map((account) => <article key={account.id}><span aria-hidden="true"><LockKeyhole size={17} /></span><div><strong>{account.name}</strong><small>{account.type}{account.mask ? ` · •••• ${account.mask}` : ""}</small></div></article>)}</div></section>}
      {connected && <section className="workspace-transactions" aria-labelledby="recent-transactions-heading"><div className="workspace-section-heading"><div><p className="card-kicker">Recent activity</p><h2 id="recent-transactions-heading">Transactions</h2></div><span>{financialData.transactionCount.toLocaleString("en-US")} total</span></div>{financialData.transactions.length ? <ul>{financialData.transactions.map((transaction) => <li key={transaction.id}><div><strong>{transaction.name}</strong><span>{new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeZone: "UTC" }).format(new Date(`${transaction.date}T00:00:00Z`))}{transaction.pending ? " · Pending" : ""}</span></div><strong>{formatAmount(transaction.amount, transaction.currency)}</strong></li>)}</ul> : <p className="workspace-empty">Your connection is active. Transactions are still syncing.</p>}</section>}
      <section className="workspace-preview-row"><article id="decision-studio"><span><Sparkles size={18} /></span><div><small>Decision Studio</small><h3>Turn possibilities into clear choices.</h3><p>Available after your Money Picture is established.</p></div></article><article id="talk-to-covarify"><span><MessageCircle size={18} /></span><div><small>Talk to Covarify</small><h3>Ask in plain language.</h3><p>Your financial context will make every conversation more useful.</p></div></article><article id="settings"><span><Settings size={18} /></span><div><small>Settings</small><h3>Your access, your preferences.</h3><p><Link href="/account/delete">Review or delete your account</Link></p></div></article></section>
    </main>
  </div>;
}
