"use client";

import { useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, MessageCircle, ShieldCheck } from "lucide-react";
import { orchestrateConversation } from "@/lib/conversation/orchestrator";
import { buildHousingGap, candidateLevers, generateRecoveryOptions, rankFinancialPriority, type PlanConstraint, type RecoveryOption } from "@/lib/conversation/financial-triage";
import { assembleWholePicture } from "@/lib/conversation/whole-picture";
import { recommendPersonalizedStrategy } from "@/lib/conversation/strategy-engine";
import { selectNextBestStep } from "@/lib/conversation/next-best-step";
import type { ConversationContext, ConversationResponse } from "@/lib/conversation/types";
import type { MoneyTransaction } from "@/lib/money-picture";
import styles from "./conversation-strategy-preview.module.css";

const transactions: MoneyTransaction[] = [
  { id: "olukai-89", plaidAccountId: "capital-one", accountLabel: "Capital One · 4242", merchantName: null, name: "OLU’KAI", description: "VISA DDA PUR AP 469216 SP AFF OLUKAI *", amount: 89, currency: "USD", date: "2026-07-14", pending: false, pendingTransactionId: null, category: "GENERAL_MERCHANDISE", sourceCategory: "GENERAL_MERCHANDISE", detailedCategory: null, direction: "outflow", transferRelationship: null },
  { id: "olukai-110", plaidAccountId: "td", accountLabel: "TD Checking · 9214", merchantName: "OLU'KAI", name: "OLU'KAI", description: "OLUKAI ONLINE", amount: 110, currency: "USD", date: "2026-06-09", pending: false, pendingTransactionId: null, category: "GENERAL_MERCHANDISE", sourceCategory: "GENERAL_MERCHANDISE", detailedCategory: null, direction: "outflow", transferRelationship: null },
  { id: "heights-1700", plaidAccountId: "td", accountLabel: "TD Checking · 9214", merchantName: "The Heights", name: "The Heights", description: "THE HEIGHTS RENT", amount: 1700, currency: "USD", date: "2026-07-01", pending: false, pendingTransactionId: null, category: "RENT_AND_UTILITIES", sourceCategory: "RENT_AND_UTILITIES", detailedCategory: null, direction: "outflow", transferRelationship: null },
];
const spend = [
  { key: "uber-eats", label: "Uber Eats", category: "Delivery", amount: 700, transactionIds: ["uber-1", "uber-2", "uber-3", "uber-4"], flexibility: "discretionary" as const, recurring: true },
  { key: "restaurants", label: "Restaurants", category: "Food & Drink", amount: 260, transactionIds: ["restaurant-1", "restaurant-2"], flexibility: "discretionary" as const, recurring: true },
  { key: "subscriptions", label: "Optional subscriptions", category: "Subscriptions", amount: 52.5, transactionIds: ["subscription-1", "subscription-2"], flexibility: "potentially_cancellable" as const, recurring: true },
  { key: "callie", label: "Callie’s activities", category: "Family", amount: 180, transactionIds: ["callie-1", "callie-2"], flexibility: "discretionary" as const, recurring: true },
  { key: "birthday", label: "Birthday gift", category: "Shopping", amount: 89, transactionIds: ["olukai-89"], flexibility: "unusual_one_time" as const, recurring: false },
];
type Turn = { role: "user" | "covarify"; text: string };
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);

export function ConversationStrategyPreview() {
  const [turns, setTurns] = useState<Turn[]>([]); const [text, setText] = useState(""); const [context, setContext] = useState<ConversationContext | null>(null); const [response, setResponse] = useState<ConversationResponse | null>(null);
  const [goalConfirmed, setGoalConfirmed] = useState(false); const [inputStep, setInputStep] = useState(0); const [normalRent, setNormalRent] = useState(""); const [outstanding, setOutstanding] = useState(""); const [deadline, setDeadline] = useState(""); const [protectCallie, setProtectCallie] = useState(false); const [selectedOption, setSelectedOption] = useState<RecoveryOption["name"]>("Balanced");
  const constraints: PlanConstraint[] = useMemo(() => [...(protectCallie ? [{ kind: "protect" as const, key: "callie", value: "Callie’s activities" }] : []), ...(deadline ? [{ kind: "deadline" as const, key: "deadline", value: deadline }] : [])], [protectCallie, deadline]);
  const gap = useMemo(() => buildHousingGap({ obligation: "Catch up on The Heights rent", normalMonthlyRent: inputStep >= 1 && normalRent ? Number(normalRent) : null, amountPaid: 1700, outstanding: inputStep >= 2 && outstanding ? Number(outstanding) : null, targetCatchUpDate: inputStep >= 3 && deadline ? deadline : null, availableCash: 1000, protectedReserve: 1000, expectedIncome: 1800, protectedObligations: 75, upcomingObligations: 725, recurringCommitments: 200, essentialSpending: 800, paymentType: "partial", evidenceIds: ["heights-1700", "cash-account", "income-activity", "credit-minimum", "recurring-evidence", "essential-spending"], assumptions: ["The target date occurs before another unmodeled obligation."], limitations: ["This is a fixture-based founder preview, not an active plan."] }), [inputStep, normalRent, outstanding, deadline]);
  const situation = useMemo(() => assembleWholePicture({ userId: "founder-review", accounts: [{ id: "cash", kind: "cash", currentBalance: 1200, availableBalance: 1000, minimumPayment: null, fresh: true }, { id: "credit", kind: "credit", currentBalance: 2400, availableBalance: 3100, minimumPayment: 75, fresh: true }, { id: "investment", kind: "investment", currentBalance: 9000, availableBalance: null, minimumPayment: null, fresh: true }], expectedIncome: 1800, recentCashFlow: 300, protectedObligations: 1500, evidenceIds: ["cash-account", "income-activity", "credit-minimum"] }), []);
  const levers = useMemo(() => candidateLevers(spend, constraints), [constraints]); const options = useMemo(() => goalConfirmed ? generateRecoveryOptions(gap, levers, constraints) : [], [goalConfirmed, gap, levers, constraints]);
  const goal = { id: "rent-preview", userId: "founder-review", type: "housing_catch_up" as const, label: "Catch up on The Heights rent", targetAmount: gap.remainingAmount, targetDate: deadline || null, priority: 1, status: "confirmed" as const, confirmedAt: goalConfirmed ? new Date().toISOString() : null, evidenceIds: gap.evidenceIds, assumptions: gap.assumptions };
  const strategy = options.length ? recommendPersonalizedStrategy({ goal, situation, options, constraints }) : null; const chosen = options.find((option) => option.name === selectedOption) || strategy?.recommended || null;
  const next = selectNextBestStep({ goal, priority: rankFinancialPriority({ housingGap: gap, daysUntilDue: 7 }), evidenceIds: gap.evidenceIds, goalConfirmationRequired: !goalConfirmed, missingInputs: goalConfirmed ? gap.missingInputs : [], optionsReady: options.length > 0, strategyReady: Boolean(strategy) });

  function send() { const statement = text.trim(); if (!statement) return; const result = orchestrateConversation({ text: statement, userId: "founder-review", sessionId: "preview-session", context, transactions, now: new Date("2026-08-03T12:00:00Z") }); setTurns((current) => [...current, { role: "user", text: statement }, { role: "covarify", text: result.message }]); setResponse(result); setContext(result.context); setText(""); }

  return <main className={styles.page}>
    <header><span>Founder review · read-only</span><h1>Conversation and strategy preview</h1><p>Explore continuous financial conversation and personalized recovery options. Nothing here activates or saves a plan.</p></header>
    <section className={styles.workspace} aria-labelledby="conversation-heading"><div><p className={styles.eyebrow}><MessageCircle size={16}/> Flow A</p><h2 id="conversation-heading">Continuous transaction conversation</h2></div>
      <div className={styles.transcript} aria-live="polite">{turns.length ? turns.map((turn, index) => <article key={`${turn.role}-${index}`} className={turn.role === "user" ? styles.user : styles.assistant}><strong>{turn.role === "user" ? "You" : "Covarify"}</strong><p>{turn.text}</p></article>) : <p className={styles.empty}>Try the guided prompts below.</p>}</div>
      <div className={styles.prompts}>{["How many payments were made to OLU’KAI?", "Which card did I use?", "One was a birthday gift for Caleb.", "The $89 one was a birthday gift for Caleb.", "My son."].map((prompt) => <button key={prompt} type="button" onClick={() => setText(prompt)}>{prompt}</button>)}</div>
      <label>Message<textarea value={text} onChange={(event) => setText(event.target.value)} onKeyDown={(event) => { if ((event.ctrlKey || event.metaKey) && event.key === "Enter") send(); }} /></label><button className={styles.primary} type="button" onClick={send}>Send <ArrowRight size={16}/></button>
      {response?.evidence ? <details><summary>View supporting evidence</summary><p>{response.evidence.transactionIds.length} exact transactions · {response.evidence.period.label}</p><p>{response.evidence.limitations.join(" ")}</p></details> : null}
      {response?.proposal ? <section className={styles.proposal} aria-label="Proposed change requiring confirmation"><strong>Proposal · confirmation required</strong>{response.proposal.values.map((value) => <p key={value.label}>{value.label}: {value.value}</p>)}<p>No durable change occurs in this preview.</p></section> : null}
      {response ? <aside className={styles.next} aria-label="Primary next best step"><small>Next best step</small><strong>{response.nextBestStep.label}</strong><p>{response.nextBestStep.reason}</p></aside> : null}
    </section>
    <section className={styles.workspace} aria-labelledby="strategy-heading"><div><p className={styles.eyebrow}><ShieldCheck size={16}/> Flow B</p><h2 id="strategy-heading">Rent recovery strategy preview</h2><p className={styles.fact}><strong>Known fact:</strong> The Heights payment was {money(1700)}. Payment amount and normal monthly rent remain separate.</p></div>
      {!goalConfirmed ? <div className={styles.goal}><p><strong>Possible goal:</strong> Catch up on The Heights rent.</p><button className={styles.primary} type="button" onClick={() => { setGoalConfirmed(true); setInputStep(0); }}>Yes, use this goal</button><button type="button">Choose a different goal</button></div> : <p className={styles.confirmed}><CheckCircle2 size={18}/> User-confirmed goal: catch up on The Heights rent</p>}
      {goalConfirmed ? <div className={styles.confirmedFacts} aria-label="User-provided confirmed facts">{inputStep >= 1 ? <p><strong>Normal monthly rent:</strong> {money(Number(normalRent))} <button type="button" onClick={() => setInputStep(0)}>Change</button></p> : null}{inputStep >= 2 ? <p><strong>Currently outstanding:</strong> {money(Number(outstanding))} <button type="button" onClick={() => setInputStep(1)}>Change</button></p> : null}{inputStep >= 3 ? <p><strong>Target catch-up date:</strong> {deadline} <button type="button" onClick={() => setInputStep(2)}>Change</button></p> : null}</div> : null}
      {goalConfirmed && inputStep < 3 ? <div className={styles.singleQuestion} aria-label="Current unanswered question"><strong>One question at a time</strong>{inputStep === 0 ? <label>What is your normal monthly rent?<input autoFocus inputMode="decimal" value={normalRent} onChange={(event) => setNormalRent(event.target.value)} onKeyDown={(event) => event.key === "Enter" && normalRent && setInputStep(1)} /></label> : inputStep === 1 ? <label>How much is currently outstanding?<input autoFocus inputMode="decimal" value={outstanding} onChange={(event) => setOutstanding(event.target.value)} onKeyDown={(event) => event.key === "Enter" && outstanding && setInputStep(2)} /></label> : <label>When do you want to be caught up?<input autoFocus type="date" value={deadline} onChange={(event) => setDeadline(event.target.value)} onKeyDown={(event) => event.key === "Enter" && deadline && setInputStep(3)} /></label>}<button className={styles.primary} type="button" disabled={inputStep === 0 ? !normalRent : inputStep === 1 ? !outstanding : !deadline} onClick={() => setInputStep((step) => Math.min(3, step + 1))}>Continue</button></div> : null}
      <label className={styles.constraint}><input type="checkbox" checked={protectCallie} onChange={(event) => setProtectCallie(event.target.checked)}/> Protect Callie’s activities</label>
      <div className={styles.situation} aria-label="Whole-picture situation preview"><article><small>Known cash</small><strong>{money(situation.availableCash || 0)}</strong><span>{money(gap.protectedReserve || 0)} reserve protected</span></article><article><small>Required minimums</small><strong>{money(situation.requiredMinimums || 0)}</strong><span>Protected</span></article><article><small>Investments</small><strong>{money(situation.investmentsExcluded || 0)}</strong><span>Excluded from available cash</span></article><article><small>Calculated shortfall</small><strong>{gap.estimatedShortfall == null ? gap.missingInputs.includes("target catch-up date") ? "Needs target date" : "Missing information" : money(gap.estimatedShortfall)}</strong><span>{gap.confidence === "low" ? "Incomplete confidence" : "High confidence for this fixture"}</span></article></div>
      {gap.estimatedShortfall === 0 ? <aside className={styles.missing} aria-label="Zero gap explanation"><strong>No reduction gap found from current fixture evidence</strong><p>The known resources appear sufficient for the outstanding amount after modeled protections. This remains a preview and must be revisited if obligations or timing change.</p></aside> : null}
      {options.length ? <><div className={styles.levers}><h3>Evidence-backed levers</h3>{levers.map((lever) => <article key={lever.id}><div><strong>{lever.label}</strong><span>{lever.evidenceIds.length} supporting transactions</span></div><strong>About {money(lever.estimatedAmount || 0)}</strong><p>{lever.tradeoff}</p></article>)}</div><div className={styles.options} aria-label="Strategy options">{options.map((option) => <article key={option.name} className={strategy?.recommended.name === option.name ? styles.recommended : undefined}><small>{strategy?.recommended.name === option.name ? "Recommended" : "Alternative"}</small><h3>{option.name}</h3><strong>{money(option.expectedContribution)} projected</strong><p>{option.levers.map((lever) => lever.label).join(" + ")}</p><p><strong>Protected:</strong> {option.protectedExpenses.length ? option.protectedExpenses.join(", ") : "Required obligations and essentials"}</p><p>{option.tradeoffs[0]}</p><button type="button" aria-pressed={chosen?.name === option.name} onClick={() => setSelectedOption(option.name)}>Preview {option.name}</button><details><summary>Evidence and assumptions</summary><p>{option.evidenceIds.length} exact evidence references</p><p>{option.assumptions.join(" ")}</p></details></article>)}</div></> : null}
      {strategy && chosen ? <section className={styles.rationale} aria-label="Recommended strategy rationale"><h3>Why {strategy.recommended.name} ranks highest</h3>{strategy.whyHighest.map((reason) => <p key={reason}>{reason}</p>)}<p><strong>Confidence:</strong> {strategy.confidence}</p><p><strong>Could change if:</strong> {strategy.changesIf.join(", ")}.</p></section> : null}
      <aside className={styles.next} aria-label="Primary next best step"><small>Next best step</small><strong>{next.label}</strong><p>{next.reason}</p></aside>
      <footer><strong>Read-only strategy preview</strong><p>Plan activation and durable saving are not available in this controlled phase.</p><button className={styles.primary} type="button" disabled>Activate plan — not available</button></footer>
    </section>
  </main>;
}
