"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, CheckCircle2, MessageCircle, Mic, ShieldCheck, Square, Volume2 } from "lucide-react";
import { orchestrateConversation } from "@/lib/conversation/orchestrator";
import { buildHousingGap, candidateLevers, expectedIncomeWithinWindow, generateRecoveryOptions, generateTimelineOptions, rankFinancialPriority, type PlanConstraint, type RecoveryOption, type TargetMode, type TimelineOption } from "@/lib/conversation/financial-triage";
import { assembleWholePicture } from "@/lib/conversation/whole-picture";
import { recommendPersonalizedStrategy } from "@/lib/conversation/strategy-engine";
import { selectNextBestStep } from "@/lib/conversation/next-best-step";
import type { ConversationContext, ConversationResponse } from "@/lib/conversation/types";
import { assessVoiceTurn, type VoiceTurnAssessment } from "@/lib/conversation/transcript-review";
import type { MoneyTransaction } from "@/lib/money-picture";
import { useBrowserSpeech, type VoiceTranscriptMeta } from "./use-browser-speech";
import styles from "./conversation-strategy-preview.module.css";

const transactions: MoneyTransaction[] = [
  { id: "olukai-89", plaidAccountId: "capital-one", accountLabel: "Capital One · 4242", merchantName: null, name: "OLU’KAI", description: "VISA DDA PUR AP 469216 SP AFF OLUKAI *", amount: 89, currency: "USD", date: "2026-07-14", pending: false, pendingTransactionId: null, category: "GENERAL_MERCHANDISE", sourceCategory: "GENERAL_MERCHANDISE", detailedCategory: null, direction: "outflow", transferRelationship: null },
  { id: "olukai-110", plaidAccountId: "td", accountLabel: "TD Checking · 9214", merchantName: "OLU'KAI", name: "OLU'KAI", description: "OLUKAI ONLINE", amount: 110, currency: "USD", date: "2026-06-09", pending: false, pendingTransactionId: null, category: "GENERAL_MERCHANDISE", sourceCategory: "GENERAL_MERCHANDISE", detailedCategory: null, direction: "outflow", transferRelationship: null },
  { id: "heights-1700", plaidAccountId: "td", accountLabel: "TD Checking · 9214", merchantName: "The Heights", name: "The Heights", description: "THE HEIGHTS RENT", amount: 1700, currency: "USD", date: "2026-07-01", pending: false, pendingTransactionId: null, category: "RENT_AND_UTILITIES", sourceCategory: "RENT_AND_UTILITIES", detailedCategory: null, direction: "outflow", transferRelationship: null },
];
const spend = [
  { key: "uber-eats", label: "Uber Eats", category: "Delivery", amount: 700, transactionIds: ["uber-1", "uber-2", "uber-3", "uber-4"], flexibility: "discretionary" as const, recurring: true },
  { key: "restaurants", label: "Restaurants", category: "Food & Drink", amount: 260, transactionIds: ["restaurant-1", "restaurant-2"], flexibility: "discretionary" as const, recurring: true },
  { key: "subscriptions", label: "Optional subscriptions", category: "Subscriptions", amount: 52.5, transactionIds: ["subscription-1", "subscription-2"], flexibility: "potentially_cancellable" as const, recurring: true },
  { key: "callie", label: "Callie’s activities", category: "Family", amount: 180, transactionIds: ["callie-1", "callie-2"], flexibility: "discretionary" as const, recurring: true },
  { key: "birthday", label: "Birthday gift", category: "Shopping", amount: 89, transactionIds: ["olukai-89"], flexibility: "unusual_one_time" as const, recurring: false },
];
type Turn = { role: "user" | "covarify"; text: string };
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);

export function ConversationStrategyPreview() {
  const [turns, setTurns] = useState<Turn[]>([]); const [text, setText] = useState(""); const [context, setContext] = useState<ConversationContext | null>(null); const [response, setResponse] = useState<ConversationResponse | null>(null);
  const [transcriptMeta, setTranscriptMeta] = useState<(VoiceTranscriptMeta & VoiceTurnAssessment) | null>(null); const [speakResponses, setSpeakResponses] = useState(false); const [speaking, setSpeaking] = useState(false); const [voiceAutoSend, setVoiceAutoSend] = useState(true); const [draftOrigin, setDraftOrigin] = useState<"typed" | "voice" | null>(null); const [incomingVoiceDraft, setIncomingVoiceDraft] = useState<{ transcript: string; meta: VoiceTranscriptMeta & VoiceTurnAssessment } | null>(null); const lastVoiceSubmitted = useRef<string | null>(null); const autoSendTimer = useRef<number | null>(null); const resetVoiceTurn = useRef<() => void>(() => undefined);
  const [goalConfirmed, setGoalConfirmed] = useState(false); const [inputStep, setInputStep] = useState(0); const [normalRent, setNormalRent] = useState(""); const [outstanding, setOutstanding] = useState(""); const [targetMode, setTargetMode] = useState<TargetMode | null>(null); const [deadline, setDeadline] = useState(""); const [monthlyContribution, setMonthlyContribution] = useState(""); const [protectCallie, setProtectCallie] = useState(false); const [selectedOption, setSelectedOption] = useState<RecoveryOption["name"]>("Balanced"); const [optionReviewed, setOptionReviewed] = useState(false); const [proposedTargetConfirmed, setProposedTargetConfirmed] = useState(false);
  const constraints: PlanConstraint[] = useMemo(() => [...(protectCallie ? [{ kind: "protect" as const, key: "callie", value: "Callie’s activities" }] : []), ...(deadline ? [{ kind: "deadline" as const, key: "deadline", value: deadline }] : [])], [protectCallie, deadline]);
  const analysisWindow = useMemo(() => ({ start: "2026-08-04", end: targetMode === "fixed_date" && deadline ? deadline : "2026-09-03" }), [deadline, targetMode]); const analysisPeriods = useMemo(() => Math.max(1, Math.ceil((new Date(`${analysisWindow.end}T12:00:00Z`).getTime() - new Date(`${analysisWindow.start}T12:00:00Z`).getTime()) / (30 * 86400000))), [analysisWindow]); const windowIncome = useMemo(() => expectedIncomeWithinWindow([{ amount: 1800, expectedDate: "2026-08-20", evidenceId: "income-august" }, { amount: 1800, expectedDate: "2026-09-20", evidenceId: "income-september" }, { amount: 1800, expectedDate: "2026-10-20", evidenceId: "income-october" }], analysisWindow), [analysisWindow]);
  const gap = useMemo(() => buildHousingGap({ obligation: "Catch up on The Heights rent", normalMonthlyRent: inputStep >= 1 && normalRent ? Number(normalRent) : null, amountPaid: 1700, outstanding: inputStep >= 2 && outstanding ? Number(outstanding) : null, targetCatchUpDate: targetMode === "fixed_date" && deadline ? deadline : null, availableCash: 1000, protectedReserve: 1000, expectedIncome: windowIncome.amount, protectedObligations: 75 * analysisPeriods, upcomingObligations: 725 * analysisPeriods, recurringCommitments: 200 * analysisPeriods, essentialSpending: 800 * analysisPeriods, paymentType: "partial", analysisWindow, evidenceIds: ["heights-1700", "cash-account", ...windowIncome.evidenceIds, "credit-minimum", "upcoming-obligations", "recurring-evidence", "essential-spending"], evidenceByCategory: { known_cash: ["cash-account"], protected_reserve: ["cash-reserve-policy"], expected_income: windowIncome.evidenceIds, protected_obligations: ["credit-minimum"], upcoming_obligations: ["upcoming-obligations"], recurring_commitments: ["recurring-evidence"], essential_spending: ["essential-spending"], outstanding_amount: ["founder-confirmed-outstanding"] }, assumptions: ["Expected income and each expense category use the same displayed analysis window."], limitations: ["This is a fixture-based founder preview, not an active plan."] }), [analysisPeriods, analysisWindow, inputStep, normalRent, outstanding, deadline, targetMode, windowIncome]);
  const situation = useMemo(() => assembleWholePicture({ userId: "founder-review", accounts: [{ id: "cash", kind: "cash", currentBalance: 1200, availableBalance: 1000, minimumPayment: null, fresh: true }, { id: "credit", kind: "credit", currentBalance: 2400, availableBalance: 3100, minimumPayment: 75, fresh: true }, { id: "investment", kind: "investment", currentBalance: 9000, availableBalance: null, minimumPayment: null, fresh: true }], expectedIncome: 1800, recentCashFlow: 300, protectedObligations: 1500, evidenceIds: ["cash-account", "income-activity", "credit-minimum"] }), []);
  const levers = useMemo(() => candidateLevers(spend, constraints), [constraints]); const timelineOptions = useMemo(() => goalConfirmed && targetMode && targetMode !== "fixed_date" ? generateTimelineOptions({ gap, levers, constraints, mode: targetMode, asOf: "2026-08-04", monthlyContribution: monthlyContribution ? Number(monthlyContribution) : null }) : [], [goalConfirmed, gap, levers, constraints, monthlyContribution, targetMode]); const options: Array<RecoveryOption | TimelineOption> = useMemo(() => targetMode === "fixed_date" && deadline ? generateRecoveryOptions(gap, levers, constraints) : timelineOptions, [deadline, gap, levers, constraints, targetMode, timelineOptions]);
  const goal = { id: "rent-preview", userId: "founder-review", type: "housing_catch_up" as const, label: "Catch up on The Heights rent", targetAmount: gap.remainingAmount, targetDate: targetMode === "fixed_date" ? deadline || null : null, priority: 1, status: "confirmed" as const, confirmedAt: goalConfirmed ? new Date().toISOString() : null, evidenceIds: gap.evidenceIds, assumptions: gap.assumptions };
  const strategy = options.length ? recommendPersonalizedStrategy({ goal, situation, options, constraints }) : null; const chosen = options.find((option) => option.name === selectedOption) || strategy?.recommended || null;
  const fixedMonths = targetMode === "fixed_date" && deadline ? Math.max(1, Math.ceil((new Date(`${deadline}T12:00:00Z`).getTime() - new Date("2026-08-04T12:00:00Z").getTime()) / (30 * 86400000))) : null; const fixedRequiredPace = fixedMonths && gap.estimatedShortfall != null ? Math.ceil(gap.estimatedShortfall / fixedMonths) : null;
  const next = selectNextBestStep({ goal, priority: rankFinancialPriority({ housingGap: gap, daysUntilDue: 7 }), evidenceIds: gap.evidenceIds, goalConfirmationRequired: !goalConfirmed, missingInputs: goalConfirmed ? gap.missingInputs : [], targetMode, fixedDateProvided: Boolean(deadline), timelineChoiceRequired: goalConfirmed && inputStep >= 2 && !targetMode, proposedTargetReady: Boolean(strategy) && optionReviewed && !proposedTargetConfirmed, optionsReady: options.length > 0, strategyReady: Boolean(strategy) && proposedTargetConfirmed });

  const stopSpeaking = useCallback(() => { if (typeof window !== "undefined" && "speechSynthesis" in window) window.speechSynthesis.cancel(); setSpeaking(false); }, []);
  const send = useCallback((raw = text, source: "typed" | "voice" | "tap" = "typed") => { const statement = raw.trim(); if (!statement) return; if (autoSendTimer.current != null) window.clearTimeout(autoSendTimer.current); const result = orchestrateConversation({ text: statement, userId: "founder-review", sessionId: "preview-session", context, transactions, dataMode: "fixture", now: new Date("2026-08-03T12:00:00Z") }); setTurns((current) => [...current, { role: "user", text: statement }, { role: "covarify", text: result.message }]); setResponse(result); setContext(result.context); setText(""); setTranscriptMeta(null); setIncomingVoiceDraft(null); setDraftOrigin(null); resetVoiceTurn.current(); if (source === "voice") lastVoiceSubmitted.current = statement; }, [context, text]);
  const onFinalTranscript = useCallback((transcript: string, meta: VoiceTranscriptMeta) => { const assessment = assessVoiceTurn({ transcript, confidence: meta.confidence, pendingProposal: Boolean(response?.proposal), lastSubmittedTranscript: lastVoiceSubmitted.current, knownMerchants: ["OLU’KAI", "The Heights", "Uber Eats"], activeContext: context }); const reviewed = { ...meta, ...assessment }; if (text.trim() && draftOrigin === "typed") { setIncomingVoiceDraft({ transcript, meta: reviewed }); return "held" as const; } const replaced = Boolean(text.trim() && draftOrigin === "voice"); setText(transcript); setDraftOrigin("voice"); setTranscriptMeta(reviewed); if (voiceAutoSend && assessment.autoSend) { if (autoSendTimer.current != null) window.clearTimeout(autoSendTimer.current); autoSendTimer.current = window.setTimeout(() => send(transcript, "voice"), 650); } return replaced ? "replaced" as const : assessment.correction?.kind === "merchant" ? "held_merchant" as const : assessment.reviewRequired ? "held" as const : "added" as const; }, [context, draftOrigin, response?.proposal, send, text, voiceAutoSend]);
  const voice = useBrowserSpeech({ onFinalTranscript, stopSpeaking });
  const startVoice = () => { if (autoSendTimer.current != null) window.clearTimeout(autoSendTimer.current); if (draftOrigin === "voice") { setText(""); setTranscriptMeta(null); } setIncomingVoiceDraft(null); voice.start(); };
  useEffect(() => { resetVoiceTurn.current = voice.resetActiveTurn; }, [voice.resetActiveTurn]);
  useEffect(() => { if (!speakResponses || !response || !("speechSynthesis" in window) || typeof SpeechSynthesisUtterance === "undefined") return; window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(response.message); utterance.onstart = () => setSpeaking(true); utterance.onend = () => setSpeaking(false); utterance.onerror = () => setSpeaking(false); window.speechSynthesis.speak(utterance); return () => window.speechSynthesis.cancel(); }, [response, speakResponses]);
  useEffect(() => () => { if (autoSendTimer.current != null) window.clearTimeout(autoSendTimer.current); }, []);

  return <main className={styles.page}>
    <aside className={styles.simulation} role="note"><strong>Founder simulation</strong> — transactions, balances, income, obligations, and people shown here are controlled test data, not your connected financial accounts.</aside>
    <header><span>Founder review · read-only</span><h1>Conversation and strategy preview</h1><p>Explore continuous financial conversation and personalized recovery options. Nothing here activates or saves a plan.</p></header>
    <section className={styles.workspace} aria-labelledby="conversation-heading"><div><p className={styles.eyebrow}><MessageCircle size={16}/> Flow A</p><h2 id="conversation-heading">Continuous transaction conversation</h2></div>
      <div className={styles.transcript} aria-live="polite">{turns.length ? turns.map((turn, index) => <article key={`${turn.role}-${index}`} className={turn.role === "user" ? styles.user : styles.assistant}><strong>{turn.role === "user" ? "You" : "Covarify"}</strong><p>{turn.text}</p></article>) : <p className={styles.empty}>Try the guided prompts below.</p>}</div>
      <div className={styles.prompts}>{["How many payments were made to OLU’KAI?", "Which card did I use?", "One was a birthday gift for Caleb.", "The $89 one was a birthday gift for Caleb.", "My son."].map((prompt) => <button key={prompt} type="button" onClick={() => send(prompt, "tap")} aria-label={`Send guided prompt: ${prompt}`}>{prompt}</button>)}</div>
      <section className={styles.voice} aria-label="Voice input controls"><div className={styles.voiceControls}><button type="button" onClick={voice.listening ? voice.stop : startVoice} disabled={voice.supported === false} aria-label={voice.listening ? "Stop microphone" : "Start microphone"} aria-pressed={voice.listening}>{voice.listening ? <><Square size={15}/> Stop microphone</> : <><Mic size={17}/> Start microphone</>}</button><fieldset className={styles.autoSend}><legend>Voice auto-send</legend><label><input type="radio" name="voice-auto-send" checked={voiceAutoSend} onChange={() => setVoiceAutoSend(true)}/> On</label><label><input type="radio" name="voice-auto-send" checked={!voiceAutoSend} onChange={() => setVoiceAutoSend(false)}/> Off</label></fieldset><label className={styles.speechToggle}><input type="checkbox" checked={speakResponses} onChange={(event) => { setSpeakResponses(event.target.checked); if (!event.target.checked) stopSpeaking(); }}/><Volume2 size={17}/> Speak responses <small>(Browser fallback)</small></label>{speaking ? <button type="button" onClick={stopSpeaking} aria-label="Stop speaking"><Square size={15}/> Stop speaking</button> : null}</div><p className={styles.voiceStatus} aria-live="polite">{voice.status}</p><p><strong>Browser fallback:</strong> browser-generated speech is non-production and is available only to test exact-text speech, interruption, accessibility fallback, and graceful disablement. Voice recognition may use your browser or platform’s remote speech service. Audio is not stored by this Covarify preview.</p>{voice.supported === false ? <p><strong>Voice recognition is unavailable.</strong> The complete text path remains available.</p> : null}</section>
      {incomingVoiceDraft ? <section className={styles.review} role="alert"><strong>Keep your typed draft?</strong><p>Voice heard: “{incomingVoiceDraft.transcript}”</p><div className={styles.reviewActions}><button type="button" onClick={() => { setText(incomingVoiceDraft.transcript); setTranscriptMeta(incomingVoiceDraft.meta); setDraftOrigin("voice"); setIncomingVoiceDraft(null); }}>Replace draft</button><button type="button" onClick={() => { setText((draft) => `${draft.trim()} ${incomingVoiceDraft.transcript}`.trim()); setTranscriptMeta({ ...incomingVoiceDraft.meta, autoSend: false, reviewRequired: true, reason: "A typed and voice draft were deliberately combined." }); setDraftOrigin("typed"); setIncomingVoiceDraft(null); }}>Append</button><button type="button" onClick={() => setIncomingVoiceDraft(null)}>Cancel</button></div></section> : null}
      <label>Message<textarea value={text} onChange={(event) => { setText(event.target.value); setDraftOrigin(event.target.value ? "typed" : null); if (transcriptMeta) setTranscriptMeta({ ...transcriptMeta, autoSend: false, reviewRequired: true, reason: "The transcript was edited and must be reviewed." }); }} onKeyDown={(event) => { if ((event.ctrlKey || event.metaKey) && event.key === "Enter") send(); }} /></label>{transcriptMeta ? <section className={styles.review} role="status"><strong>{transcriptMeta.autoSend && voiceAutoSend ? "Safe voice turn — sending…" : "Transcript review required."}</strong><p>{transcriptMeta.reason}</p>{transcriptMeta.correction ? <><p>I heard “{transcriptMeta.correction.heard}.” Did you mean {transcriptMeta.correction.canonical}?</p><div className={styles.reviewActions}><button type="button" onClick={() => { const corrected = transcriptMeta.correction!.correctedTranscript; if (voiceAutoSend) send(corrected, "voice"); else { setText(corrected); setDraftOrigin("voice"); setTranscriptMeta({ ...transcriptMeta, correction: null, autoSend: false, reviewRequired: true, reason: "Canonical merchant accepted. Voice auto-send is Off; select Send when ready." }); } }}>Yes, use {transcriptMeta.correction.canonical}</button><button type="button" onClick={() => document.querySelector<HTMLTextAreaElement>("textarea")?.focus()}>Edit transcript</button><button type="button" onClick={() => { setText(""); setTranscriptMeta(null); setDraftOrigin(null); startVoice(); }}>Try again</button></div></> : <p>Correct merchant names, people, amounts, dates, accounts, and confirmation language before sending.</p>}<small>Recognition confidence and transcript corrections are temporary session metadata and are not Financial Memory.</small></section> : null}<button className={styles.primary} type="button" onClick={() => send()}>Send <ArrowRight size={16}/></button>
      {response?.evidence ? <details><summary>View simulated supporting evidence</summary><p>{response.evidence.transactionIds.length} exact simulated transactions · {response.evidence.period.label}</p><p>{response.evidence.limitations.join(" ")}</p></details> : null}
      {response?.proposal ? <section className={styles.proposal} aria-label="Proposed change requiring confirmation"><strong>Proposal · confirmation required</strong>{response.proposal.values.map((value) => <p key={value.label}>{value.label}: {value.value}</p>)}<p>No durable change occurs in this preview.</p></section> : null}
      {response ? <aside className={styles.next} aria-label="Primary next best step"><small>Next best step</small><strong>{response.nextBestStep.label}</strong><p>{response.nextBestStep.reason}</p></aside> : null}
    </section>
    <section className={styles.workspace} aria-labelledby="strategy-heading"><div><p className={styles.eyebrow}><ShieldCheck size={16}/> Flow B</p><h2 id="strategy-heading">Rent recovery strategy preview</h2><p className={styles.fact}><strong>Known fact:</strong> The Heights payment was {money(1700)}. Payment amount and normal monthly rent remain separate.</p></div>
      {!goalConfirmed ? <div className={styles.goal}><p><strong>Possible goal:</strong> Catch up on The Heights rent.</p><button className={styles.primary} type="button" onClick={() => { setGoalConfirmed(true); setInputStep(0); }}>Yes, use this goal</button><button type="button">Choose a different goal</button></div> : <p className={styles.confirmed}><CheckCircle2 size={18}/> User-confirmed goal: catch up on The Heights rent</p>}
      {goalConfirmed ? <div className={styles.confirmedFacts} aria-label="User-provided confirmed facts">{inputStep >= 1 ? <p><strong>Normal monthly rent:</strong> {money(Number(normalRent))} <button type="button" onClick={() => { setInputStep(0); setTargetMode(null); }}>Change</button></p> : null}{inputStep >= 2 ? <p><strong>Currently outstanding:</strong> {money(Number(outstanding))} <button type="button" onClick={() => { setInputStep(1); setTargetMode(null); }}>Change</button></p> : null}{targetMode ? <p><strong>Target approach:</strong> {targetMode.replaceAll("_", " ")} <button type="button" onClick={() => { setTargetMode(null); setDeadline(""); setMonthlyContribution(""); setProposedTargetConfirmed(false); }}>Change</button></p> : null}{targetMode === "fixed_date" && deadline ? <p><strong>User-provided target date:</strong> {deadline} <button type="button" onClick={() => setDeadline("")}>Change</button></p> : null}{targetMode === "monthly_contribution_target" && monthlyContribution ? <p><strong>Monthly contribution target:</strong> {monthlyContribution === "suggest" ? "Covarify suggestion requested" : money(Number(monthlyContribution))} <button type="button" onClick={() => setMonthlyContribution("")}>Change</button></p> : null}</div> : null}
      {goalConfirmed && inputStep < 2 ? <div className={styles.singleQuestion} aria-label="Current unanswered question"><strong>One question at a time</strong>{inputStep === 0 ? <label>What is your normal monthly rent?<input autoFocus inputMode="decimal" value={normalRent} onChange={(event) => setNormalRent(event.target.value)} onKeyDown={(event) => event.key === "Enter" && normalRent && setInputStep(1)} /></label> : <label>How much is currently outstanding?<input autoFocus inputMode="decimal" value={outstanding} onChange={(event) => setOutstanding(event.target.value)} onKeyDown={(event) => event.key === "Enter" && outstanding && setInputStep(2)} /></label>}<button className={styles.primary} type="button" disabled={inputStep === 0 ? !normalRent : !outstanding} onClick={() => setInputStep((step) => Math.min(2, step + 1))}>Continue</button></div> : null}
      {goalConfirmed && inputStep >= 2 && !targetMode ? <div className={styles.singleQuestion} aria-label="Choose recovery timeline approach"><strong>One question at a time</strong><p>Do you already have a date you want to be caught up by, or should I show you realistic timelines based on your current financial picture?</p><p>You do not need to choose a date first.</p><div className={styles.modeActions}><button type="button" onClick={() => setTargetMode("fixed_date")}>I have a date</button><button type="button" onClick={() => setTargetMode("suggested_date")}>Show me realistic timelines</button><button type="button" onClick={() => setTargetMode("monthly_contribution_target")}>I want steady monthly progress</button><button type="button" onClick={() => setTargetMode("as_soon_as_practical")}>As soon as practical</button></div></div> : null}
      {targetMode === "fixed_date" && !deadline ? <div className={styles.singleQuestion} aria-label="Current unanswered question"><strong>One question at a time</strong><label>When do you want to be caught up?<input autoFocus type="date" value={deadline} onChange={(event) => setDeadline(event.target.value)} /></label></div> : null}
      {targetMode === "monthly_contribution_target" && !monthlyContribution ? <div className={styles.singleQuestion} aria-label="Current unanswered question"><strong>One question at a time</strong><p>How much would you like to put toward catching up each month, or should I suggest an amount?</p><label>Monthly contribution<input autoFocus inputMode="decimal" value={monthlyContribution} onChange={(event) => setMonthlyContribution(event.target.value)} /></label><button type="button" onClick={() => setMonthlyContribution("suggest")}>Suggest a sustainable amount</button></div> : null}
      {options.length ? <label className={styles.constraint}><input type="checkbox" checked={protectCallie} onChange={(event) => { setProtectCallie(event.target.checked); setOptionReviewed(false); setProposedTargetConfirmed(false); }}/> Do you want me to protect Callie’s activities from these options? {protectCallie ? <small>Plan-scoped protected priority</small> : null}</label> : null}
      {options.length && !optionReviewed ? <button className={styles.primary} type="button" onClick={() => setOptionReviewed(true)}>Compare these recovery options</button> : null}
      <div className={styles.situation} aria-label="Whole-picture situation preview"><article><small>Known cash</small><strong>{money(situation.availableCash || 0)}</strong><span>{money(gap.protectedReserve || 0)} reserve protected</span></article><article><small>Required minimums</small><strong>{money(situation.requiredMinimums || 0)}</strong><span>Protected</span></article><article><small>Investments</small><strong>{money(situation.investmentsExcluded || 0)}</strong><span>Excluded from available cash</span></article><article><small>Calculated remaining gap</small><strong>{gap.estimatedShortfall == null ? "Missing financial evidence" : money(gap.estimatedShortfall)}</strong><span>{gap.confidence === "low" ? "Incomplete confidence" : "High confidence for this fixture"}</span></article></div>
      {inputStep >= 2 ? <details className={styles.reconciliation}><summary>How available-for-goal cash was reconciled</summary><p>Analysis window: {gap.analysisWindow?.start} through {gap.analysisWindow?.end}. Expected income is limited to this window.</p>{gap.reconciliation.map((line) => <p key={line.key}><span>{line.label}</span><strong>{line.amount == null ? "Unknown" : money(line.amount)}</strong><small>{line.dataStatus} · {line.evidenceIds.length} evidence reference{line.evidenceIds.length === 1 ? "" : "s"}</small></p>)}</details> : null}
      {gap.estimatedShortfall === 0 ? <aside className={styles.missing} aria-label="Zero gap explanation"><strong>No reduction gap found from current fixture evidence</strong><p>The known resources appear sufficient for the outstanding amount after modeled protections. This remains a preview and must be revisited if obligations or timing change.</p></aside> : null}
      {targetMode === "fixed_date" && deadline && fixedRequiredPace != null ? <aside className={styles.feasibility}><strong>Fixed-date feasibility</strong><p>This user-provided date requires about {money(fixedRequiredPace)} per month for {fixedMonths} month{fixedMonths === 1 ? "" : "s"}. It {levers.reduce((sum, lever) => sum + (lever.estimatedAmount || 0), 0) >= fixedRequiredPace ? "appears achievable from the modeled levers" : "does not appear achievable from current modeled levers; compare a longer timeline"}. This is an estimate, not a guarantee.</p></aside> : null}
      {options.length ? <><div className={styles.levers}><h3>Evidence-backed levers</h3>{levers.map((lever) => <article key={lever.id}><div><strong>{lever.label}</strong><span>{lever.evidenceIds.length} supporting transactions · {lever.timeframe} · {lever.confidence} confidence</span></div><strong>About {money(lever.estimatedAmount || 0)}</strong><p>{lever.tradeoff} {lever.reversible ? "Reversible." : "Not readily reversible."} {lever.confirmationRequired ? "Confirmation required." : ""}</p></article>)}</div><div className={styles.options} aria-label="Strategy options">{options.map((option) => { const timeline = "durationMonths" in option ? option : null; return <article key={option.name} className={strategy?.recommended.name === option.name ? styles.recommended : undefined}><small>{strategy?.recommended.name === option.name ? "Recommended proposal" : "Alternative proposal"}</small><h3>{option.name}</h3>{timeline ? <><strong>About {timeline.durationMonths} month{timeline.durationMonths === 1 ? "" : "s"}</strong><p>{money(timeline.contributionPerMonth)} per month · estimated {timeline.projectedCompletionDate}</p></> : <strong>{money(option.expectedContribution)} projected</strong>}<p>{option.levers.map((lever) => lever.label).join(" + ") || "Use the confirmed contribution target"}</p><p><strong>Protected:</strong> {option.protectedExpenses.length ? option.protectedExpenses.join(", ") : "Required obligations, essentials, and reserve"}</p><p>{option.tradeoffs[0] || "Keeps the modeled protections intact."}</p><button type="button" aria-pressed={chosen?.name === option.name} onClick={() => { setSelectedOption(option.name); setProposedTargetConfirmed(false); }}>Preview {option.name}</button><details><summary>Evidence, assumptions, and uncertainty</summary><p>{option.evidenceIds.length} exact evidence references · {option.confidence} confidence</p><p>{option.assumptions.join(" ")}</p>{timeline ? <p>Could change if {timeline.whatCouldChange.join(", ")}.</p> : null}</details></article>; })}</div></> : null}
      {strategy && chosen ? <section className={styles.rationale} aria-label="Recommended strategy rationale"><h3>Why {strategy.recommended.name} ranks highest</h3>{strategy.whyHighest.map((reason) => <p key={reason}>{reason}</p>)}<p><strong>Confidence:</strong> {strategy.confidence}</p><p><strong>Could change if:</strong> {strategy.changesIf.join(", ")}.</p>{targetMode !== "fixed_date" ? <div className={styles.modeActions}><button type="button" onClick={() => { setProposedTargetConfirmed(true); }}>Use the {chosen.name.toLowerCase()} timeline as my proposed target</button><button type="button" onClick={() => { setTargetMode("flexible_timeline"); setProposedTargetConfirmed(false); }}>Keep my timeline flexible</button></div> : null}<p><strong>Status:</strong> {proposedTargetConfirmed ? "Explicitly confirmed in this temporary preview session; not saved or activated." : "Proposed only — not confirmed, saved, or active."}</p></section> : null}
      <aside className={styles.next} aria-label="Primary next best step"><small>Next best step</small><strong>{next.label}</strong><p>{next.reason}</p></aside>
      <footer><strong>Read-only strategy preview</strong><p>Plan activation and durable saving are not available in this controlled phase.</p><button className={styles.primary} type="button" disabled>Activate plan — not available</button></footer>
    </section>
  </main>;
}
