"use client";

import { useMemo, useState } from "react";
import { Banknote, BriefcaseBusiness, RotateCcw } from "lucide-react";
import { allocationWithOffAccountCash, allocationWithReceivedOwnerFunds, cashIncomeFixture, conservativeCashEstimate, offAccountMemoryMapping, receivableFixture, reconcileCashIncome, reconcileDeposit, reconcileReceivable, simulateReceivable } from "@/lib/conversation/off-account-resources";
import styles from "./conversation-strategy-preview.module.css";

const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
type CashStage = "expected" | "received" | "spent" | "deposited";
type InvoiceScenario = "baseline" | "pays_friday" | "two_weeks_late" | "half_paid" | "disputed";

export function OffAccountResourcePreview() {
  const [cashStage, setCashStage] = useState<CashStage>("expected"); const [protectCash, setProtectCash] = useState(false); const [invoiceScenario, setInvoiceScenario] = useState<InvoiceScenario>("baseline");
  const cash = useMemo(() => cashIncomeFixture(cashStage === "expected" ? {} : cashStage === "received" ? { expected: false, grossAmount: 240, cashOnHand: 240, confirmed: true, state: "confirmed_cash_on_hand", confidence: "high" } : cashStage === "spent" ? { expected: false, grossAmount: 240, cashOnHand: 150, alreadySpent: 90, protectedAmount: protectCash ? 100 : 0, confirmed: true, state: protectCash ? "protected" : "partially_spent", confidence: "high" } : { expected: false, grossAmount: 240, cashOnHand: 0, deposited: 150, alreadySpent: 90, protectedAmount: protectCash ? 100 : 0, confirmed: true, state: protectCash ? "protected" : "deposited", confidence: "high" }), [cashStage, protectCash]);
  const cashReconciliation = useMemo(() => reconcileCashIncome(cash), [cash]); const cashAllocation = useMemo(() => allocationWithOffAccountCash(cash), [cash]);
  const invoice = useMemo(() => receivableFixture(), []); const baselineInvoice = useMemo(() => reconcileReceivable(invoice, { start: "2026-08-04", end: "2026-08-20" }), [invoice]); const invoiceSimulation = invoiceScenario === "baseline" ? null : simulateReceivable(invoice, invoiceScenario);
  const shownInvoice = invoiceSimulation?.result || baselineInvoice; const estimate = conservativeCashEstimate({ low: 140, typical: 200, high: 260, userOverride: null }); const memory = offAccountMemoryMapping();
  const invoiceAllocation = useMemo(() => allocationWithReceivedOwnerFunds(shownInvoice), [shownInvoice]);
  const currentRent = cashAllocation.options[0]?.allocations.find((line) => line.needId === "current-rent")?.allocated || 0;
  const depositTrace = cashStage === "deposited" ? reconcileDeposit({ sourceKey: cash.reconciliationKey, receiptAmount: 150, depositAmount: 150 }) : null;

  return <section className={styles.resourceExtension} aria-labelledby="off-account-heading">
    <div><p className={styles.eyebrow}>Resource extension</p><h3 id="off-account-heading">Cash and business receivables</h3><p>These fixtures feed the same allocation intelligence. Expected money remains separate from money available today.</p></div>
    <section className={styles.resourceScenario} aria-labelledby="cash-scenario-heading"><div className={styles.scenarioHeading}><Banknote size={20}/><div><small>Scenario A</small><h3 id="cash-scenario-heading">Bartending tips</h3></div></div>
      <div className={styles.resourceSummary}><article><small>Connected cash</small><strong>{money(900)}</strong></article><article><small>Expected tips</small><strong>{money(200)}</strong><span>Future · medium confidence</span></article><article><small>Confirmed available now</small><strong>{money(cashReconciliation.totalAvailableContribution)}</strong><span>{cashStage === "expected" ? "Not received" : cash.state.replaceAll("_", " ")}</span></article><article><small>Total current resources</small><strong>{money(cashAllocation.availableBeforeNextIncome)}</strong><span>No duplicate deposits</span></article></div>
      {cashStage === "expected" ? <div className={styles.singleQuestion} aria-live="polite"><small>One material question</small><h4>How much of those tips do you expect to still have available?</h4><p>Recent Friday tips were {money(140)}–{money(260)}. The conservative planning estimate is {money(estimate.planningEstimate)}, but it is not available today.</p><button type="button" onClick={() => setCashStage("received")}>I made $240 and still have all of it</button></div> : <div className={styles.resourceActions}><button type="button" onClick={() => setCashStage("spent")}>I spent $90</button><button type="button" disabled={cashStage !== "spent"} onClick={() => setCashStage("deposited")}>I deposited the rest</button><button type="button" onClick={() => { setCashStage("expected"); setProtectCash(false); }}>Reset cash baseline</button></div>}
      {cashStage !== "expected" ? <label className={styles.constraint}><input type="checkbox" checked={protectCash} onChange={(event) => setProtectCash(event.target.checked)}/> Keep {money(100)} of these tips for groceries <small>Temporary, event-scoped protection</small></label> : null}
      <aside className={styles.reconciliation} aria-label="Cash reconciliation"><p><span>Earned</span><strong>{money(cashReconciliation.earned)}</strong></p><p><span>Already spent</span><strong>−{money(cashReconciliation.spent)}</strong></p><p><span>Protected</span><strong>−{money(cashReconciliation.protected)}</strong></p><p><span>Available for allocation</span><strong>{money(cashReconciliation.totalAvailableContribution)}</strong><small>{cashReconciliation.explanation}</small></p>{depositTrace ? <p><span>Deposit reconciliation</span><strong>One inflow</strong><small>{depositTrace.explanation}</small></p> : null}</aside>
      <p><strong>Allocation change:</strong> Current-rent reserve is now {money(currentRent)} using {money(cashAllocation.availableBeforeNextIncome)} confirmed current resources. The work-critical repair and card minimum remain protected.</p>
    </section>
    <section className={styles.resourceScenario} aria-labelledby="invoice-scenario-heading"><div className={styles.scenarioHeading}><BriefcaseBusiness size={20}/><div><small>Scenario B</small><h3 id="invoice-scenario-heading">Outstanding sole-proprietor invoice</h3></div></div>
      <div className={styles.resourceSummary}><article><small>Gross invoice</small><strong>{money(2500)}</strong></article><article><small>Materials</small><strong>−{money(300)}</strong></article><article><small>Tax reserve</small><strong>−{money(625)}</strong><span>User-confirmed 25% · no tax conclusion</span></article><article><small>Provisional owner-available</small><strong>{money(1575)}</strong><span>Expected, not current cash</span></article></div>
      <p className={styles.fact}>I found a {money(2500)} invoice due Friday from a reliable fixture client. After the confirmed materials cost and user-confirmed reserve, about {money(1575)} may be owner-available. Payment is scheduled, so no additional timing question is needed.</p>
      <div className={styles.resourceActions} aria-label="Invoice what-if scenarios"><button type="button" onClick={() => setInvoiceScenario("pays_friday")}>What if it pays Friday?</button><button type="button" onClick={() => setInvoiceScenario("two_weeks_late")}>What if it is two weeks late?</button><button type="button" onClick={() => setInvoiceScenario("half_paid")}>What if only half is paid?</button><button type="button" onClick={() => setInvoiceScenario("disputed")}>What if the client disputes it?</button></div>
      {invoiceSimulation ? <section className={styles.simulated} aria-live="polite"><small>Simulated · baseline preserved · not active</small><h4>{invoiceSimulation.changedAssumptions[0]}</h4><p>Received: {money(shownInvoice.received)} · Remaining receivable: {money(shownInvoice.remaining)} · Current owner-available cash: {money(shownInvoice.currentPersonalCash)} · Future planning amount: {money(shownInvoice.futurePlanningAmount)}.</p><p>{shownInvoice.explanation}</p><p><strong>Simulated current allocation ceiling:</strong> {money(invoiceAllocation.availableBeforeNextIncome)}. Only received owner-available funds are added to the {money(900)} baseline.</p><button type="button" onClick={() => setInvoiceScenario("baseline")}><RotateCcw size={16}/> Reset invoice baseline</button></section> : <aside className={styles.preliminary}><small>Expected future business income</small><p>{shownInvoice.explanation} The current allocation still uses only {money(900)}.</p><p><strong>Dependency:</strong> Future planning may include {money(shownInvoice.futurePlanningAmount)} only if payment arrives inside the window and business protections remain unchanged.</p></aside>}
      <details className={styles.audit}><summary>Invoice reconciliation and boundaries</summary><p>Gross: {money(shownInvoice.gross)}</p><p>Received: {money(shownInvoice.received)}</p><p>Remaining receivable: {money(shownInvoice.remaining)}</p><p>Business costs applied to received funds: {money(shownInvoice.businessCostsApplied)}</p><p>Tax reserve applied to received funds: {money(shownInvoice.taxReserveApplied)}</p><p>Owner-available from received funds: {money(shownInvoice.receivedOwnerAvailable)}</p><p>Collection confidence: {shownInvoice.confidence}</p><p>Reconciliation key: {invoice.reconciliationKey}</p></details>
    </section>
    <details className={styles.audit}><summary>Governed memory boundary</summary><p>{memory.temporary.join(", ")} remain temporary.</p><p>Confirmed facts are only durable candidates with governed metadata; persistence implemented: {String(memory.persistenceImplemented)}.</p><p>{memory.neverCanonical.join(", ")} are never canonical memory.</p></details>
    <p className={styles.fact}><strong>Read-only boundary:</strong> Cash statements, invoice states, deposits, protections, and simulations remain session-only fixtures. Nothing is saved, activated, or written to Financial Memory.</p>
  </section>;
}
