import type { DocumentRecord, FinancialEvent, Person, Transaction } from "./types";

export const samplePeople: Person[] = [
  {
    id: "person-b",
    name: "B",
    relationship: "Partner",
    notes: "Used in sample relationship memories without exposing private detail.",
  },
];

export const sampleTransactions: Transaction[] = [
  {
    id: "txn-home-depot-backyard",
    merchant: "Home Depot",
    amount: 257.69,
    date: "2026-05-04",
    accountName: "Everyday Checking",
    paymentMethod: "Debit card",
    rawDescription: "HOME DEPOT 257.69 GARDEN CENTER",
    categoryGuess: "Home",
    linkedEventId: "event-backyard-refresh",
    receiptId: "doc-home-depot-receipt",
  },
  {
    id: "txn-vegas-hotel",
    merchant: "The Cosmopolitan Las Vegas",
    amount: 428.16,
    date: "2026-04-18",
    accountName: "Travel Rewards Card",
    paymentMethod: "Credit card",
    rawDescription: "COSMOPOLITAN LAS VEGAS HOTEL",
    categoryGuess: "Travel",
    linkedEventId: "event-vegas-trip",
  },
  {
    id: "txn-vegas-dinner",
    merchant: "Best Friend",
    amount: 86.42,
    date: "2026-04-19",
    accountName: "Travel Rewards Card",
    paymentMethod: "Credit card",
    rawDescription: "BEST FRIEND LAS VEGAS NV",
    categoryGuess: "Food",
    linkedEventId: "event-vegas-trip",
  },
  {
    id: "txn-vegas-rideshare",
    merchant: "Lyft",
    amount: 24.9,
    date: "2026-04-19",
    accountName: "Travel Rewards Card",
    paymentMethod: "Credit card",
    rawDescription: "LYFT RIDE LAS VEGAS",
    categoryGuess: "Transportation",
    linkedEventId: "event-vegas-trip",
  },
  {
    id: "txn-card-payment",
    merchant: "Capital One",
    amount: 350,
    date: "2026-05-10",
    accountName: "Everyday Checking",
    paymentMethod: "ACH payment",
    rawDescription: "CAPITAL ONE ONLINE PAYMENT",
    categoryGuess: "Debt",
    linkedEventId: "event-credit-card-payoff",
  },
  {
    id: "txn-covarum-domain",
    merchant: "Namecheap",
    amount: 18.98,
    date: "2026-03-12",
    accountName: "Business Checking",
    paymentMethod: "Business debit card",
    rawDescription: "NAMECHEAP INC DOMAIN REGISTRATION",
    categoryGuess: "Business",
    linkedEventId: "event-covarum-setup",
    receiptId: "doc-namecheap-invoice",
  },
  {
    id: "txn-covarum-software",
    merchant: "Google Workspace",
    amount: 14.4,
    date: "2026-03-14",
    accountName: "Business Checking",
    paymentMethod: "Business debit card",
    rawDescription: "GOOGLE WORKSPACE SUBSCRIPTION",
    categoryGuess: "Business",
    linkedEventId: "event-covarum-setup",
    receiptId: "doc-google-workspace-invoice",
  },
  {
    id: "txn-anniversary-flowers",
    merchant: "Local Flower Studio",
    amount: 64.28,
    date: "2026-02-13",
    accountName: "Everyday Checking",
    paymentMethod: "Debit card",
    rawDescription: "LOCAL FLOWER STUDIO",
    categoryGuess: "Relationships",
    linkedEventId: "event-anniversary-flowers",
    receiptId: "doc-anniversary-flowers-receipt",
  },
];

export const sampleDocuments: DocumentRecord[] = [
  {
    id: "doc-home-depot-receipt",
    type: "receipt",
    title: "Home Depot garden receipt",
    date: "2026-05-04",
    linkedEventId: "event-backyard-refresh",
    linkedTransactionId: "txn-home-depot-backyard",
    tags: ["home", "garden", "project"],
    retentionReason: "Useful for returns, warranty context, and remembering project materials.",
  },
  {
    id: "doc-backyard-photo",
    type: "photo",
    title: "Backyard refresh progress photo",
    date: "2026-05-05",
    linkedEventId: "event-backyard-refresh",
    tags: ["home", "memory"],
    retentionReason: "Preserves the project context beyond the receipt.",
  },
  {
    id: "doc-namecheap-invoice",
    type: "invoice",
    title: "Domain registration invoice",
    date: "2026-03-12",
    linkedEventId: "event-covarum-setup",
    linkedTransactionId: "txn-covarum-domain",
    tags: ["business", "tax"],
    retentionReason: "Business and tax documentation.",
  },
  {
    id: "doc-google-workspace-invoice",
    type: "invoice",
    title: "Workspace software invoice",
    date: "2026-03-14",
    linkedEventId: "event-covarum-setup",
    linkedTransactionId: "txn-covarum-software",
    tags: ["business", "tax", "software"],
    retentionReason: "Business expense support for tax prep.",
  },
  {
    id: "doc-anniversary-flowers-receipt",
    type: "receipt",
    title: "Flowers for B anniversary receipt",
    date: "2026-02-13",
    linkedEventId: "event-anniversary-flowers",
    linkedTransactionId: "txn-anniversary-flowers",
    tags: ["relationship", "anniversary"],
    retentionReason: "Context for a relationship memory, not a cost-first record.",
  },
];

export const sampleFinancialEvents: FinancialEvent[] = [
  {
    id: "event-backyard-refresh",
    title: "Backyard Refresh",
    eventType: "project",
    lifeBucket: "Home",
    people: [],
    project: "Backyard Refresh",
    purpose: "Outdoor improvement",
    notes: "Plants, pots, and supplies for a calmer outdoor space.",
    startDate: "2026-05-04",
    endDate: "2026-05-05",
    transactionIds: ["txn-home-depot-backyard"],
    documentIds: ["doc-home-depot-receipt", "doc-backyard-photo"],
    tags: ["home", "garden", "project"],
    showMoneyByDefault: false,
    taxRelevant: false,
    businessRelevant: false,
  },
  {
    id: "event-vegas-trip",
    title: "Vegas Trip",
    eventType: "travel",
    lifeBucket: "Travel",
    people: [],
    project: "Vegas Trip",
    purpose: "Travel and shared experience",
    notes: "Hotel, dinner, and ride share activity grouped into one travel memory.",
    startDate: "2026-04-18",
    endDate: "2026-04-20",
    transactionIds: ["txn-vegas-hotel", "txn-vegas-dinner", "txn-vegas-rideshare"],
    documentIds: [],
    tags: ["travel", "experience"],
    showMoneyByDefault: false,
    taxRelevant: false,
    businessRelevant: false,
  },
  {
    id: "event-credit-card-payoff",
    title: "Credit Card Payoff",
    eventType: "debt_plan",
    lifeBucket: "Debt",
    people: [],
    project: "Credit Card Payoff",
    purpose: "Reduce revolving debt",
    notes: "Money is central because payoff decisions depend on balances, rates, and cash flow.",
    startDate: "2026-05-10",
    transactionIds: ["txn-card-payment"],
    documentIds: [],
    tags: ["debt", "payoff", "planning"],
    showMoneyByDefault: true,
    taxRelevant: false,
    businessRelevant: false,
  },
  {
    id: "event-covarum-setup",
    title: "Covarum Business Setup",
    eventType: "business_setup",
    lifeBucket: "Business",
    people: [],
    project: "Covarum Business Setup",
    purpose: "Business infrastructure",
    notes: "Early business setup costs that should remain easy to retrieve for records and tax prep.",
    startDate: "2026-03-12",
    endDate: "2026-03-14",
    transactionIds: ["txn-covarum-domain", "txn-covarum-software"],
    documentIds: ["doc-namecheap-invoice", "doc-google-workspace-invoice"],
    tags: ["business", "startup", "tax"],
    showMoneyByDefault: true,
    taxRelevant: true,
    businessRelevant: true,
  },
  {
    id: "event-anniversary-flowers",
    title: "Flowers for B Anniversary",
    eventType: "relationship_memory",
    lifeBucket: "Relationships",
    people: ["person-b"],
    project: "Anniversary",
    purpose: "Relationship care",
    notes: "A relationship moment where the meaning matters more than the price.",
    startDate: "2026-02-13",
    transactionIds: ["txn-anniversary-flowers"],
    documentIds: ["doc-anniversary-flowers-receipt"],
    tags: ["relationship", "anniversary"],
    showMoneyByDefault: false,
    taxRelevant: false,
    businessRelevant: false,
  },
];
