"use client";

import { useMemo, useState } from "react";
import { Check, ChevronDown, Plus, ShieldCheck, Trash2 } from "lucide-react";

type Account = { id: string; name: string; type: string; currentBalance: number | null };
type Transaction = { id: string; name: string; amount: number; date: string; category: string };
type DebtStrategy = { detected_credit_accounts: number; estimated_total_credit_balance: number; estimated_available_credit: number | null; estimated_credit_utilization_if_available: number | null; minimum_payment_data_status: string; apr_data_status: string; payment_strategy_note: string };
type Lever = { category: string; current_30_day_spend: number; estimated_savings: number; suggested_reduction: string };
type Debt = { id: string; manual: boolean; name: string; balance: string; minimum: string; statement: string; apr: string; due: string; planned: string };
type Scenario = "minimums" | "full" | "custom" | "flexible" | "consolidation";
type TxChoice = "none" | "skip" | "reduce" | "protect";

const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const number = (value: string) => Math.max(0, Number(value) || 0);
const categoryLabel = (value: string) => value.toLowerCase().replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const scenarioNames: Record<Scenario, string> = { minimums: "Minimums only this cycle", full: "Full / statement balance", custom: "Custom payment", flexible: "Flexible spending plan", consolidation: "Consolidation review" };

export function DecisionStudio({ accounts, debt, cashGap, totalCash, levers, transactions }: { accounts: Account[]; debt: DebtStrategy; cashGap: number; totalCash: number; levers: Lever[]; transactions: Transaction[] }) {
  const detected = accounts.filter((account) => account.type === "credit");
  const [debts, setDebts] = useState<Debt[]>(() => detected.map((account) => ({ id: account.id, manual: false, name: account.name, balance: String(account.currentBalance || ""), minimum: "", statement: "", apr: "", due: "", planned: "" })));
  const [scenario, setScenario] = useState<Scenario>(cashGap > 0 ? "minimums" : "flexible");
  const [customPayment, setCustomPayment] = useState("");
  const [reductions, setReductions] = useState<Record<string, number>>(() => Object.fromEntries(levers.map((lever) => [lever.category, lever.estimated_savings])));
  const [expanded, setExpanded] = useState<string | null>(null);
  const [merchantPlans, setMerchantPlans] = useState<Record<string, Record<string, number>>>({});
  const [txPlans, setTxPlans] = useState<Record<string, { choice: TxChoice; amount: number }>>({});
  const updateDebt = (id: string, key: keyof Debt, value: string) => setDebts((current) => current.map((item) => item.id === id ? { ...item, [key]: value } : item));
  const addDebt = () => setDebts((current) => [...current, { id: `manual-${Date.now()}`, manual: true, name: "Manual debt", balance: "", minimum: "", statement: "", apr: "", due: "", planned: "" }]);
  const setReduction = (category: string, amount: number) => { const currentSpend = levers.find((lever) => lever.category === category)?.current_30_day_spend || 0; setReductions((current) => ({ ...current, [category]: Math.min(currentSpend, Math.max(0, amount)) })); };
  const totals = useMemo(() => debts.reduce((sum, item) => ({ minimum: sum.minimum + number(item.minimum), full: sum.full + number(item.statement || item.balance), planned: sum.planned + number(item.planned), aprs: [...sum.aprs, ...(item.apr ? [number(item.apr)] : [])] }), { minimum: 0, full: 0, planned: 0, aprs: [] as number[] }), [debts]);
  const selectedSavings = Object.values(reductions).reduce((sum, amount) => sum + amount, 0);
  const modeledPayment = scenario === "minimums" ? totals.minimum : scenario === "full" ? totals.full : scenario === "custom" ? number(customPayment) : totals.planned;
  const paymentCashChange = totals.planned - modeledPayment;
  const cashFreed = paymentCashChange + selectedSavings;
  const remainingGap = Math.max(0, cashGap - cashFreed);
  const gapCovered = cashGap > 0 ? Math.max(0, Math.min(100, cashFreed / cashGap * 100)) : 100;
  const mode = cashGap > 0 ? "Catch-Up Mode" : totalCash < 1000 ? "Stability Mode" : "Progress Mode";
  const categoryTransactions = (category: string) => transactions.filter((transaction) => categoryLabel(transaction.category) === category && transaction.amount > 0);
  const merchantsFor = (category: string) => { const map = new Map<string,{amount:number;count:number}>(); for (const tx of categoryTransactions(category)) { const current = map.get(tx.name) || { amount: 0, count: 0 }; current.amount += tx.amount; current.count += 1; map.set(tx.name,current); } return [...map.entries()].map(([name,data]) => ({name,...data})).sort((a,b)=>b.amount-a.amount); };
  const applyMerchant = (category: string, merchant: string, amount: number) => { const next = { ...(merchantPlans[category] || {}), [merchant]: amount }; setMerchantPlans((current) => ({ ...current, [category]: next })); const transactionPlan = categoryTransactions(category).filter((tx) => txPlans[tx.id]?.choice !== "protect").reduce((sum,tx) => sum + (txPlans[tx.id]?.amount || 0),0); setReduction(category, Math.max(reductions[category] || 0, Object.values(next).reduce((sum,value)=>sum+value,0), transactionPlan)); };
  const applyTransaction = (category: string, tx: Transaction, choice: TxChoice) => { const amount = choice === "skip" ? tx.amount : choice === "reduce" ? tx.amount * .5 : 0; const next = { ...txPlans, [tx.id]: { choice, amount } }; setTxPlans(next); const txTotal = categoryTransactions(category).reduce((sum,item)=>sum+(next[item.id]?.amount||0),0); const merchantTotal = Object.values(merchantPlans[category] || {}).reduce((sum,value)=>sum+value,0); setReduction(category, Math.max(reductions[category] || 0, txTotal, merchantTotal)); };
  const firstWin = scenario === "full" && cashFreed < 0 ? "Paying the full balance may reduce interest, but it could increase short-term cash pressure in this sandbox history." : scenario === "minimums" ? "Paying minimums only this cycle may be a temporary catch-up move. It protects cash flow now but may increase interest if balances carry." : gapCovered >= 80 ? "Your first win may be to follow this plan for the next seven days before making extra debt payments." : `You selected changes that could cover ${Math.round(gapCovered)}% of the gap. Covarify would next look at bill timing, income timing, or one more flexible category.`;

  return <div className="decision-studio v1">
    <div className="mode-card"><div><p className="eyebrow plain">Current mode</p><h3>{mode}</h3><p>Based on available sandbox history, Covarify would look at cash-flow stability before optimizing longer-term progress.</p></div><span>Protect essentials first.</span></div>
    <section className="debt-assumptions"><div className="decision-heading"><div><p className="eyebrow plain">Debt Assumptions</p><h3>Model every card or debt in the decision.</h3></div><button className="add-debt" onClick={addDebt}><Plus size={14}/>Add manual debt</button></div><p className="helper-copy">Manual inputs are used only for sandbox decision modeling. Covarify needs minimums, APRs, statement balances, and due dates to compare payment strategies more accurately.</p><div className="debt-card-grid">{debts.map((item) => <article className="debt-card" key={item.id}><div className="debt-card-title"><input aria-label="Debt nickname" value={item.name} onChange={(event)=>updateDebt(item.id,"name",event.target.value)}/>{item.manual && <button aria-label="Remove manual debt" onClick={()=>setDebts((current)=>current.filter((debtItem)=>debtItem.id!==item.id))}><Trash2 size={14}/></button>}</div><div>{(["balance","minimum","statement","apr","due","planned"] as const).map((key)=><label key={key}><span>{{balance:"Current balance",minimum:"Minimum due",statement:"Statement balance",apr:"APR %",due:"Due date",planned:"Planned this cycle"}[key]}</span><input type={key==="due"?"date":"number"} min="0" step="0.01" value={item[key]} onChange={(event)=>updateDebt(item.id,key,event.target.value)} placeholder={key==="minimum"||key==="apr"?"Needed":"Optional"}/></label>)}</div></article>)}</div></section>
    <section><div className="decision-heading"><div><p className="eyebrow plain">Decision Studio v1</p><h3>Build one combined working plan.</h3></div><p>Choose what feels realistic. These are levers, not instructions.</p></div><div className="scenario-tabs">{(Object.keys(scenarioNames) as Scenario[]).map((item)=><button className={scenario===item?"active":""} onClick={()=>setScenario(item)} key={item}>{scenarioNames[item]}</button>)}</div>{scenario==="custom"&&<label className="custom-payment">Custom payment amount<input type="number" min="0" value={customPayment} onChange={(event)=>setCustomPayment(event.target.value)}/></label>}
      <div className="category-plans">{levers.map((lever)=>{const reduction=reductions[lever.category]||0; const txs=categoryTransactions(lever.category); const merchants=merchantsFor(lever.category); return <article className="category-plan" key={lever.category}><button className="category-toggle" onClick={()=>setExpanded(expanded===lever.category?null:lever.category)}><div><strong>{lever.category}</strong><span>{money(lever.current_30_day_spend)} across {txs.length} transactions</span></div><ChevronDown className={expanded===lever.category?"open":""} size={18}/></button><div className="reduction-controls"><span>Choose a reduction</span><div className="quick-buttons"><button onClick={()=>setReduction(lever.category,50)}>$50</button><button onClick={()=>setReduction(lever.category,100)}>$100</button><button onClick={()=>setReduction(lever.category,lever.current_30_day_spend*.15)}>15%</button><button onClick={()=>setReduction(lever.category,lever.current_30_day_spend*.25)}>25%</button></div><label>$<input aria-label={`${lever.category} custom reduction`} type="number" min="0" max={lever.current_30_day_spend} value={Math.round(reduction)} onChange={(event)=>setReduction(lever.category,number(event.target.value))}/></label></div><div className="category-impact"><span>New target <strong>{money(lever.current_30_day_spend-reduction)}</strong></span><span>Estimated cash freed <strong>{money(reduction)}</strong></span><span>{cashGap>0?`Closes ${Math.min(100,Math.round(reduction/cashGap*100))}% of gap`:`Could free ${money(reduction)} for savings, debt, or goals`}</span></div><p className="prospective">If similar spending repeats next month, this change could free up approximately {money(reduction)}.</p>
        {expanded===lever.category&&<div className="category-detail"><p>Use transactions as clues. Covarify is helping you plan future choices, not judge past ones.</p><h4>Merchant summary</h4>{merchants.slice(0,6).map((merchant)=><div className="merchant-row" key={merchant.name}><span><strong>{merchant.name}</strong>{money(merchant.amount)} across {merchant.count} transactions</span><div><button onClick={()=>applyMerchant(lever.category,merchant.name,merchant.amount)}>Pause next month</button><button onClick={()=>applyMerchant(lever.category,merchant.name,merchant.amount*.5)}>Reduce by 50%</button></div></div>)}<h4>Transaction examples</h4>{txs.slice(0,10).map((tx)=><div className="tx-plan" key={tx.id}><span><strong>{tx.name}</strong>{tx.date} · {money(tx.amount)}</span><select value={txPlans[tx.id]?.choice||"none"} onChange={(event)=>applyTransaction(lever.category,tx,event.target.value as TxChoice)}><option value="none">Use as clue</option><option value="skip">Would skip next time</option><option value="reduce">Would reduce 50%</option><option value="protect">Protect / not a cut</option></select></div>)}</div>}</article>})}</div>
      <div className="scorecard"><article><span>Cash impact this month</span><strong className={cashFreed>=0?"positive":"negative"}>{cashFreed>=0?"+":"−"}{money(Math.abs(cashFreed))}</strong></article><article><span>Cash gap remaining</span><strong>{money(remainingGap)}</strong></article><article><span>Gap closed</span><strong>{Math.round(gapCovered)}%</strong></article><article><span>Risk</span><strong>{scenario==="full"&&cashFreed<0?"High":"Low / Medium"}</strong></article><article><span>Confidence</span><strong>{totals.minimum||scenario!=="minimums"?"Medium":"Low"}</strong></article><article><span>Tradeoff</span><strong>{scenario==="minimums"?"Cash now / interest later":scenario==="full"?"Interest / cash pressure":"Flexibility / pace"}</strong></article></div>
      {scenario==="consolidation"&&<div className="consolidation-review"><h4>May be worth reviewing</h4><p>Total credit balance: {money(debt.estimated_total_credit_balance)} · Estimated minimums: {totals.minimum?money(totals.minimum):"missing"} · APRs: {totals.aprs.length?totals.aprs.map((apr)=>`${apr}%`).join(", "):"missing"}</p><p>Possible benefit: lower monthly pressure or a simpler structure. Review fees, promotional expiration, approval, credit inquiry, extended repayment, and balance re-use risk.</p></div>}
    </section>
    <section className="working-plan"><p className="eyebrow plain">My Working Plan</p><h3>{scenarioNames[scenario]}</h3><div><span>Flexible changes<strong>{levers.filter((lever)=>(reductions[lever.category]||0)>0).map((lever)=>`${lever.category} − ${money(reductions[lever.category])}`).join(", ")||"None selected"}</strong></span><span>Estimated cash freed<strong>{money(Math.max(0,cashFreed))}</strong></span><span>Remaining gap<strong>{money(remainingGap)}</strong></span><span>Gap covered<strong>{Math.round(gapCovered)}%</strong></span></div><p>{firstWin}</p><div className="plan-checklist"><span><Check size={14}/>Make required minimum payments only if selected.</span><span><Check size={14}/>Protect essential bills first.</span><span><Check size={14}/>Cap selected flexible categories this week.</span><span><Check size={14}/>Pause or reduce selected merchants.</span><span><Check size={14}/>Recheck after new transactions post.</span></div></section>
    <section className="protect-card"><ShieldCheck/><div><p className="eyebrow plain">Protect / review first</p><p>IRS · Mathnasium · medical · insurance · rent · utilities · minimum debt payments · childcare · transportation needed for work</p><small>Covarify protects required or important obligations from default savings suggestions. You can review them, but they are not first-cut items.</small></div></section>
  </div>;
}

// TODO: Save user plans after authentication, encrypted storage, Plaid Liabilities,
// bill due-date calendar, recurring merchant/subscription detection, protected labels,
// AI-assisted explanations, and compliance/legal review before public launch.
