"use client";

import { useMemo, useState } from "react";
import { Check, ShieldCheck } from "lucide-react";

type CreditAccount = { id: string; name: string; type: string; currentBalance: number | null };
type DebtStrategy = { detected_credit_accounts: number; estimated_total_credit_balance: number; estimated_available_credit: number | null; estimated_credit_utilization_if_available: number | null; minimum_payment_data_status: string; apr_data_status: string; payment_strategy_note: string };
type Lever = { category: string; estimated_savings: number; suggested_reduction: string };
type Assumption = { balance: string; minimum: string; statement: string; apr: string; due: string; planned: string };
type Scenario = "minimums" | "full" | "custom" | "flexible" | "consolidation";

const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const number = (value: string) => Math.max(0, Number(value) || 0);
const scenarioNames: Record<Scenario, string> = { minimums: "Pay minimums", full: "Pay full / statement", custom: "Custom payment", flexible: "Flexible spending", consolidation: "Consolidation review" };

export function DecisionStudio({ accounts, debt, cashGap, totalCash, levers }: { accounts: CreditAccount[]; debt: DebtStrategy; cashGap: number; totalCash: number; levers: Lever[] }) {
  const credit = accounts.filter((account) => account.type === "credit");
  const [scenario, setScenario] = useState<Scenario>(cashGap > 0 ? "minimums" : "flexible");
  const [custom, setCustom] = useState("");
  const [selectedLevers, setSelectedLevers] = useState<string[]>(levers.slice(0, 2).map((lever) => lever.category));
  const [assumptions, setAssumptions] = useState<Record<string, Assumption>>(() => Object.fromEntries(credit.map((account) => [account.id, { balance: String(account.currentBalance || ""), minimum: "", statement: "", apr: "", due: "", planned: "" }])));
  const update = (id: string, key: keyof Assumption, value: string) => setAssumptions((current) => ({ ...current, [id]: { ...current[id], [key]: value } }));
  const totals = useMemo(() => Object.values(assumptions).reduce((sum, item) => ({ minimum: sum.minimum + number(item.minimum), full: sum.full + number(item.statement || item.balance), planned: sum.planned + number(item.planned), aprs: [...sum.aprs, ...(item.apr ? [number(item.apr)] : [])] }), { minimum: 0, full: 0, planned: 0, aprs: [] as number[] }), [assumptions]);
  const selectedSavings = levers.filter((lever) => selectedLevers.includes(lever.category)).reduce((sum, lever) => sum + lever.estimated_savings, 0);
  const payment = scenario === "minimums" ? totals.minimum : scenario === "full" ? totals.full : scenario === "custom" ? number(custom) : 0;
  const savings = scenario === "flexible" || scenario === "minimums" ? selectedSavings : 0;
  const cashImpact = savings - payment;
  const remainingGap = Math.max(0, cashGap - savings + payment);
  const gapClosed = cashGap > 0 ? Math.max(0, Math.min(100, (cashGap - remainingGap) / cashGap * 100)) : 100;
  const missingMinimums = credit.length > 0 && totals.minimum === 0;
  const mode = cashGap > 0 ? "Catch-Up Mode" : totalCash < 1000 ? "Stability Mode" : "Progress Mode";
  const scenarioMessage = scenario === "minimums" ? (missingMinimums ? "Needs minimum payment amount." : "This may be a temporary stability move. It preserves cash but may increase interest while balances carry.") : scenario === "full" ? "Paying in full may reduce interest, but it can increase short-term cash pressure." : scenario === "custom" ? "A custom amount can balance debt progress with essential cash needs." : scenario === "flexible" ? "Selected flexible changes reduce pressure without changing required payments.": "May be worth reviewing, but this is a review flag—not a recommendation.";
  const scenarioAwareWin = scenario === "minimums" && remainingGap < cashGap ? "Your first win may be to make required minimum payments only this cycle, protect essentials, and use selected flexible changes to close the remaining gap. Treat this as temporary catch-up mode, not a long-term debt strategy." : scenario === "full" && remainingGap > cashGap ? "Paying the full balance may reduce interest, but based on this sandbox history it could increase short-term cash pressure. Covarify would compare this against minimums or a custom payment before choosing." : scenario === "flexible" && remainingGap === 0 ? "Your first win may be to lock in these flexible spending changes for the next seven days before adding extra debt payments." : scenario === "consolidation" ? "Consolidation may be worth reviewing, but Covarify needs APRs, fees, payment terms, and approval assumptions before treating it as a stronger path." : "Choose what feels realistic. Covarify is showing tradeoffs, not judging spending.";

  return <div className="decision-studio">
    <div className="mode-card"><div><p className="eyebrow plain">Current mode</p><h3>{mode}</h3><p>Based on available sandbox history, Covarify would look at cash-flow stability before optimizing longer-term progress.</p></div><span>Protect essentials first.</span></div>
    <section className="debt-assumptions"><div className="decision-heading"><div><p className="eyebrow plain">Debt Assumptions</p><h3>Add details to improve the comparison.</h3></div><p>Manual input used for sandbox decision modeling only.</p></div>{credit.length ? credit.map((account) => <div className="debt-row" key={account.id}><strong>{account.name}</strong>{(["balance","minimum","statement","apr","due","planned"] as const).map((key) => <label key={key}><span>{{balance:"Current balance",minimum:"Minimum due",statement:"Statement balance",apr:"APR %",due:"Due date",planned:"Planned payment"}[key]}</span><input type={key === "due" ? "date" : "number"} min="0" step="0.01" value={assumptions[account.id]?.[key] || ""} onChange={(event) => update(account.id, key, event.target.value)} placeholder={key === "minimum" || key === "apr" ? "Needed" : "Optional"} /></label>)}</div>) : <p className="empty-analysis">No credit-card accounts were detected in this sandbox item.</p>}<div className="missing-data">Covarify needs a few debt details to compare payment strategies more accurately. Add APR, minimum due, due date, and statement balance to improve this decision.</div></section>
    <section><div className="decision-heading"><div><p className="eyebrow plain">Decision Studio</p><h3>Test the tradeoffs before you decide.</h3></div><p>Covarify helps you see what each move changes.</p></div><div className="scenario-tabs">{(Object.keys(scenarioNames) as Scenario[]).map((item) => <button className={scenario === item ? "active" : ""} onClick={() => setScenario(item)} key={item}>{scenarioNames[item]}</button>)}</div>{scenario === "custom" && <label className="custom-payment">Custom payment amount<input type="number" min="0" value={custom} onChange={(event) => setCustom(event.target.value)} placeholder="0" /></label>}{(scenario === "flexible" || scenario === "minimums") && <div className="lever-choices">{levers.map((lever) => <label key={lever.category}><input type="checkbox" checked={selectedLevers.includes(lever.category)} onChange={() => setSelectedLevers((current) => current.includes(lever.category) ? current.filter((item) => item !== lever.category) : [...current, lever.category])} /><span>{lever.category}<small>{money(lever.estimated_savings)} estimated</small></span></label>)}</div>}
      <div className="scorecard"><article><span>Cash impact this month</span><strong className={cashImpact >= 0 ? "positive" : "negative"}>{cashImpact >= 0 ? "+" : "−"}{money(Math.abs(cashImpact))}</strong></article><article><span>Cash gap remaining</span><strong>{money(remainingGap)}</strong></article><article><span>Gap closed</span><strong>{Math.round(gapClosed)}%</strong></article><article><span>Interest / cost impact</span><strong>{totals.aprs.length ? "Estimated" : "Unknown"}</strong></article><article><span>Risk level</span><strong>{scenario === "full" && payment > totalCash ? "High" : scenario === "consolidation" ? "Medium" : "Low / Medium"}</strong></article><article><span>Confidence</span><strong>{missingMinimums && scenario === "minimums" ? "Low" : "Medium"}</strong></article></div><p className="scenario-message">{scenarioMessage}</p>
      {scenario === "consolidation" && <div className="consolidation-review"><h4>May be worth reviewing</h4><p>Total credit balance: {money(debt.estimated_total_credit_balance)} · Estimated minimums: {totals.minimum ? money(totals.minimum) : "missing"} · APRs: {totals.aprs.length ? totals.aprs.map((apr) => `${apr}%`).join(", ") : "missing"}</p><strong>Possible benefit</strong><p>Lower monthly pressure or a simpler payment structure.</p><strong>Risks to review</strong><p>Fees, promotional expiration, approval, a new credit inquiry, extending repayment, and running balances back up.</p></div>}
    </section>
    <section className="working-plan"><p className="eyebrow plain">My Working Plan</p><h3>{scenarioNames[scenario]}</h3><div><span>Selected savings levers<strong>{selectedLevers.length ? selectedLevers.join(", ") : "None selected"}</strong></span><span>Estimated cash freed<strong>{money(Math.max(0,cashImpact))}</strong></span><span>Remaining gap<strong>{money(remainingGap)}</strong></span></div><p>{scenarioAwareWin}</p><div className="plan-checklist"><span><Check size={14}/>Confirm required minimums and due dates.</span><span><Check size={14}/>Protect essential bills and near-term cash.</span><span><Check size={14}/>Review the plan again in seven days.</span></div></section>
    <section className="protect-card"><ShieldCheck /><div><p className="eyebrow plain">Protect these first</p><p>Essential bills · minimum required debt payments · taxes · insurance · medical · childcare / education · transportation needed for work</p><small>IRS and education-related transactions such as Mathnasium belong in review-first—not default cuts.</small></div></section>
  </div>;
}

// TODO: Plaid Liabilities integration, encrypted storage, authenticated user profiles,
// saved plans, real bill due-date calendar, consolidation offer comparison,
// balance-transfer modeling, production Plaid review, and compliance/legal review.
