"use server";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
const safeMessage = "We could not complete that request. Check your details and try again.";
export async function signIn(formData: FormData) { const email=String(formData.get("email")||""); const password=String(formData.get("password")||""); const requested=String(formData.get("next")||"/account"); const next=requested.startsWith("/")&&!requested.startsWith("//")?requested:"/account"; const { error }=await (await createSupabaseServerClient()).auth.signInWithPassword({email,password}); if(error) redirect(`/login?error=${encodeURIComponent(safeMessage)}&next=${encodeURIComponent(next)}`); redirect(next); }
export async function signUp(formData: FormData) { if(process.env.COVARIFY_PUBLIC_SIGNUPS_ENABLED!=="true") redirect("/signup?error=Covarify%20is%20currently%20a%20controlled%20beta."); const email=String(formData.get("email")||""); const password=String(formData.get("password")||""); const site=process.env.NEXT_PUBLIC_SITE_URL||"http://localhost:3000"; const { error }=await (await createSupabaseServerClient()).auth.signUp({email,password,options:{emailRedirectTo:`${site}/auth/callback?next=/account`}}); if(error) redirect(`/signup?error=${encodeURIComponent(safeMessage)}`); redirect("/login?message=Check%20your%20email%20to%20confirm%20your%20account."); }
export async function requestReset(formData: FormData) { const email=String(formData.get("email")||""); const site=process.env.NEXT_PUBLIC_SITE_URL||"http://localhost:3000"; await (await createSupabaseServerClient()).auth.resetPasswordForEmail(email,{redirectTo:`${site}/auth/callback?next=/reset-password`}); redirect("/forgot-password?message=If%20an%20account%20exists,%20a%20reset%20link%20has%20been%20sent."); }
export async function updatePassword(formData: FormData) { const password=String(formData.get("password")||""); const { error }=await (await createSupabaseServerClient()).auth.updateUser({password}); if(error) redirect(`/reset-password?error=${encodeURIComponent(safeMessage)}`); redirect("/account"); }
export async function signOut() { await (await createSupabaseServerClient()).auth.signOut(); redirect("/login"); }
