export type IntelligenceAccount = { id: string; label: string; transactionCount: number; identifiedInflows: number; identifiedOutflows: number; spendingShare: number; depositShare: number; transferCount: number; currentBalance: number | null; availableBalance: number | null; lastActivityDate: string | null };
export type IntelligenceMetrics = { generatedAt: string; period: { currentStart: string; currentEnd: string; priorStart: string; priorEnd: string }; transactionCount: number; pendingCount: number; removedCount: number; transferCount: number; internalTransferCount: number; identifiedInflows: number; identifiedOutflows: number; priorInflows: number; priorOutflows: number; largestExpense: number | null; uncategorizedOutflow: number; categorizedOutflow: number; completeMonths: Array<{ inflow: number; outflow: number }>; accounts: IntelligenceAccount[]; syncStatus: string; lastSyncAt: string | null };
type Dimensions = { impact: number; urgency: number; confidence: number; usefulness: number; relevance: number; novelty: number; actionability: number; completeness: number };
export type InsightCandidate = { ruleId: string; observationId: string; conditionSignature: string; title: string; observed: string; meaning: string; period: string; support: string; qualification: string; question: string; accountScope: string[]; aggregates: Record<string, number | string | null>; confidence: number; score: number; critical: boolean; generatedAt: string; expiresAt: string; reevaluateWhen: string; dimensions: Dimensions };
export type PriorObservation = { observationId: string; conditionSignature: string; shownAt: string; handled?: boolean };
export type IntelligenceResult = { candidateCount: number; rejected: Array<{ ruleId: string; reason: string }>; ranked: InsightCandidate[]; observations: InsightCandidate[]; criticalAlert: InsightCandidate | null; stableMessage: string | null; dataQualityStatus: { title: string; body: string; uncategorizedShare: number } | null };

const PRIMARY_CONFIDENCE = .65; const PRIMARY_SCORE = 55; const CRITICAL_SCORE = 85;
const clamp = (value: number) => Math.max(0, Math.min(1, value));
const dollars = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const periodLabel = (start: string, end: string) => { const from = new Date(`${start}T00:00:00Z`); const through = new Date(`${end}T00:00:00Z`); const first = new Intl.DateTimeFormat("en-US", { month: "long", day: "numeric", timeZone: "UTC" }).format(from); const last = new Intl.DateTimeFormat("en-US", { month: "long", day: "numeric", year: "numeric", timeZone: "UTC" }).format(through); return `${first} through ${last}`; };
export function buildCashFlowComparison(metrics: IntelligenceMetrics) { const currentNet = metrics.identifiedInflows - metrics.identifiedOutflows; const priorNet = metrics.priorInflows - metrics.priorOutflows; const change = currentNet - priorNet; const percentageChange = priorNet > 0 ? Math.abs(change) / priorNet * 100 : null; const direction = change < 0 ? "declined" : "improved"; return { currentNet, priorNet, change, absoluteChange: Math.abs(change), percentageChange, direction, currentPositive: currentNet >= 0, currentPeriod: periodLabel(metrics.period.currentStart, metrics.period.currentEnd), priorPeriod: periodLabel(metrics.period.priorStart, metrics.period.priorEnd) }; }
export function rankDimensions(value: Dimensions) { return Math.round(100 * (.25 * value.impact + .15 * value.urgency + .25 * value.confidence + .1 * value.usefulness + .05 * value.relevance + .1 * value.novelty + .05 * value.actionability + .05 * value.completeness)); }
const expiry = (generatedAt: string, days: number) => new Date(new Date(generatedAt).getTime() + days * 86400000).toISOString();
function candidate(metrics: IntelligenceMetrics, ruleId: string, signature: string, copy: Omit<InsightCandidate, "ruleId" | "observationId" | "conditionSignature" | "score" | "generatedAt" | "expiresAt" | "dimensions">, dimensions: Dimensions, days = 7): InsightCandidate { return { ...copy, ruleId, observationId: `${ruleId}:${copy.accountScope.slice().sort().join("+") || "combined"}:${metrics.period.currentEnd}`, conditionSignature: signature, score: rankDimensions(dimensions), generatedAt: metrics.generatedAt, expiresAt: expiry(metrics.generatedAt, days), dimensions }; }
function recentPrior(candidateValue: InsightCandidate, prior: PriorObservation[], now: Date) { const match = prior.find((item) => item.observationId === candidateValue.observationId && item.conditionSignature === candidateValue.conditionSignature && !item.handled); return match && now.getTime() - new Date(match.shownAt).getTime() < 7 * 86400000; }

export function generateInsightCandidates(metrics: IntelligenceMetrics): InsightCandidate[] {
  const candidates: InsightCandidate[] = []; const totalOutflow = metrics.identifiedOutflows; const completeness = metrics.transactionCount ? 1 - metrics.uncategorizedOutflow / Math.max(1, totalOutflow) : 0;
  const dominantOutflow = metrics.accounts.slice().sort((a, b) => b.spendingShare - a.spendingShare)[0]; if (dominantOutflow?.spendingShare >= .7 && dominantOutflow.transactionCount >= 10) candidates.push(candidate(metrics, "account.outflow_concentration", `share:${Math.round(dominantOutflow.spendingShare * 20)}`, { title: "Most spending activity runs through one account", observed: `Approximately ${Math.round(dominantOutflow.spendingShare * 100)}% of identified outflow over the last 30 days came from ${dominantOutflow.label}.`, meaning: "This appears to be your primary operating account. Understanding which income and predictable payments use it may help identify ways to simplify bill management and automate savings.", period: periodLabel(metrics.period.currentStart, metrics.period.currentEnd), support: `${dollars(dominantOutflow.identifiedOutflows)} in identified outflow across ${dominantOutflow.transactionCount} transactions.`, qualification: "High confidence based on connected account activity. The account role is inferred, not permanently assigned.", question: "What income and recurring payments use this account?", accountScope: [dominantOutflow.id], aggregates: { spendingShare: dominantOutflow.spendingShare, identifiedOutflows: dominantOutflow.identifiedOutflows, transactionCount: dominantOutflow.transactionCount }, confidence: .9, critical: false, reevaluateWhen: "Account spending share changes by at least 10 percentage points", }, { impact: .7, urgency: .3, confidence: .9, usefulness: .85, relevance: .85, novelty: 1, actionability: .7, completeness: clamp(completeness + .25) }));
  const comparison = buildCashFlowComparison(metrics); const currentNet = comparison.currentNet; if (comparison.absoluteChange >= 500 && Math.max(metrics.identifiedInflows, metrics.identifiedOutflows) > 0) { const cashFlowConfidence = completeness < .6 ? .6 : .88; const percentCopy = comparison.percentageChange === null ? "" : ` or ${comparison.percentageChange.toFixed(0)}%`; const signCopy = !comparison.currentPositive ? "Identified spending exceeded identified inflows during the current period." : comparison.direction === "declined" ? "Your cash flow remained positive, but the surplus was smaller than during the prior period." : "Your cash flow remained positive and the identified surplus increased."; candidates.push(candidate(metrics, "cashflow.material_change", `${comparison.direction}:${Math.round(comparison.absoluteChange / 250)}`, { title: `Your identified cash flow ${comparison.direction}`, observed: `Your identified net cash flow was approximately ${dollars(comparison.currentNet)} from ${comparison.currentPeriod}, compared with ${dollars(comparison.priorNet)} during ${comparison.priorPeriod}.`, meaning: `That is a change of approximately ${dollars(comparison.absoluteChange)}${percentCopy}. ${signCopy}`, period: `${comparison.currentPeriod}, compared with ${comparison.priorPeriod}`, support: `Current period: ${dollars(metrics.identifiedInflows)} identified inflows, ${dollars(metrics.identifiedOutflows)} identified outflows, ${dollars(comparison.currentNet)} net. Prior period: ${dollars(metrics.priorInflows)} identified inflows, ${dollars(metrics.priorOutflows)} identified outflows, ${dollars(comparison.priorNet)} net.`, qualification: completeness < .6 ? "Insufficient confidence for display because category coverage is incomplete." : "High confidence based on identified inflows and outflows.", question: "What drove the change in my cash flow?", accountScope: metrics.accounts.map((account) => account.id), aggregates: { currentInflows: metrics.identifiedInflows, currentOutflows: metrics.identifiedOutflows, currentNet: comparison.currentNet, priorInflows: metrics.priorInflows, priorOutflows: metrics.priorOutflows, priorNet: comparison.priorNet, absoluteChange: comparison.absoluteChange, percentageChange: comparison.percentageChange }, confidence: cashFlowConfidence, critical: false, reevaluateWhen: "Current or prior-period cash flow changes by at least 10%", }, { impact: .8, urgency: .55, confidence: cashFlowConfidence, usefulness: .9, relevance: .9, novelty: 1, actionability: .8, completeness: clamp(completeness + .2) })); }
  if (metrics.largestExpense && totalOutflow && metrics.largestExpense / totalOutflow >= .2 && metrics.largestExpense >= 250) candidates.push(candidate(metrics, "spending.large_expense", `share:${Math.round(metrics.largestExpense / totalOutflow * 20)}`, { title: "One expense materially affected recent outflow", observed: `The largest identified expense represented approximately ${Math.round(metrics.largestExpense / totalOutflow * 100)}% of estimated outflow in the current period.`, meaning: "A single large expense can make a period look different from the user’s usual pattern.", period: `${metrics.period.currentStart} through ${metrics.period.currentEnd}`, support: `${metrics.largestExpense.toFixed(2)} largest expense against ${totalOutflow.toFixed(2)} estimated outflow.`, qualification: "High confidence in the aggregate amount; transaction details are intentionally omitted from this observation.", question: "How did this expense affect the rest of the period?", accountScope: metrics.accounts.map((account) => account.id), aggregates: { largestExpense: metrics.largestExpense, totalOutflow }, confidence: .9, critical: false, reevaluateWhen: "The largest-expense share changes materially", }, { impact: .72, urgency: .5, confidence: .9, usefulness: .8, relevance: .8, novelty: 1, actionability: .65, completeness: .9 }));
  const staleDays = metrics.lastSyncAt ? (new Date(metrics.generatedAt).getTime() - new Date(metrics.lastSyncAt).getTime()) / 86400000 : Infinity; if (metrics.syncStatus !== "complete" || staleDays >= 3) candidates.push(candidate(metrics, "stability.sync_stale", `status:${metrics.syncStatus}:days:${Math.floor(staleDays)}`, { title: "Your connected data may need attention", observed: metrics.lastSyncAt ? `The last successful sync was ${Math.floor(staleDays)} days ago.` : "A successful sync time is not available.", meaning: "A stale connection can make the Money Picture incomplete until new activity arrives.", period: "Current connection state", support: `Sync status: ${metrics.syncStatus}.`, qualification: "High confidence from connection status.", question: "What can I check before refreshing my connection?", accountScope: metrics.accounts.map((account) => account.id), aggregates: { staleDays: Number.isFinite(staleDays) ? staleDays : null, syncStatus: metrics.syncStatus }, confidence: .98, critical: staleDays >= 7 || metrics.syncStatus === "error", reevaluateWhen: "A successful sync completes", }, { impact: staleDays >= 7 ? .9 : .65, urgency: staleDays >= 7 ? .92 : .65, confidence: .98, usefulness: .95, relevance: 1, novelty: 1, actionability: .9, completeness: 1 }, 2));
  const positiveMonths = metrics.completeMonths.filter((month) => month.inflow - month.outflow > 0); const averageSurplus = positiveMonths.length ? positiveMonths.reduce((sum, month) => sum + month.inflow - month.outflow, 0) / positiveMonths.length : 0; const currentNetPositive = currentNet > 0; const threeCompletePositiveMonths = metrics.completeMonths.length >= 3 && positiveMonths.length === metrics.completeMonths.length; if (threeCompletePositiveMonths && currentNetPositive && averageSurplus >= 250) candidates.push(candidate(metrics, "savings.surplus_observed", `months:${positiveMonths.length}:band:${Math.round(averageSurplus / 250)}`, { title: "Positive cash flow may create future savings capacity", observed: `${positiveMonths.length} complete recent months and the current comparison period show positive identified cash flow.`, meaning: "The pattern may support a future automatic-savings estimate, but income frequency and observed obligations must be confirmed first.", period: "Recent complete months and current comparison period", support: `Average identified surplus across positive complete months: ${averageSurplus.toFixed(2)}.`, qualification: "Observation only—not a recommended amount. More income-pattern evidence is required.", question: "What additional history is needed before estimating a sustainable savings amount?", accountScope: metrics.accounts.map((account) => account.id), aggregates: { positiveMonths: positiveMonths.length, averageSurplus, currentNet }, confidence: .72, critical: false, reevaluateWhen: "At least one additional complete month or a material cash-flow change", }, { impact: .7, urgency: .2, confidence: .72, usefulness: .85, relevance: .8, novelty: 1, actionability: .5, completeness: clamp(completeness + .1) }, 30));
  return candidates;
}

export function rankInsightCandidates(candidates: InsightCandidate[], prior: PriorObservation[], generatedAt: string) { const now = new Date(generatedAt); const rejected: IntelligenceResult["rejected"] = []; const eligible = candidates.filter((item) => { if (item.confidence < PRIMARY_CONFIDENCE) { rejected.push({ ruleId: item.ruleId, reason: "confidence_below_threshold" }); return false; } if (item.score < PRIMARY_SCORE) { rejected.push({ ruleId: item.ruleId, reason: "score_below_threshold" }); return false; } if (recentPrior(item, prior, now)) { rejected.push({ ruleId: item.ruleId, reason: "unchanged_recent_repeat" }); return false; } return true; }).sort((a, b) => b.score - a.score || b.confidence - a.confidence || a.ruleId.localeCompare(b.ruleId)); return { eligible, rejected }; }
export function runMoneyPictureIntelligence(metrics: IntelligenceMetrics, prior: PriorObservation[] = []): IntelligenceResult { const candidates = generateInsightCandidates(metrics); const { eligible, rejected } = rankInsightCandidates(candidates, prior, metrics.generatedAt); const criticalAlert = eligible.find((item) => item.critical && item.score >= CRITICAL_SCORE && item.confidence >= .85 && item.dimensions.urgency >= .9) || null; const observations = eligible.filter((item) => item !== criticalAlert).slice(0, 3); const uncategorizedShare = metrics.identifiedOutflows ? metrics.uncategorizedOutflow / metrics.identifiedOutflows : 0; const dataQualityStatus = uncategorizedShare >= .35 && metrics.uncategorizedOutflow >= 250 ? { title: "Covarify is still organizing your spending", body: "Some transactions do not yet have reliable spending categories, so category comparisons and recurring-payment estimates are limited for now.", uncategorizedShare } : null; return { candidateCount: candidates.length, rejected, ranked: eligible, observations, criticalAlert, stableMessage: observations.length || criticalAlert ? null : "Your financial picture is stable today. No meaningful changes were detected.", dataQualityStatus }; }

export const INTELLIGENCE_THRESHOLDS = { primaryConfidence: PRIMARY_CONFIDENCE, primaryScore: PRIMARY_SCORE, criticalScore: CRITICAL_SCORE } as const;
