create extension if not exists pgcrypto;

create table public.profiles (id uuid primary key references auth.users(id) on delete restrict, display_name text, account_status text not null default 'active' check (account_status in ('active','suspended','closed')), is_internal boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.consent_records (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete restrict, consent_version text not null, products_requested text[] not null, purposes text[] not null, accepted_at timestamptz not null, revoked_at timestamptz, created_at timestamptz not null default now());
create table public.plaid_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete restrict, plaid_item_id text not null, institution_id text, institution_name text, environment text not null check (environment in ('sandbox','production')), encrypted_access_token text, token_key_version text, status text not null, consent_id uuid not null references public.consent_records(id) on delete restrict, last_successful_sync_at timestamptz, last_webhook_at timestamptz, error_code text, needs_update_mode boolean not null default false, disconnected_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(plaid_item_id,environment));
create table public.plaid_accounts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete restrict, plaid_item_id uuid not null references public.plaid_items(id) on delete restrict, plaid_account_id text not null, persistent_account_id text, name text not null, official_name text, type text not null, subtype text, mask text, currency text, current_balance numeric, available_balance numeric, limit_balance numeric, active_status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(plaid_item_id,plaid_account_id));
create table public.transaction_sync_states (id uuid primary key default gen_random_uuid(), plaid_item_id uuid not null unique references public.plaid_items(id) on delete restrict, cursor text, sync_status text not null default 'idle', retry_count integer not null default 0, last_error text, last_sync_started_at timestamptz, last_sync_completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.plaid_transactions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete restrict, plaid_item_id uuid not null references public.plaid_items(id) on delete restrict, plaid_account_id uuid not null references public.plaid_accounts(id) on delete restrict, plaid_transaction_id text not null, pending_transaction_id text, amount numeric not null, currency text, merchant_name text, transaction_name text not null, category_data jsonb, transaction_date date not null, authorized_date date, pending boolean not null, removed_at timestamptz, provenance jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(plaid_item_id,plaid_transaction_id));
create table public.plaid_webhook_events (id uuid primary key default gen_random_uuid(), plaid_item_id uuid references public.plaid_items(id) on delete restrict, webhook_type text not null, webhook_code text not null, event_hash text not null unique, verification_status text not null, processing_status text not null, received_at timestamptz not null default now(), processed_at timestamptz, safe_error_metadata jsonb);
create table public.audit_events (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete restrict, event_type text not null, entity_type text not null, entity_id uuid, safe_metadata jsonb, created_at timestamptz not null default now());

create index plaid_items_user_idx on public.plaid_items(user_id); create index plaid_accounts_user_idx on public.plaid_accounts(user_id); create index plaid_transactions_user_date_idx on public.plaid_transactions(user_id,transaction_date desc); create index webhook_item_idx on public.plaid_webhook_events(plaid_item_id);

alter table public.profiles enable row level security; alter table public.consent_records enable row level security; alter table public.plaid_items enable row level security; alter table public.plaid_accounts enable row level security; alter table public.transaction_sync_states enable row level security; alter table public.plaid_transactions enable row level security; alter table public.plaid_webhook_events enable row level security; alter table public.audit_events enable row level security;
create policy profile_select on public.profiles for select to authenticated using ((select auth.uid())=id); create policy profile_update on public.profiles for update to authenticated using ((select auth.uid())=id) with check ((select auth.uid())=id);
create policy consent_select on public.consent_records for select to authenticated using ((select auth.uid())=user_id);
create policy item_select on public.plaid_items for select to authenticated using ((select auth.uid())=user_id);
create policy account_select on public.plaid_accounts for select to authenticated using ((select auth.uid())=user_id);
create policy sync_select on public.transaction_sync_states for select to authenticated using (exists(select 1 from public.plaid_items i where i.id=transaction_sync_states.plaid_item_id and i.user_id=(select auth.uid())));
create policy transaction_select on public.plaid_transactions for select to authenticated using ((select auth.uid())=user_id);
revoke all on public.plaid_webhook_events, public.audit_events from anon, authenticated;
revoke select(encrypted_access_token,token_key_version) on public.plaid_items from anon, authenticated;
grant select(id,user_id,plaid_item_id,institution_id,institution_name,environment,status,consent_id,last_successful_sync_at,last_webhook_at,error_code,needs_update_mode,disconnected_at,created_at,updated_at) on public.plaid_items to authenticated;

create function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id) values(new.id) on conflict do nothing; return new; end $$;
create trigger auth_user_profile after insert on auth.users for each row execute function public.handle_new_user();

-- Rollback is intentionally manual because these tables contain audit-relevant data.
-- See supabase/rollback/202607170001_auth_plaid_foundation.sql.
