export type NeedType = "current_housing" | "housing_arrears" | "utilities" | "food" | "medication" | "work_transportation" | "car_repair" | "insurance_premium" | "debt_minimum" | "installment_payment" | "childcare" | "taxes" | "legal_deadline" | "business_obligation" | "reimbursement_expense" | "user_urgent" | "custom";
export type EvidenceStatus = "known" | "estimated" | "missing";
export type ConsequenceBasis = "verified" | "user_reported" | "system_derived" | "generally_possible" | "uncertain_requires_verification";
export type Confidence = "high" | "medium" | "low";

export type FinancialNeed = {
  id: string; scopeId: string; title: string; type: NeedType; amountRequired: number | null; minimumUsefulPayment: number | null; fullAmount: number | null;
  dueDate: string | null; gracePeriod: string | null; partialPaymentUsefulness: "verified_useful" | "verified_not_useful" | "unknown_verify";
  consequenceOfDelay: string; consequenceConfidence: ConsequenceBasis; housingStability: "none" | "possible" | "direct"; incomeEmployment: "none" | "possible" | "direct";
  essentialServices: "none" | "possible" | "direct"; creditConsequence: "none_known" | "generally_possible" | "unknown"; feePenaltyRisk: "none_known" | "possible" | "verified";
  reversible: boolean; negotiable: "yes" | "no" | "unknown"; source: "fixture" | "user" | "connected" | "document"; evidenceIds: string[]; freshness: string;
  status: EvidenceStatus; scope: "personal" | "household" | "business";
};

export type IncomeEvent = { id: string; title: string; amount: number; date: string; kind: "deposited" | "scheduled_payroll" | "historically_predictable" | "confirmed_reimbursement" | "uncertain_commission" | "possible_side_income" | "user_estimate"; confidence: Confidence; available: boolean; evidenceIds: string[] };
export type Resource = { id: string; title: string; amount: number; kind: "cash" | "protected_reserve" | "restricted" | "business" | "household" | "expected_income" | "uncertain_income" | "credit" | "investment" | "reimbursement" | "refund" | "transfer"; availableDate: string; confidence: Confidence; evidenceIds: string[]; included: boolean; exclusionReason: string | null; deduplicationKey: string };
export type TimelineEvent = { id: string; date: string; kind: "opening_balance" | "pending" | "need" | "income"; title: string; amount: number; effect: "add" | "subtract" | "none"; projectedBalance: number; confidence: Confidence; evidenceIds: string[] };
export type ConsequenceAssessment = { needId: string; description: string; basis: ConsequenceBasis; confidence: Confidence; verificationStep: string | null };
export type AllocationLine = { needId: string; title: string; allocated: number; unfunded: number; reason: string; consequenceMitigated: string | null; consequenceDeferred: string | null; evidenceIds: string[]; confidence: Confidence; timing: string; tradeoff: string; confirmationRequired: true };
export type AllocationOption = { id: "stability_first" | "housing_first" | "income_protection" | "balanced" | "lowest_immediate_risk" | "user_customized"; title: string; allocations: AllocationLine[]; protectedReserve: number; expectedAfterNextIncome: number; consequencesAddressed: string[]; consequencesDeferred: string[]; assumptions: string[]; confidence: Confidence; evidenceIds: string[]; simulated: boolean };
export type GuidanceState = "enough_to_orient" | "enough_to_compare" | "preliminary_recommendation" | "final_strategy_preview" | "blocked_by_critical_evidence";
export type BlockingQuestion = { id: string; prompt: string; recognizedFacts: string[]; changes: string[] };
export type AllocationResult = { guidance: GuidanceState; availableBeforeNextIncome: number; nextIncome: IncomeEvent | null; timeline: TimelineEvent[]; consequences: ConsequenceAssessment[]; options: AllocationOption[]; recommendedId: AllocationOption["id"] | null; simpleExplanation: string; limitation: string | null; blockingQuestion: BlockingQuestion | null; nextBestStep: string; durableWriteBlocked: true };
export type AllocationScenario = { id: string; title: string; simulated: true; baselineId: string; changedAssumptions: string[]; result: AllocationResult; activated: false; memoryWriteBlocked: true };
export type AllocationResumeState = { lastConfirmedFact: string | null; activeQuestion: string | null; evidenceIds: string[]; preliminaryRecommendationId: string | null; unresolvedNeedId: string | null; optionIds: string[]; unconfirmedGoal: string | null; unconfirmedConstraint: string | null; scope: "session_only" };
export type GovernedMemoryDisposition = { type: string; disposition: "temporary" | "durable_after_confirmation" | "never_canonical"; confirmationRequired: boolean; requiredFields: string[] };
export type RealDataEvidenceContract = { sourceRecordIds: string[]; calculationPeriod: { start: string; end: string }; freshness: string; status: EvidenceStatus; inclusionReason: string | null; exclusionReason: string | null; deduplicationKey: string };

const money = (value: number) => `$${value.toFixed(0)}`;
const dateSort = <T extends { date: string }>(items: T[]) => [...items].sort((a, b) => a.date.localeCompare(b.date));

export function founderAllocationFixture() {
  const needs: FinancialNeed[] = [
    { id: "repair", scopeId: "founder-fixture", title: "Car repair", type: "car_repair", amountRequired: 500, minimumUsefulPayment: 500, fullAmount: 500, dueDate: "2026-08-06", gracePeriod: null, partialPaymentUsefulness: "verified_not_useful", consequenceOfDelay: "May prevent travel to work if the repair is required for work.", consequenceConfidence: "uncertain_requires_verification", housingStability: "none", incomeEmployment: "possible", essentialServices: "none", creditConsequence: "none_known", feePenaltyRisk: "none_known", reversible: false, negotiable: "no", source: "fixture", evidenceIds: ["repair-estimate"], freshness: "2026-08-04", status: "known", scope: "personal" },
    { id: "card-minimum", scopeId: "founder-fixture", title: "Card required minimum", type: "debt_minimum", amountRequired: 75, minimumUsefulPayment: 75, fullAmount: 2400, dueDate: "2026-08-08", gracePeriod: null, partialPaymentUsefulness: "verified_not_useful", consequenceOfDelay: "A missed required minimum may cause a late fee or other account consequences.", consequenceConfidence: "generally_possible", housingStability: "none", incomeEmployment: "none", essentialServices: "none", creditConsequence: "generally_possible", feePenaltyRisk: "possible", reversible: false, negotiable: "unknown", source: "fixture", evidenceIds: ["card-statement-minimum"], freshness: "2026-08-04", status: "known", scope: "personal" },
    { id: "utility", scopeId: "founder-fixture", title: "Utility payment", type: "utilities", amountRequired: 180, minimumUsefulPayment: null, fullAmount: 180, dueDate: null, gracePeriod: null, partialPaymentUsefulness: "unknown_verify", consequenceOfDelay: "Service interruption is generally possible, but the due date and partial-payment effect are unconfirmed.", consequenceConfidence: "uncertain_requires_verification", housingStability: "possible", incomeEmployment: "none", essentialServices: "direct", creditConsequence: "unknown", feePenaltyRisk: "possible", reversible: false, negotiable: "unknown", source: "fixture", evidenceIds: ["utility-bill"], freshness: "2026-08-04", status: "estimated", scope: "household" },
    { id: "current-rent", scopeId: "founder-fixture", title: "Upcoming current rent", type: "current_housing", amountRequired: 1700, minimumUsefulPayment: null, fullAmount: 1700, dueDate: "2026-09-01", gracePeriod: null, partialPaymentUsefulness: "unknown_verify", consequenceOfDelay: "The next rent payment could become late and increase housing instability.", consequenceConfidence: "generally_possible", housingStability: "direct", incomeEmployment: "none", essentialServices: "none", creditConsequence: "unknown", feePenaltyRisk: "possible", reversible: false, negotiable: "unknown", source: "fixture", evidenceIds: ["lease-current-rent"], freshness: "2026-08-04", status: "known", scope: "household" },
    { id: "rent-arrears", scopeId: "founder-fixture", title: "Rent arrears", type: "housing_arrears", amountRequired: 7800, minimumUsefulPayment: null, fullAmount: 7800, dueDate: null, gracePeriod: null, partialPaymentUsefulness: "unknown_verify", consequenceOfDelay: "The past-due balance remains and may increase, but the effect of a partial payment must be verified.", consequenceConfidence: "uncertain_requires_verification", housingStability: "possible", incomeEmployment: "none", essentialServices: "none", creditConsequence: "unknown", feePenaltyRisk: "possible", reversible: false, negotiable: "unknown", source: "fixture", evidenceIds: ["rent-ledger-arrears"], freshness: "2026-08-04", status: "known", scope: "household" },
    { id: "groceries-medication", scopeId: "founder-fixture", title: "Protected groceries and medication", type: "medication", amountRequired: 0, minimumUsefulPayment: 0, fullAmount: 0, dueDate: "2026-08-20", gracePeriod: null, partialPaymentUsefulness: "verified_useful", consequenceOfDelay: "Food and medication access must remain protected.", consequenceConfidence: "user_reported", housingStability: "none", incomeEmployment: "possible", essentialServices: "direct", creditConsequence: "none_known", feePenaltyRisk: "none_known", reversible: false, negotiable: "no", source: "fixture", evidenceIds: ["protected-essentials"], freshness: "2026-08-04", status: "known", scope: "household" },
  ];
  const resources: Resource[] = [
    { id: "cash", title: "Cash available before next income", amount: 900, kind: "cash", availableDate: "2026-08-04", confidence: "high", evidenceIds: ["cash-balance"], included: true, exclusionReason: null, deduplicationKey: "cash:checking:2026-08-04" },
    { id: "commission", title: "Possible commission", amount: 300, kind: "uncertain_income", availableDate: "2026-08-20", confidence: "low", evidenceIds: ["commission-estimate"], included: false, exclusionReason: "Timing and receipt are uncertain.", deduplicationKey: "income:commission:2026-08" },
    { id: "credit", title: "Available credit", amount: 3100, kind: "credit", availableDate: "2026-08-04", confidence: "high", evidenceIds: ["credit-available"], included: false, exclusionReason: "Available credit is not cash.", deduplicationKey: "credit:card:4242" },
    { id: "investments", title: "Investments", amount: 9000, kind: "investment", availableDate: "2026-08-04", confidence: "high", evidenceIds: ["investment-balance"], included: false, exclusionReason: "Investments are not spendable cash in this preview.", deduplicationKey: "investment:brokerage" },
  ];
  const income: IncomeEvent[] = [{ id: "paycheck", title: "Scheduled paycheck", amount: 1800, date: "2026-08-20", kind: "scheduled_payroll", confidence: "high", available: false, evidenceIds: ["payroll-schedule"] }, { id: "commission-income", title: "Possible commission", amount: 300, date: "2026-08-20", kind: "uncertain_commission", confidence: "low", available: false, evidenceIds: ["commission-estimate"] }];
  return { asOf: "2026-08-04", analysisEnd: "2026-09-01", needs, resources, income };
}

export function evaluateConsequences(needs: FinancialNeed[], repairRequiredForWork: boolean | null): ConsequenceAssessment[] {
  return needs.map((need) => need.id === "repair" && repairRequiredForWork === true ? { needId: need.id, description: "Without the repair, the user reported they cannot reliably get to work.", basis: "user_reported", confidence: "high", verificationStep: null } : { needId: need.id, description: need.consequenceOfDelay, basis: need.consequenceConfidence, confidence: need.consequenceConfidence === "verified" || need.consequenceConfidence === "user_reported" ? "high" : need.consequenceConfidence === "system_derived" ? "medium" : "low", verificationStep: need.consequenceConfidence === "uncertain_requires_verification" ? (need.type === "utilities" ? "Review the official utility bill or contact the provider to confirm the due date and useful minimum." : need.type === "housing_arrears" ? "Confirm with the landlord whether a partial payment preserves any arrangement." : "Verify the consequence before relying on it.") : null });
}

export function buildCashFlowTimeline(input: ReturnType<typeof founderAllocationFixture>): TimelineEvent[] {
  const opening = input.resources.filter((item) => item.kind === "cash" && item.included).reduce((sum, item) => sum + item.amount, 0); let balance = opening;
  const events: TimelineEvent[] = [{ id: "opening", date: input.asOf, kind: "opening_balance", title: "Available cash", amount: opening, effect: "add", projectedBalance: opening, confidence: "high", evidenceIds: ["cash-balance"] }];
  const datedNeeds = input.needs.filter((need): need is FinancialNeed & { dueDate: string } => Boolean(need.dueDate && need.dueDate <= input.analysisEnd)).map((need) => ({ id: `need:${need.id}`, date: need.dueDate, kind: "need" as const, title: `${need.title} due`, amount: need.amountRequired || 0, effect: "none" as const, confidence: need.status === "known" ? "high" as const : "low" as const, evidenceIds: need.evidenceIds }));
  const reliableIncome = input.income.filter((event) => event.confidence === "high" && event.date <= input.analysisEnd).map((item) => ({ id: item.id, date: item.date, kind: "income" as const, title: item.title, amount: item.amount, effect: "add" as const, confidence: item.confidence, evidenceIds: item.evidenceIds }));
  for (const item of dateSort([...datedNeeds, ...reliableIncome])) { if (item.effect === "add") balance += item.amount; events.push({ ...item, projectedBalance: balance }); }
  return events;
}

function line(need: FinancialNeed, amount: number, reason: string, deferred: string | null): AllocationLine { return { needId: need.id, title: need.title, allocated: amount, unfunded: Math.max(0, (need.amountRequired || 0) - amount), reason, consequenceMitigated: amount > 0 ? need.consequenceOfDelay : null, consequenceDeferred: deferred, evidenceIds: need.evidenceIds, confidence: need.status === "known" ? "high" : "low", timing: need.dueDate ? `By ${need.dueDate}` : "Timing needs verification", tradeoff: deferred || "Uses cash that cannot be allocated to another need.", confirmationRequired: true }; }

export function allocateNextDollar(input: { fixture?: ReturnType<typeof founderAllocationFixture>; repairRequiredForWork: boolean | null; protectUtility?: boolean; extraShiftIncome?: number; commissionGuaranteed?: boolean }): AllocationResult {
  const fixture = input.fixture || founderAllocationFixture(); const consequences = evaluateConsequences(fixture.needs, input.repairRequiredForWork); const need = (id: string) => fixture.needs.find((item) => item.id === id)!;
  const cash = fixture.resources.filter((item) => item.included && item.kind === "cash").reduce((sum, item) => sum + item.amount, 0);
  if (input.repairRequiredForWork == null) return { guidance: "enough_to_orient", availableBeforeNextIncome: cash, nextIncome: fixture.income.find((item) => item.kind === "scheduled_payroll") || null, timeline: buildCashFlowTimeline(fixture), consequences, options: [], recommendedId: null, simpleExplanation: "I found the repair, card minimum, utility payment, upcoming rent, and rent arrears. One answer could materially change their order.", limitation: "The repair's effect on income is not confirmed.", blockingQuestion: { id: "repair-for-work", prompt: "Is the $500 repair required for you to keep working?", recognizedFacts: ["$75 card minimum", "$180 utility payment", "upcoming current rent", "$7,800 rent arrears"], changes: ["whether income protection should outrank arrears"] }, nextBestStep: "Confirm whether the repair is required for work.", durableWriteBlocked: true };
  let remaining = cash; const allocations: AllocationLine[] = [];
  if (input.repairRequiredForWork) { allocations.push(line(need("repair"), 500, "Protects the ability to work and the income needed for later obligations.", null)); remaining -= 500; }
  allocations.push(line(need("card-minimum"), 75, "Satisfies the known required minimum; less than $75 is not modeled as useful.", null)); remaining -= 75;
  if (input.protectUtility && remaining >= 180) { allocations.push(line(need("utility"), 180, "Protects the full known utility amount while its exact due date is verified.", null)); remaining -= 180; }
  allocations.push(line(need("current-rent"), remaining, "Reserves the remaining cash for the upcoming current payment instead of increasing arrears risk.", "The full upcoming rent is not yet funded.")); remaining = 0;
  allocations.push(line(need("rent-arrears"), 0, "Do not use the same money for arrears while current rent and immediate needs remain unfunded.", "The arrears balance remains; verify any arrangement before making a partial payment."));
  if (!input.protectUtility) allocations.push(line(need("utility"), 0, "Its due date and useful partial-payment amount are not confirmed.", "Utility timing and consequence remain to be verified."));
  const option: AllocationOption = { id: input.protectUtility ? "lowest_immediate_risk" : "income_protection", title: input.protectUtility ? "Income protection and stability" : "Protect work and required minimums", allocations, protectedReserve: 0, expectedAfterNextIncome: 1800 + (input.extraShiftIncome || 0) + (input.commissionGuaranteed ? 300 : 0), consequencesAddressed: allocations.filter((item) => item.allocated > 0).map((item) => item.consequenceMitigated!).filter(Boolean), consequencesDeferred: allocations.map((item) => item.consequenceDeferred).filter((item): item is string => Boolean(item)), assumptions: ["The scheduled paycheck arrives on August 20.", "The possible commission is excluded unless explicitly confirmed.", ...(input.extraShiftIncome ? [`Two extra shifts add ${money(input.extraShiftIncome)} in this simulation.`] : [])], confidence: input.protectUtility ? "medium" : "medium", evidenceIds: [...new Set(allocations.flatMap((item) => item.evidenceIds))], simulated: Boolean(input.extraShiftIncome) };
  return { guidance: "preliminary_recommendation", availableBeforeNextIncome: cash, nextIncome: fixture.income.find((item) => item.kind === "scheduled_payroll") || null, timeline: buildCashFlowTimeline(fixture), consequences, options: [option], recommendedId: option.id, simpleExplanation: input.protectUtility ? "I prioritized the repair because it protects your ability to work, covered the required card minimum and utility payment, then reserved the remaining $145 for upcoming rent." : "I prioritized the repair because it protects your ability to work, covered the required card minimum, and reserved the remaining cash for upcoming rent.", limitation: "This is preliminary because the utility due date and the effect of partial rent payments are not confirmed.", blockingQuestion: null, nextBestStep: input.protectUtility ? "Review the utility bill to confirm its due date; do not move money from this preview." : "Choose whether to protect the utility payment too.", durableWriteBlocked: true };
}

export function simulateAllocation(baseline: AllocationResult, extraShiftIncome: number): AllocationScenario { return { id: "extra-shifts", title: "What if I work two extra shifts?", simulated: true, baselineId: baseline.recommendedId || "baseline", changedAssumptions: [`Expected income increases by ${money(extraShiftIncome)} after the next paycheck.`], result: allocateNextDollar({ repairRequiredForWork: true, protectUtility: baseline.options[0]?.allocations.some((item) => item.needId === "utility" && item.allocated > 0), extraShiftIncome }), activated: false, memoryWriteBlocked: true }; }
export function correctIncomeReliability(baseline: AllocationResult, statement: string) { const disputed = /commission.+not guaranteed/i.test(statement); return { disputedAssumption: "Possible $300 commission", acceptedCorrection: disputed ? "Commission remains excluded from available resources." : null, baselinePreserved: true, result: baseline, durableWriteBlocked: true as const }; }
export function detectPlanConflict(plans: Array<{ id: string; monthlyResourceIds: string[]; amount: number }>) { for (let index = 0; index < plans.length; index++) for (let other = index + 1; other < plans.length; other++) { const overlap = plans[index].monthlyResourceIds.filter((id) => plans[other].monthlyResourceIds.includes(id)); if (overlap.length) return { conflict: true, planIds: [plans[index].id, plans[other].id], resourceIds: overlap, message: `These plans rely on the same ${money(Math.min(plans[index].amount, plans[other].amount))} monthly resource and cannot both remain on schedule.` }; } return { conflict: false, planIds: [], resourceIds: [], message: "No shared-money conflict detected." }; }
export function crisisNextStep(kind: "housing_loss" | "utility_shutoff" | "insurance_lapse" | "food_medication" | "fraud" | "legal_deadline") { const actions = { housing_loss: "Contact the landlord or appropriate housing support now to verify the immediate deadline and available arrangement.", utility_shutoff: "Contact the utility provider now to verify the shutoff date and minimum needed to preserve service.", insurance_lapse: "Contact the insurer now to verify the lapse deadline and required payment.", food_medication: "Address immediate food or medication access first and seek appropriate local or professional support.", fraud: "Contact the financial institution using its official channel to review and secure the account.", legal_deadline: "Review the official notice and seek appropriate qualified professional help now." }; return { mode: "immediate_stabilization", oneAction: actions[kind], legalConclusion: false, outcomeGuaranteed: false, longRangeOptimizationHidden: true }; }
export function waitOrNoAction(input: { pendingDeposit?: boolean; staleAccount?: boolean; missingDocument?: boolean; noNeed?: boolean }) { if (input.staleAccount) return { type: "refresh", label: "Refresh the stale account before moving money." }; if (input.pendingDeposit) return { type: "wait", label: "Wait for the pending deposit; do not move money yet." }; if (input.missingDocument) return { type: "verify", label: "Review the missing bill or notice before allocating." }; return { type: "no_action", label: input.noNeed ? "No action is needed." : "No evidence-backed action is available yet." }; }
export function governedMemoryMapping(): GovernedMemoryDisposition[] { const durableFields = ["type", "scope", "subject", "source", "evidence", "confirmation", "effectiveDate", "confidence", "freshness", "status", "correction", "revocation", "expiration", "supersession"]; return [{ type: "evidence bundle, unconfirmed need/consequence/goal/priority/constraint, viewed allocation, simulation, dispute, resume state", disposition: "temporary", confirmationRequired: false, requiredFields: [] }, { type: "confirmed need, consequence fact, goal, priority, protected expense, allocation, strategy, plan, or income reliability", disposition: "durable_after_confirmation", confirmationRequired: true, requiredFields: durableFields }, { type: "raw audio/transcript, abandoned scenario, unsupported inference, low-confidence consequence, unaccepted allocation", disposition: "never_canonical", confirmationRequired: false, requiredFields: [] }]; }
export function realDataReadinessContract(): { inputs: string[]; evidence: RealDataEvidenceContract } { return { inputs: ["Canonical Financial Snapshot", "posted and pending transactions", "balances and freshness", "obligations and recurring commitments", "income events", "user facts", "business and household boundaries", "active plans", "protected reserves", "documents and notices", "Financial Memory", "missing institutions"], evidence: { sourceRecordIds: [], calculationPeriod: { start: "", end: "" }, freshness: "", status: "missing", inclusionReason: null, exclusionReason: null, deduplicationKey: "" } }; }
