import type { AmbiguityCandidate, FactValue, FinancialEntity, FinancialFieldId, StateChange } from "./turn-contract.ts";
export type CorrectionResolution = { kind: "resolved"; entity: FinancialEntity; field: FinancialFieldId; value: string | number | boolean; phrase: string; confidence: "high" | "medium" } | { kind: "ambiguous"; message: string; candidates: AmbiguityCandidate[] } | { kind: "unresolved"; message: string };
const numericFields: FinancialFieldId[] = ["amount", "minimum", "estimate", "gross", "materials"];
const fieldHints: Array<[RegExp, FinancialFieldId]> = [[/minimum/i, "minimum"], [/materials?/i, "materials"], [/invoice/i, "gross"], [/(?:repair|car)/i, "estimate"], [/(?:deposit)/i, "amount"]];
const numberFrom = (text: string) => { const matched = text.match(/\$?([\d,]+(?:\.\d{1,2})?)/)?.[1]; return matched ? Number(matched.replaceAll(",", "")) : null; };
const factsFor = (facts: FactValue[], entityId: string) => facts.filter((item) => item.entityId === entityId);

export function resolveCorrection(input: { statement: string; entities: FinancialEntity[]; facts: FactValue[]; recentEntityIds: string[]; guided?: { entityId: string; field: FinancialFieldId; value: string | number | boolean } }): CorrectionResolution {
  if (input.guided) { const entity = input.entities.find((item) => item.id === input.guided!.entityId); return entity ? { kind: "resolved", entity, field: input.guided.field, value: input.guided.value, phrase: entity.label, confidence: "high" } : { kind: "unresolved", message: "That financial item is not available in the current context." }; }
  const statement = input.statement.trim();
  if (/visa.*not.*mastercard|meant the visa/i.test(statement)) { const payment = input.entities.find((item) => item.type === "TRANSACTION" && factsFor(input.facts, item.id).some((fact) => fact.field === "account_reference")); return payment ? { kind: "resolved", entity: payment, field: "account_reference", value: "visa", phrase: "the Visa", confidence: "high" } : { kind: "unresolved", message: "I couldn’t identify the payment account to correct." }; }
  const amount = numberFrom(statement); const explicitEntities = input.entities.filter((entity) => [entity.label, ...entity.aliases].some((alias) => new RegExp(`\\b${alias.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "i").test(statement)));
  const contextual = /\b(?:that|that amount|it)\b/i.test(statement) ? (input.recentEntityIds.length ? input.entities.filter((item) => input.recentEntityIds.includes(item.id)) : input.entities.filter((item) => factsFor(input.facts, item.id).some((fact) => numericFields.includes(fact.field)))) : [];
  const candidates = explicitEntities.length ? explicitEntities : contextual;
  if (!amount && /(?:amount.*wrong|change that amount)/i.test(statement)) return candidates.length ? { kind: "ambiguous", message: candidates.length === 1 ? `What is the correct amount for ${candidates[0].label}?` : "Which amount do you want to change?", candidates: candidates.flatMap((candidate) => numericFields.filter((field) => factsFor(input.facts, candidate.id).some((fact) => fact.field === field)).map((field) => ({ entityId: candidate.id, fieldId: field, displayLabel: `${candidate.label} ${field.replaceAll("_", " ")}`, confidence: "medium" as const, reason: "The replacement value or target needs clarification.", clarificationRequired: true as const }))) } : { kind: "unresolved", message: "Tell me which amount is wrong and the corrected value." };
  if (amount == null) return { kind: "unresolved", message: "I couldn’t identify a corrected financial value." };
  if (candidates.length !== 1) return candidates.length > 1 ? { kind: "ambiguous", message: `Which amount should change?`, candidates: candidates.map((entity) => ({ entityId: entity.id, fieldId: null, displayLabel: entity.label, confidence: "medium", reason: "More than one active financial entity matches the reference.", clarificationRequired: true })) } : { kind: "unresolved", message: "I couldn’t connect that amount to a financial item in the current context." };
  const entity = candidates[0]; const hinted = fieldHints.find(([pattern]) => pattern.test(statement))?.[1]; const available = factsFor(input.facts, entity.id).filter((fact) => numericFields.includes(fact.field));
  const field = hinted && available.some((fact) => fact.field === hinted) ? hinted : available.length === 1 ? available[0].field : null;
  if (!field) return { kind: "ambiguous", message: `Which ${entity.label} amount do you mean?`, candidates: available.map((item) => ({ entityId: entity.id, fieldId: item.field, displayLabel: `${entity.label} ${item.field.replaceAll("_", " ")}`, confidence: "medium", reason: "The entity has multiple editable amounts.", clarificationRequired: true })) };
  return { kind: "resolved", entity, field, value: amount, phrase: explicitEntities.length ? entity.label : "that amount", confidence: explicitEntities.length ? "high" : "medium" };
}
export function proposeCorrection(input: { resolution: Extract<CorrectionResolution, { kind: "resolved" }>; facts: FactValue[]; sequence: number }): StateChange | null { const current = input.facts.find((item) => item.entityId === input.resolution.entity.id && item.field === input.resolution.field); if (!current || current.value === input.resolution.value || typeof input.resolution.value === "number" && (!Number.isFinite(input.resolution.value) || input.resolution.value < 0)) return null; return { changeId: `${input.resolution.entity.id}.${input.resolution.field}:${input.sequence}`, entityId: input.resolution.entity.id, field: input.resolution.field, before: current.value, after: input.resolution.value, status: "proposed", reversible: true, affectedEntityIds: [input.resolution.entity.id] }; }
export function applyStateChange(facts: FactValue[], change: StateChange) { return facts.map((item) => item.entityId === change.entityId && item.field === change.field ? { ...item, value: change.after, status: "confirmed" as const } : { ...item }); }
