import { capabilityForIntent } from "./capability-registry.ts";
import { applyStateChange, proposeCorrection, resolveCorrection } from "./correction-engine.ts";
import { deriveDecision } from "./domain-adapters.ts";
import { presentTurn } from "./response-presenter.ts";
import { selectSemanticNextStep } from "./semantic-next-step.ts";
import { assertTurnInvariants, confirmationFor, type AmbiguityCandidate, type CapabilityId, type CovarifyTurn, type FactValue, type FinancialEntity, type FinancialFieldId, type InputModality, type IntentId, type PresentationDepth, type SemanticAction, type SemanticActionPayload, type StateChange } from "./turn-contract.ts";

export type CovarifySession = { sessionId: string; sequence: number; entities: FinancialEntity[]; facts: FactValue[]; presentationDepth: PresentationDepth; recentEntityIds: string[]; pendingChange: StateChange | null; undoChange: StateChange | null; stopped: boolean };
export type TurnInput = { modality: InputModality; statement?: string; action?: { id: string; payload: SemanticActionPayload | { kind: "propose_correction"; entityId: string; field: FinancialFieldId; value: string | number | boolean } }; now?: string };
export function createCovarifySession(input: { sessionId: string; entities: FinancialEntity[]; facts: FactValue[] }): CovarifySession { return { sessionId: input.sessionId, sequence: 0, entities: input.entities.map((item) => ({ ...item, aliases: [...item.aliases], facts: [] })), facts: input.facts.map((item) => ({ ...item, evidenceIds: [...item.evidenceIds] })), presentationDepth: "GUIDED", recentEntityIds: [], pendingChange: null, undoChange: null, stopped: false }; }

const makeAction = (id: string, type: SemanticAction["type"], label: string, consequence: SemanticAction["consequence"], payload: SemanticActionPayload, reversible = false): SemanticAction => ({ id, type, label, consequence, confirmation: confirmationFor(consequence), reversible, payload });
const normalized = (input: TurnInput) => (input.statement || "").trim().replace(/\s+/g, " ");
const depthFrom = (text: string): PresentationDepth | null => /(?:just tell me|go faster|keep it simple)/i.test(text) ? "CONCISE" : /(?:show me everything|show me the math)/i.test(text) ? "DETAILED" : /walk me through it/i.test(text) ? "GUIDED" : null;
const isFinancial = (text: string) => /\b(?:money|cash|card|visa|mastercard|repair|car|utility|rent|invoice|materials|deposit|goal|spend|payment|transaction|account|balance|debt|income|financial|amount|that|it)\b|\$\d/i.test(text);
function cloneFacts(facts: FactValue[]) { return facts.map((item) => ({ ...item, evidenceIds: [...item.evidenceIds] })); }
function intentFor(text: string, actionId: string | null, state: CovarifySession): IntentId {
  if (actionId === "correction.apply") return "CORRECT_FACT"; if (actionId === "correction.cancel") return "CORRECT_FACT"; if (actionId === "correction.undo") return "UNDO"; if (actionId === "session.stop") return "STOP"; if (actionId === "session.resume") return "RESUME"; if (actionId === "presentation.change") return "CHANGE_DEPTH";
  if (/stop here|done for now/i.test(text)) return "STOP"; if (/^resume$/i.test(text)) return "RESUME"; if (depthFrom(text)) return "CHANGE_DEPTH"; if (/show.*evidence/i.test(text)) return "SHOW_EVIDENCE"; if (/show.*(?:math|calculation)/i.test(text)) return "SHOW_CALCULATION"; if (/compare.*option/i.test(text)) return "COMPARE_OPTIONS";
  if (/what changed|since last week/i.test(text)) return "COMPARE_SNAPSHOTS";
  if (actionId === "fact.correct.propose" || /(?:actually|wrong|only|make that|change that amount|not mastercard|meant the visa)|\b(?:repair|minimum|utility|invoice|materials|deposit)\s+(?:is|are|to)\s+\$?\d/i.test(text)) return /not mastercard|meant the visa/i.test(text) ? "CORRECT_REFERENCE" : "CORRECT_FACT";
  if (/invoice|receivable|materials/i.test(text)) return "ASSESS_EXPECTED_RESOURCE"; if (/pay down.*but|camp deposit.*due/i.test(text)) return "PRIORITIZE"; if (/target.*(?:back-to-school|for callie)/i.test(text)) return "PROPOSE_MEMORY";
  if (!isFinancial(text)) return "OUT_OF_SCOPE"; return state.facts.length ? "READ_STATE" : "UNRESOLVED";
}

export function runCovarifyTurn(state: CovarifySession, input: TurnInput): CovarifyTurn {
  const before = cloneFacts(state.facts); state.sequence += 1; const statement = normalized(input); const guidedId = input.action?.id || null; let intent = intentFor(statement, guidedId, state); let capability: CapabilityId = capabilityForIntent(intent).id; let ambiguity: { message: string; candidates: AmbiguityCandidate[] } | null = null; let proposal: StateChange | null = null; let accepted: StateChange[] = []; let sessionMessage: string | null = null; let event: CovarifyTurn["telemetry"]["event"] = "turn_understood"; let actions: SemanticAction[] = []; let memory: CovarifyTurn["memory"] = { disposition: "session_only", proposal: null }; let resolved: CovarifyTurn["understanding"]["resolvedReferences"] = [];
  const actionPayload = input.action?.payload;
  if (intent === "CHANGE_DEPTH") { const requested = actionPayload?.kind === "change_presentation_depth" ? actionPayload.depth : depthFrom(statement); if (requested) state.presentationDepth = requested; sessionMessage = `Presentation changed to ${state.presentationDepth.toLowerCase()}.`; actions = [makeAction("presentation.change", "CHANGE_PRESENTATION_DEPTH", "Change explanation depth", "SESSION_REVERSIBLE", { kind: "change_presentation_depth", depth: state.presentationDepth }, true)]; }
  else if (intent === "STOP") { state.stopped = true; sessionMessage = "Stopped for now. Your session context is preserved for this session."; event = "stopped_for_now"; actions = [makeAction("session.resume", "RESUME", "Resume", "SESSION_REVERSIBLE", { kind: "resume" }, true)]; }
  else if (intent === "RESUME") { state.stopped = false; sessionMessage = "Resumed where you stopped."; event = "resumed"; actions = [makeAction("session.stop", "STOP_FOR_NOW", "Stop for now", "SESSION_REVERSIBLE", { kind: "stop" }, true)]; }
  else if (intent === "UNDO") { if (state.undoChange) { const undo = { ...state.undoChange, status: "accepted_session" as const }; state.facts = applyStateChange(state.facts, undo); accepted = [undo]; state.recentEntityIds = [undo.entityId]; state.undoChange = null; sessionMessage = `Undid the ${undo.entityId} ${undo.field.replaceAll("_", " ")} change.`; event = "undo_used"; } else sessionMessage = "There is no reversible session change to undo."; }
  else if (guidedId === "correction.cancel") { const cancelled = state.pendingChange; state.pendingChange = null; sessionMessage = cancelled ? `Cancelled the proposed ${cancelled.entityId} ${cancelled.field.replaceAll("_", " ")} change. Nothing changed.` : "There is no active correction to cancel."; event = "correction_cancelled"; }
  else if (guidedId === "correction.apply") { const pending = state.pendingChange; if (pending && actionPayload?.kind === "apply_correction" && actionPayload.changeId === pending.changeId) { const applied = { ...pending, status: "accepted_session" as const }; state.facts = applyStateChange(state.facts, applied); state.undoChange = { ...applied, changeId: `undo:${applied.changeId}`, before: applied.after, after: applied.before, status: "proposed" }; state.pendingChange = null; state.recentEntityIds = [applied.entityId]; accepted = [applied]; sessionMessage = `Applied the ${applied.entityId} ${applied.field.replaceAll("_", " ")} correction.`; event = "correction_applied"; actions = [makeAction("correction.undo", "UNDO", `Undo ${applied.entityId} ${applied.field.replaceAll("_", " ")} change`, "SESSION_REVERSIBLE", { kind: "undo", reversibleActionId: applied.changeId }, true)]; } else sessionMessage = "That correction is no longer active. Nothing changed."; }
  else if (intent === "CORRECT_FACT" || intent === "CORRECT_REFERENCE") {
    const guided = actionPayload?.kind === "propose_correction" ? { entityId: actionPayload.entityId, field: actionPayload.field, value: actionPayload.value } : undefined; const resolution = resolveCorrection({ statement, entities: state.entities, facts: state.facts, recentEntityIds: state.recentEntityIds, guided });
    if (resolution.kind === "resolved") { proposal = proposeCorrection({ resolution, facts: state.facts, sequence: state.sequence }); if (proposal) { state.pendingChange = proposal; state.recentEntityIds = [proposal.entityId]; resolved = [{ phrase: resolution.phrase, entityId: proposal.entityId, fieldId: proposal.field, confidence: resolution.confidence }]; event = "correction_proposed"; actions = [makeAction("correction.apply", "APPLY_CORRECTION", `Apply ${proposal.entityId} ${proposal.field.replaceAll("_", " ")} correction`, "SESSION_REVERSIBLE", { kind: "apply_correction", changeId: proposal.changeId }, true), makeAction("correction.cancel", "CANCEL_CORRECTION", "Cancel correction", "READ_ONLY", { kind: "cancel_correction", changeId: proposal.changeId })]; } else sessionMessage = "That value is already recorded, or the proposed value is invalid. Nothing changed."; }
    else if (resolution.kind === "ambiguous") { ambiguity = { message: resolution.message, candidates: resolution.candidates }; event = "clarification_requested"; actions = resolution.candidates.map((candidate, index) => makeAction(`clarification.${index + 1}`, "ANSWER_QUESTION", candidate.displayLabel, "READ_ONLY", { kind: "answer_question", questionId: "correction-target", answerId: `${candidate.entityId}:${candidate.fieldId || "entity"}` })); }
    else { intent = "UNRESOLVED"; capability = "OUT_OF_SCOPE"; sessionMessage = resolution.message; }
  }
  else if (intent === "PROPOSE_MEMORY") { const transaction = state.entities.find((entity) => entity.type === "TRANSACTION"); if (transaction) { const proposedFact: FactValue = { entityId: transaction.id, entityType: "TRANSACTION", field: "meaning", value: "back-to-school for Callie", status: "unconfirmed", evidenceIds: state.facts.filter((fact) => fact.entityId === transaction.id).flatMap((fact) => fact.evidenceIds) }; const proposalId = `memory:${state.sequence}`; memory = { disposition: "memory_proposal", proposal: { proposalId, fact: proposedFact, sourceTurnId: `turn:${state.sessionId}:${state.sequence}` } }; sessionMessage = `I matched ${transaction.label} and prepared a separate memory proposal for review.`; actions = [makeAction("memory.propose", "PROPOSE_MEMORY", "Review memory proposal", "READ_ONLY", { kind: "propose_memory", proposalId })]; } }
  else if (intent === "SHOW_EVIDENCE") actions = [makeAction("evidence.show", "SHOW_EVIDENCE", "Show evidence", "READ_ONLY", { kind: "show_evidence", evidenceGroupId: "active-decision" })];
  else if (intent === "SHOW_CALCULATION") actions = [makeAction("calculation.show", "SHOW_CALCULATION", "Show calculation", "READ_ONLY", { kind: "show_calculation", calculationId: "active-decision" })];
  else if (intent === "COMPARE_OPTIONS") actions = [makeAction("options.compare", "COMPARE_OPTIONS", "Compare options", "READ_ONLY", { kind: "compare_options", decisionId: `decision:${state.sequence}` })];
  else if (intent === "OUT_OF_SCOPE") sessionMessage = "I’m focused on helping with your financial picture and decisions.";
  const prospectiveFacts = proposal ? applyStateChange(state.facts, proposal) : state.facts; const decision = deriveDecision(prospectiveFacts, capability, state.sequence); const turnId = `turn:${state.sessionId}:${state.sequence}`; const response = presentTurn({ turnId, decision, depth: state.presentationDepth, proposal, ambiguity, outOfScope: intent === "OUT_OF_SCOPE", sessionMessage });
  if (!actions.length && decision.recommendation && !proposal) actions = [makeAction("session.stop", "STOP_FOR_NOW", "Stop for now", "SESSION_REVERSIBLE", { kind: "stop" }, true)];
  const next = selectSemanticNextStep({ proposal: Boolean(proposal), criticalQuestion: ambiguity?.message || null, waiting: false, decisionReview: !state.stopped && Boolean(decision.recommendation) && !sessionMessage, optionalAction: state.stopped ? null : actions[0] || null, stopped: state.stopped });
  const after = cloneFacts(state.facts); const evidence = before.flatMap((fact) => fact.evidenceIds.map((id) => ({ id, provenance: "fixture" as const, freshness: "current" as const, confidence: "high" as const })));
  return assertTurnInvariants({ contractVersion: 1, identity: { turnId, sessionId: state.sessionId, sequence: state.sequence, timestamp: input.now || new Date(0).toISOString(), modality: input.modality }, input: { rawStatement: input.modality === "guided_action" ? null : input.statement || "", normalizedStatement: input.modality === "guided_action" ? null : statement, guidedActionId: guidedId }, understanding: { intent, capability, scope: intent === "CHANGE_DEPTH" ? "PRESENTATION" : ["STOP", "RESUME", "UNDO"].includes(intent) ? "SESSION" : intent === "OUT_OF_SCOPE" ? "OUT_OF_SCOPE" : intent === "PROPOSE_MEMORY" || intent === "CORRECT_REFERENCE" ? "TRANSACTION" : capability === "ASSESS_EXPECTED_RESOURCE" ? "RESOURCE" : capability === "PRIORITIZE_COMPETING_NEEDS" ? "GOAL" : "FINANCIAL_STATE", referencedEntityIds: resolved.map((item) => item.entityId), resolvedReferences: resolved, confidence: ambiguity ? "low" : intent === "OUT_OF_SCOPE" || intent === "UNRESOLVED" ? "low" : "high", ambiguity }, evidence: { references: evidence, missing: ambiguity ? ["reference.target"] : [], stale: [] }, financialImpact: { factsRead: before, proposedChanges: proposal ? [proposal] : [], acceptedSessionChanges: accepted, derivedCalculations: decision.reconciliation ? [{ id: `calculation:${state.sequence}`, type: "RECONCILIATION", expression: "available - allocated", result: decision.reconciliation.remaining, evidenceIds: evidence.map((item) => item.id) }] : [], before, after }, decision, response, actions, next, memory, telemetry: { event: event === "turn_understood" && decision.recommendation ? "recommendation_presented" : event, safeAttributes: { capability, modality: input.modality, scope: intent === "OUT_OF_SCOPE" ? "out_of_scope" : "financial" } } });
}
