import { allocateNextDollar, founderAllocationFixture, reconcileAllocation } from "./allocation-intelligence.ts";
import type { CanonicalDecisionResult, FactValue } from "./turn-contract.ts";
const value = (facts: FactValue[], entityId: string, field: FactValue["field"]) => facts.find((item) => item.entityId === entityId && item.field === field)?.value;
const base = (id: string, type: CanonicalDecisionResult["type"], facts: FactValue[]): CanonicalDecisionResult => ({ decisionId: id, type, goal: null, constraints: [], factsConsidered: facts, answer: null, recommendation: null, quantified: [], allocation: [], reconciliation: null, alternatives: [], tradeoffs: [], consequenceOfDelay: null, uncertainty: [], confidence: "high", status: "final", affectedEntityIds: [] });
function allocationDecision(facts: FactValue[], sequence: number): CanonicalDecisionResult | null {
  const cash = Number(value(facts, "cash", "available_amount")), minimum = Number(value(facts, "card", "minimum")); if (!Number.isFinite(cash) || !Number.isFinite(minimum)) return null;
  const fixture = founderAllocationFixture(); fixture.resources = fixture.resources.map((item) => item.id === "cash" ? { ...item, amount: cash } : item); fixture.needs = fixture.needs.map((item) => item.id === "card-minimum" ? { ...item, amountRequired: minimum, minimumUsefulPayment: minimum } : item.id === "utility" ? { ...item, amountRequired: Number(value(facts, "utility", "amount") || item.amountRequired), fullAmount: Number(value(facts, "utility", "amount") || item.fullAmount) } : item.id === "repair" ? { ...item, amountRequired: Number(value(facts, "repair", "estimate") || item.amountRequired) } : item.id === "current-rent" ? { ...item, amountRequired: Number(value(facts, "rent", "amount") || item.amountRequired) } : item.id === "rent-arrears" ? { ...item, amountRequired: Number(value(facts, "rent", "balance") || item.amountRequired) } : item);
  const work = value(facts, "repair", "work_required"); const result = allocateNextDollar({ fixture, repairRequiredForWork: work === true ? true : work === false ? false : null, repairAmount: Number(value(facts, "repair", "estimate") || 0), protectUtility: value(facts, "utility", "timing") === "before_next_income" }); const option = result.options.find((item) => item.id === result.recommendedId) || null; const reconciled = option ? reconcileAllocation(result, option) : null;
  return { ...base(`decision:${sequence}`, "ALLOCATION", facts), goal: "Protect immediate stability", constraints: result.limitation ? [result.limitation] : [], recommendation: { type: "PROTECT_STABILITY", summary: result.simpleExplanation }, allocation: option?.allocations.map((item) => ({ entityId: item.needId, amount: item.allocated })) || [], reconciliation: reconciled ? { available: reconciled.available, allocated: reconciled.allocated, remaining: reconciled.leftUnallocated } : null, uncertainty: result.blockingQuestion ? [result.blockingQuestion.prompt] : result.limitation ? [result.limitation] : [], confidence: result.blockingQuestion ? "medium" : "high", status: result.blockingQuestion ? "preliminary" : "final", affectedEntityIds: option?.allocations.map((item) => item.needId) || ["repair", "card", "utility", "rent"] };
}
export function deriveDecision(facts: FactValue[], capability: string, sequence: number): CanonicalDecisionResult {
  const decision = base(`decision:${sequence}`, "NONE", facts);
  if (capability === "ASSESS_EXPECTED_RESOURCE" || facts.some((item) => item.entityType === "RECEIVABLE")) { const gross = Number(value(facts, "invoice-2500", "gross") || 0), materials = Number(value(facts, "invoice-2500", "materials") || 0), received = value(facts, "invoice-2500", "received_status") === true; return { ...decision, type: "EXPECTED_RESOURCE", constraints: ["Expected resources are unavailable until received"], recommendation: { type: "EXCLUDE_EXPECTED_RESOURCE", summary: received ? "Treat only received owner-available funds as current cash." : "The invoice is expected, not available cash; keep it outside today’s plan." }, quantified: [{ label: "Potential owner-available amount", value: Math.max(0, gross - materials), unit: "USD" }], uncertainty: received ? [] : ["Receipt remains unconfirmed"], confidence: received ? "high" : "medium", status: received ? "final" : "preliminary", affectedEntityIds: ["invoice-2500"] }; }
  const allocation = allocationDecision(facts, sequence); if (allocation) return allocation;
  const prior = Number(value(facts, "snapshot-prior", "available_amount")), current = Number(value(facts, "snapshot-current", "available_amount")); if (Number.isFinite(prior) && Number.isFinite(current)) return { ...decision, type: "SNAPSHOT_CHANGE", recommendation: { type: "REVIEW_CHANGE", summary: `Available cash is $${Math.abs(current - prior)} ${current < prior ? "lower" : "higher"} than the prior snapshot.` }, quantified: [{ label: "Available cash change", value: current - prior, unit: "USD" }], affectedEntityIds: ["snapshot-prior", "snapshot-current"] };
  if (facts.some((item) => item.entityId === "camp-deposit")) return { ...decision, type: "GOAL_PRIORITY", goal: "Balance card payoff and camp timing", recommendation: { type: "PRIORITIZE_DEADLINE", summary: "Protect the time-sensitive camp deposit before accelerating optional card payoff." }, tradeoffs: ["Extra card payoff waits while the nearer deadline is protected."], consequenceOfDelay: "The camp place may be lost if its deposit deadline is missed.", affectedEntityIds: ["camp-deposit", "card-goal"] };
  return decision;
}
