import type { MoneyTransaction } from "../money-picture.ts";
import type { EvidenceReference, FactValue, FinancialEntity } from "./turn-contract.ts";
export type TruthProvenanceType = "CONNECTED_DATA" | "USER_CONFIRMED" | "DERIVED" | "INFERRED" | "EXPECTED" | "FIXTURE" | "MEMORY_CONFIRMED";
export type TruthOwnership = { userId: string; householdId: string | null; scope: "user" | "household" | "business" };
export type TruthProvenance = { sourceType: TruthProvenanceType; sourceId: string; observedAt: string | null; updatedAt: string | null; freshness: "current" | "stale" | "unknown"; confidence: "high" | "medium" | "low"; ownership: TruthOwnership };
export type GovernedTruthMemory = { id: string; fact: FactValue; status: "confirmed" | "superseded" | "revoked"; evidenceIds: string[] };
export type CanonicalFinancialTruth = { version: 1; subject: TruthOwnership; asOf: string; sourceMode: "fixture" | "sandbox" | "authenticated_preview" | "production_adapter"; entities: FinancialEntity[]; facts: FactValue[]; evidence: TruthProvenance[]; transactions: MoneyTransaction[]; liabilities: FinancialEntity[]; recurringObligations: FinancialEntity[]; income: FinancialEntity[]; offAccountCash: FinancialEntity[]; receivables: FinancialEntity[]; goals: FinancialEntity[]; constraints: FactValue[]; peopleAndHousehold: FinancialEntity[]; confirmedContext: FactValue[]; governedMemory: GovernedTruthMemory[] };
const entity = (transaction: MoneyTransaction, facts: FactValue[]): FinancialEntity => ({ id: transaction.id, type: "TRANSACTION", label: transaction.name, aliases: [...new Set([transaction.name, transaction.merchantName].filter((item): item is string => Boolean(item)))], facts: facts.filter((fact) => fact.entityId === transaction.id) });
export function canonicalTruthFromTransactions(input: { userId: string; householdId?: string | null; transactions: MoneyTransaction[]; asOf: string; sourceMode: CanonicalFinancialTruth["sourceMode"] }): CanonicalFinancialTruth { const ownership: TruthOwnership = { userId: input.userId, householdId: input.householdId || null, scope: "user" }; const sourceType: TruthProvenanceType = input.sourceMode === "fixture" ? "FIXTURE" : "CONNECTED_DATA"; const facts = input.transactions.flatMap((transaction): FactValue[] => [{ entityId: transaction.id, entityType: "TRANSACTION", field: "amount", value: transaction.amount, status: "confirmed", evidenceIds: [`transaction:${transaction.id}`] }, { entityId: transaction.id, entityType: "TRANSACTION", field: "merchant", value: transaction.name, status: "confirmed", evidenceIds: [`transaction:${transaction.id}`] }, { entityId: transaction.id, entityType: "TRANSACTION", field: "category", value: transaction.category, status: "confirmed", evidenceIds: [`transaction:${transaction.id}`] }, { entityId: transaction.id, entityType: "TRANSACTION", field: "account_reference", value: transaction.accountLabel, status: "confirmed", evidenceIds: [`transaction:${transaction.id}`] }]); const evidence = input.transactions.map((transaction): TruthProvenance => ({ sourceType, sourceId: `transaction:${transaction.id}`, observedAt: transaction.date, updatedAt: input.asOf, freshness: "current", confidence: "high", ownership })); return { version: 1, subject: ownership, asOf: input.asOf, sourceMode: input.sourceMode, entities: input.transactions.map((transaction) => entity(transaction, facts)), facts, evidence, transactions: input.transactions.map((transaction) => ({ ...transaction })), liabilities: [], recurringObligations: [], income: [], offAccountCash: [], receivables: [], goals: [], constraints: [], peopleAndHousehold: [], confirmedContext: [], governedMemory: [] }; }
export function evidenceReference(source: TruthProvenance): EvidenceReference { return { id: source.sourceId, provenance: source.sourceType, sourceId: source.sourceId, observedAt: source.observedAt, updatedAt: source.updatedAt, freshness: source.freshness, confidence: source.confidence, ownership: source.ownership }; }
export function assertAuthorizedTruth(truth: CanonicalFinancialTruth, authenticatedUserId: string) { if (!authenticatedUserId || truth.subject.userId !== authenticatedUserId) throw new Error("AUTHORIZED_FINANCIAL_TRUTH_REQUIRED"); return truth; }
