export type FinancialPriority = "critical" | "urgent" | "important" | "optimization" | "informational";
export type TargetMode = "fixed_date" | "suggested_date" | "flexible_timeline" | "monthly_contribution_target" | "as_soon_as_practical";
export type ReconciliationLine = { key: "known_cash" | "protected_reserve" | "expected_income" | "protected_obligations" | "upcoming_obligations" | "recurring_commitments" | "essential_spending" | "available_for_goal" | "outstanding_amount" | "remaining_gap"; label: string; operation: "start" | "add" | "subtract" | "equals"; amount: number | null; evidenceIds: string[]; dataStatus: "known" | "missing" | "stale" };
export type FinancialGap = { obligation: string; requiredAmount: number | null; amountPaid: number | null; remainingAmount: number | null; dueDate: string | null; nextDueDate: string | null; targetCatchUpDate: string | null; expectedIncome: number | null; availableCash: number | null; protectedReserve: number | null; protectedObligations: number | null; upcomingObligations: number | null; recurringCommitments: number | null; essentialSpending: number | null; availableForGoal: number | null; estimatedShortfall: number | null; confidence: "high" | "medium" | "low"; missingInputs: string[]; staleData: boolean; assumptions: string[]; limitations: string[]; evidenceIds: string[]; reconciliation: ReconciliationLine[]; analysisWindow: { start: string; end: string } | null; normalMonthlyAmount?: number | null; paymentType?: "full" | "partial" | "late" | "catch_up" | "extra" | "unsure"; periodsBehind?: number | null };
export type SpendingFlexibility = "protected_essential" | "committed_obligation" | "flexible_essential" | "discretionary" | "potentially_cancellable" | "user_protected" | "unusual_one_time" | "uncertain";
export type SpendingCandidate = { key: string; label: string; category: string; amount: number; transactionIds: string[]; flexibility: SpendingFlexibility; recurring: boolean; userProtected?: boolean; requiredMinimum?: boolean };
export type CandidateLever = { id: string; type: "reduce_category" | "pause_commitment" | "redirect_income" | "apply_refund" | "delay_purchase" | "reduce_above_minimum_debt" | "add_confirmed_income" | "use_available_cash" | "negotiate_obligation" | "extend_target_date" | "split_milestones" | "wait_for_data" | "seek_human_help"; label: string; evidenceIds: string[]; estimatedAmount: number | null; timeframe: string; confidence: "high" | "medium" | "low"; benefit: string; impact: string; effort: "low" | "medium" | "high"; reversible: boolean; tradeoff: string; assumptions: string[]; touchesProtectedSpending: boolean; confirmationRequired: boolean; professionalInvolvementRequired: boolean; humanHelpAppropriate: boolean };
export type RecoveryOption = { name: "Fastest" | "Balanced" | "Lowest disruption" | "User-customized"; goal: string; targetAmount: number; targetDate: string | null; levers: CandidateLever[]; leverContributions: Array<{ leverId: string; amount: number }>; expectedContribution: number; protectedExpenses: string[]; tradeoffs: string[]; risks: string[]; assumptions: string[]; confidence: "high" | "medium" | "low"; projectedCompletionDate: string | null; unresolved: string[]; evidenceIds: string[] };
export type TimelineOption = RecoveryOption & { targetMode: TargetMode; durationMonths: number; contributionPerMonth: number; suggested: true; confirmed: false; whatCouldChange: string[] };
export type PlanConstraint = { kind: "protect" | "prefer" | "exclude" | "deadline"; key: string; value: string };
export type RecoveryPlanProposal = { target: string; gap: FinancialGap; options: RecoveryOption[]; constraints: PlanConstraint[]; confirmed: false; activationBlocked: true };
export type PlanProgress = { status: "on_track" | "ahead" | "behind" | "blocked_by_missing_data" | "needs_adjustment" | "completed"; actualContribution: number; expectedContribution: number; remainingGap: number | null; message: string };

export function expectedIncomeWithinWindow(items: Array<{ amount: number; expectedDate: string; evidenceId: string }>, window: { start: string; end: string }) { const included = items.filter((item) => item.expectedDate >= window.start && item.expectedDate <= window.end); return { amount: included.reduce((sum, item) => sum + item.amount, 0), evidenceIds: included.map((item) => item.evidenceId), window }; }

const exclusiveExpenseCategories = ["protected_obligations", "upcoming_obligations", "recurring_commitments", "essential_spending"] as const;
export function assertMutuallyExclusiveEvidence(evidence: Partial<Record<(typeof exclusiveExpenseCategories)[number], string[]>>) { const owner = new Map<string, string>(); for (const category of exclusiveExpenseCategories) for (const id of evidence[category] || []) { const prior = owner.get(id); if (prior && prior !== category) throw new Error(`OVERLAPPING_OBLIGATION_EVIDENCE:${id}`); owner.set(id, category); } }

export function buildHousingGap(input: { obligation: string; normalMonthlyRent?: number | null; amountPaid?: number | null; outstanding?: number | null; dueDate?: string | null; nextDueDate?: string | null; targetCatchUpDate?: string | null; expectedIncome?: number | null; availableCash?: number | null; protectedReserve?: number | null; protectedObligations?: number | null; upcomingObligations?: number | null; recurringCommitments?: number | null; essentialSpending?: number | null; evidenceIds: string[]; evidenceByCategory?: Partial<Record<"known_cash" | "protected_reserve" | "expected_income" | "protected_obligations" | "upcoming_obligations" | "recurring_commitments" | "essential_spending" | "outstanding_amount", string[]>>; analysisWindow?: { start: string; end: string } | null; paymentType?: FinancialGap["paymentType"]; periodsBehind?: number | null; staleData?: boolean; assumptions?: string[]; limitations?: string[] }): FinancialGap {
  assertMutuallyExclusiveEvidence(input.evidenceByCategory || {});
  const missingInputs = [...(input.normalMonthlyRent == null ? ["normal monthly rent"] : []), ...(input.outstanding == null ? ["current amount outstanding"] : [])];
  const wholePictureValues = [input.expectedIncome, input.availableCash, input.protectedReserve, input.protectedObligations, input.upcomingObligations, input.recurringCommitments, input.essentialSpending];
  const wholePictureKnown = wholePictureValues.every((value) => value != null);
  const usableCash = wholePictureKnown ? Math.max(0, input.availableCash! - input.protectedReserve!) : null;
  const availableForGoal = wholePictureKnown ? Math.max(0, usableCash! + input.expectedIncome! - input.protectedObligations! - input.upcomingObligations! - input.recurringCommitments! - input.essentialSpending!) : null;
  const estimatedShortfall = input.outstanding != null && availableForGoal != null ? Math.max(0, input.outstanding - availableForGoal) : null;
  const evidence = input.evidenceByCategory || {}; const status = (amount: number | null | undefined): ReconciliationLine["dataStatus"] => input.staleData ? "stale" : amount == null ? "missing" : "known";
  const line = (key: ReconciliationLine["key"], label: string, operation: ReconciliationLine["operation"], amount: number | null | undefined): ReconciliationLine => ({ key, label, operation, amount: amount ?? null, evidenceIds: evidence[key as keyof typeof evidence] || input.evidenceIds, dataStatus: status(amount) });
  const reconciliation = [line("known_cash", "Known cash", "start", input.availableCash), line("protected_reserve", "Less protected reserve", "subtract", input.protectedReserve), line("expected_income", "Plus expected income", "add", input.expectedIncome), line("protected_obligations", "Less protected obligations", "subtract", input.protectedObligations), line("upcoming_obligations", "Less upcoming obligations", "subtract", input.upcomingObligations), line("recurring_commitments", "Less recurring commitments", "subtract", input.recurringCommitments), line("essential_spending", "Less essential spending", "subtract", input.essentialSpending), line("available_for_goal", "Equals available for goal", "equals", availableForGoal), line("outstanding_amount", "Outstanding amount", "start", input.outstanding), line("remaining_gap", "Equals remaining gap", "equals", estimatedShortfall)];
  return { obligation: input.obligation, requiredAmount: input.normalMonthlyRent ?? null, normalMonthlyAmount: input.normalMonthlyRent ?? null, amountPaid: input.amountPaid ?? null, remainingAmount: input.outstanding ?? null, dueDate: input.dueDate ?? null, nextDueDate: input.nextDueDate ?? null, targetCatchUpDate: input.targetCatchUpDate ?? null, expectedIncome: input.expectedIncome ?? null, availableCash: input.availableCash ?? null, protectedReserve: input.protectedReserve ?? null, protectedObligations: input.protectedObligations ?? null, upcomingObligations: input.upcomingObligations ?? null, recurringCommitments: input.recurringCommitments ?? null, essentialSpending: input.essentialSpending ?? null, availableForGoal, estimatedShortfall, confidence: input.staleData || missingInputs.length || !wholePictureKnown ? "low" : "high", missingInputs, staleData: Boolean(input.staleData), assumptions: input.assumptions || [], limitations: [...(input.limitations || []), ...(!wholePictureKnown ? ["Whole-picture obligations are incomplete."] : []), ...(!input.analysisWindow ? ["The analysis window is not confirmed."] : [])], evidenceIds: input.evidenceIds, reconciliation, analysisWindow: input.analysisWindow || null, paymentType: input.paymentType || "unsure", periodsBehind: input.periodsBehind ?? null };
}

export function rankFinancialPriority(input: { housingGap?: FinancialGap | null; utilityShutoff?: boolean; daysUntilDue?: number | null; requiredMinimumMissed?: boolean; optimizationOnly?: boolean }): FinancialPriority {
  if (input.utilityShutoff || (input.housingGap?.remainingAmount != null && input.housingGap.remainingAmount > 0 && (input.daysUntilDue == null || input.daysUntilDue <= 7))) return "critical";
  if (input.housingGap?.remainingAmount != null && input.housingGap.remainingAmount > 0) return "urgent";
  if (input.requiredMinimumMissed) return "important";
  return input.optimizationOnly ? "optimization" : "informational";
}

export function candidateLevers(candidates: SpendingCandidate[], constraints: PlanConstraint[] = []): CandidateLever[] {
  const protectedKeys = new Set(constraints.filter((item) => item.kind === "protect" || item.kind === "exclude").map((item) => item.key.toLowerCase()));
  return candidates.filter((item) => !item.userProtected && !item.requiredMinimum && !protectedKeys.has(item.key.toLowerCase())).filter((item) => ["discretionary", "potentially_cancellable", "flexible_essential"].includes(item.flexibility)).filter((item) => item.recurring && item.flexibility !== "unusual_one_time").map((item) => {
    const cancellable = item.flexibility === "potentially_cancellable";
    const rate = item.flexibility === "discretionary" ? .5 : item.flexibility === "flexible_essential" ? .15 : .8;
    return { id: `lever:${item.key}`, type: cancellable ? "pause_commitment" : "reduce_category", label: item.label, evidenceIds: item.transactionIds, estimatedAmount: Math.round(item.amount * rate * 100) / 100, timeframe: "next month", confidence: item.transactionIds.length >= 2 ? "high" : "medium", benefit: `Contributes toward the confirmed goal using ${item.transactionIds.length} supporting transactions.`, impact: `Potentially free about $${(item.amount * rate).toFixed(0)}.`, effort: "medium", reversible: true, tradeoff: cancellable ? "Requires the user to verify and make any cancellation." : "Requires lower future spending in this area.", assumptions: ["Future spending resembles the evidence period."], touchesProtectedSpending: false, confirmationRequired: true, professionalInvolvementRequired: false, humanHelpAppropriate: false };
  });
}

const takeUntil = (levers: CandidateLever[], target: number, fraction: number) => { const selected: CandidateLever[] = []; let total = 0; for (const lever of levers) { if (total >= target * fraction) break; selected.push(lever); total += lever.estimatedAmount || 0; } return { selected, total: Math.min(total, target) }; };
export function generateRecoveryOptions(gap: FinancialGap, levers: CandidateLever[], constraints: PlanConstraint[] = []): RecoveryOption[] {
  const target = gap.estimatedShortfall;
  if (target == null || target <= 0 || !levers.length) return [];
  const supported = levers.filter((lever) => !lever.touchesProtectedSpending && lever.estimatedAmount != null).sort((a, b) => (b.estimatedAmount || 0) - (a.estimatedAmount || 0));
  const totalSupport = supported.reduce((sum, lever) => sum + (lever.estimatedAmount || 0), 0); if (!totalSupport) return [];
  const specs = totalSupport >= target ? [["Fastest", 1], ["Balanced", .75], ["Lowest disruption", .5]] as const : [["Balanced", 1]] as const;
  const protectedExpenses = constraints.filter((item) => item.kind === "protect" || item.kind === "exclude").map((item) => item.value);
  return specs.map(([name, fraction]) => { const picked = takeUntil(supported, target, fraction); return { name, goal: gap.obligation, targetAmount: target, targetDate: constraints.find((item) => item.kind === "deadline")?.value || gap.targetCatchUpDate || gap.dueDate, levers: picked.selected, leverContributions: picked.selected.map((lever) => ({ leverId: lever.id, amount: lever.estimatedAmount || 0 })), expectedContribution: Math.min(picked.total, totalSupport, target), protectedExpenses, tradeoffs: picked.selected.map((lever) => lever.tradeoff), risks: gap.staleData ? ["Connected activity is stale."] : [], assumptions: ["Future activity is similar to the evidence period.", "The user makes any selected changes."], confidence: gap.confidence === "low" ? "low" : picked.selected.every((lever) => lever.confidence === "high") ? "high" : "medium", projectedCompletionDate: null, unresolved: gap.missingInputs, evidenceIds: [...new Set(picked.selected.flatMap((lever) => lever.evidenceIds))] } as RecoveryOption; });
}

const addMonths = (iso: string, months: number) => { const date = new Date(`${iso}T12:00:00Z`); date.setUTCMonth(date.getUTCMonth() + months); return date.toISOString().slice(0, 10); };
export function generateTimelineOptions(input: { gap: FinancialGap; levers: CandidateLever[]; constraints?: PlanConstraint[]; mode: Exclude<TargetMode, "fixed_date">; asOf: string; monthlyContribution?: number | null }): TimelineOption[] {
  const { gap, mode, asOf } = input; if (gap.estimatedShortfall == null || gap.estimatedShortfall <= 0 || gap.confidence === "low") return [];
  const supported = input.levers.filter((lever) => !lever.touchesProtectedSpending && (lever.estimatedAmount || 0) > 0).sort((a, b) => (b.estimatedAmount || 0) - (a.estimatedAmount || 0));
  const total = supported.reduce((sum, lever) => sum + (lever.estimatedAmount || 0), 0); if (!total && !input.monthlyContribution) return [];
  const protectedExpenses = (input.constraints || []).filter((item) => item.kind === "protect" || item.kind === "exclude").map((item) => item.value);
  const specs = mode === "monthly_contribution_target" ? [["User-customized", input.monthlyContribution || Math.max(50, Math.round(total * .6))]] as const : mode === "as_soon_as_practical" ? [["Fastest", total]] as const : [["Fastest", total], ["Balanced", total * .7], ["Lowest disruption", total * .4]] as const;
  return specs.filter(([, contribution]) => contribution > 0).map(([name, rawContribution]) => { const contribution = Math.min(gap.estimatedShortfall || rawContribution, Math.round(rawContribution)); const durationMonths = Math.max(1, Math.ceil((gap.estimatedShortfall || 0) / contribution)); const picked = takeUntil(supported, contribution, 1); return { name, goal: gap.obligation, targetAmount: gap.estimatedShortfall || 0, targetDate: addMonths(asOf, durationMonths), projectedCompletionDate: addMonths(asOf, durationMonths), levers: picked.selected, leverContributions: picked.selected.map((lever) => ({ leverId: lever.id, amount: lever.estimatedAmount || 0 })), expectedContribution: contribution, protectedExpenses, tradeoffs: picked.selected.map((lever) => lever.tradeoff), risks: gap.staleData ? ["Connected activity is stale."] : [], assumptions: ["Each month uses the same bounded analysis window.", "Expected income includes only income arriving within that window.", "The user confirms any selected changes."], confidence: gap.confidence, unresolved: [], evidenceIds: [...new Set([...gap.evidenceIds, ...picked.selected.flatMap((lever) => lever.evidenceIds)])], targetMode: mode, durationMonths, contributionPerMonth: contribution, suggested: true, confirmed: false, whatCouldChange: ["income or obligations change", "connected evidence becomes stale", "a protected priority changes"] } as TimelineOption; });
}

export function proposeRecoveryPlan(gap: FinancialGap, options: RecoveryOption[], constraints: PlanConstraint[] = []): RecoveryPlanProposal { return { target: gap.obligation, gap, options, constraints, confirmed: false, activationBlocked: true }; }
export function confirmRecoveryPlan(): never { throw new Error("DURABLE_PLAN_PERSISTENCE_REQUIRED"); }
export function monitorPlan(input: { gap: FinancialGap; actualContribution: number; expectedContribution: number; stale: boolean }): PlanProgress {
  const remaining = input.gap.remainingAmount == null ? null : Math.max(0, input.gap.remainingAmount - input.actualContribution);
  if (input.stale || remaining == null) return { status: "blocked_by_missing_data", actualContribution: input.actualContribution, expectedContribution: input.expectedContribution, remainingGap: remaining, message: "Current activity is incomplete, so progress cannot be determined reliably yet." };
  if (remaining === 0) return { status: "completed", actualContribution: input.actualContribution, expectedContribution: input.expectedContribution, remainingGap: 0, message: "The tracked target appears complete based on current activity." };
  const status = input.actualContribution > input.expectedContribution ? "ahead" : input.actualContribution < input.expectedContribution ? "behind" : "on_track";
  return { status, actualContribution: input.actualContribution, expectedContribution: input.expectedContribution, remainingGap: remaining, message: status === "behind" ? "The plan is behind the current target. Would you like to compare an adjustment or extend the deadline?" : `The plan is ${status === "ahead" ? "ahead" : "on track"} based on current activity.` };
}
