import { createCovarifySession } from "./covarify-orchestrator.ts";
import type { FactValue, FinancialEntity, FinancialEntityType } from "./turn-contract.ts";
export type GoldenJourneyId = "competing_cash_needs" | "transaction_meaning" | "expected_business_income" | "goal_conflict" | "what_changed" | "contextual_correction";
export type GoldenJourney = { id: GoldenJourneyId; title: string; facts: FactValue[]; entities: FinancialEntity[]; examples: string[]; expectedCapabilities: string[] };
const types: Record<string, FinancialEntityType> = { cash: "CASH_RESOURCE", repair: "REPAIR", card: "LIABILITY", utility: "OBLIGATION", rent: "OBLIGATION", "target-312": "TRANSACTION", callie: "PERSON", "invoice-2500": "RECEIVABLE", "card-goal": "GOAL", "camp-deposit": "EXPENSE", "snapshot-current": "CASH_RESOURCE", "snapshot-prior": "CASH_RESOURCE", payment: "TRANSACTION", visa: "ACCOUNT", mastercard: "ACCOUNT" };
const fact = (entityId: string, field: FactValue["field"], value: FactValue["value"], status: FactValue["status"] = "confirmed"): FactValue => ({ entityId, entityType: types[entityId], field, value, status, evidenceIds: [`fixture:${entityId}:${field}`] });
const entity = (id: string, label: string, aliases: string[], facts: FactValue[]): FinancialEntity => ({ id, type: types[id], label, aliases, facts: facts.filter((item) => item.entityId === id) });
const build = (id: GoldenJourneyId, title: string, facts: FactValue[], labels: Array<[string, string, string[]]>, examples: string[], expectedCapabilities: string[]): GoldenJourney => ({ id, title, facts, entities: labels.map(([entityId, label, aliases]) => entity(entityId, label, aliases, facts)), examples, expectedCapabilities });
const competing = [fact("cash", "available_amount", 900), fact("repair", "estimate", 500), fact("repair", "work_required", null, "unconfirmed"), fact("card", "minimum", 75), fact("utility", "amount", 180), fact("utility", "timing", null, "unconfirmed"), fact("rent", "amount", 3475), fact("rent", "balance", 7890)];
const transaction = [fact("target-312", "amount", 312), fact("target-312", "merchant", "Target"), fact("target-312", "meaning", null, "unconfirmed")];
const invoice = [fact("invoice-2500", "gross", 2500, "expected"), fact("invoice-2500", "materials", 300), fact("invoice-2500", "received_status", false), fact("cash", "available_amount", 0, "derived")];
const goals = [fact("card-goal", "priority", "pay_down"), fact("camp-deposit", "due_date", "soon"), fact("camp-deposit", "amount", 400)];
const snapshots = [fact("snapshot-prior", "available_amount", 1200), fact("snapshot-current", "available_amount", 900), fact("snapshot-current", "new_obligation", "utility")];
const correction = [fact("payment", "account_reference", "mastercard"), fact("repair", "estimate", 500)];
export const goldenJourneys: Record<GoldenJourneyId, GoldenJourney> = {
  competing_cash_needs: build("competing_cash_needs", "Competing cash needs", competing, [["cash", "available cash", ["cash", "available"]], ["repair", "car repair", ["car", "repair"]], ["card", "card minimum", ["card", "minimum"]], ["utility", "utility payment", ["utility", "bill"]], ["rent", "rent", ["rent", "arrears"]]], ["repair is $400"], ["CORRECT_FACT", "PRIORITIZE_COMPETING_NEEDS"]),
  transaction_meaning: build("transaction_meaning", "Transaction meaning", transaction, [["target-312", "$312 Target charge", ["target", "target charge"]], ["callie", "Callie", ["callie"]]], ["That $312 Target charge was back-to-school stuff for Callie."], ["PROPOSE_MEMORY"]),
  expected_business_income: build("expected_business_income", "Expected business income", invoice, [["invoice-2500", "$2,500 invoice", ["invoice", "receivable", "materials"]], ["cash", "available cash", ["cash"]]], ["I’m getting a $2,500 invoice paid Friday, but $300 is materials."], ["ASSESS_EXPECTED_RESOURCE"]),
  goal_conflict: build("goal_conflict", "Goal conflict", goals, [["card-goal", "card payoff goal", ["card", "card payoff"]], ["camp-deposit", "camp deposit", ["camp", "camp deposit", "deposit"]]], ["I want to pay down my card, but a camp deposit is due."], ["PRIORITIZE_COMPETING_NEEDS"]),
  what_changed: build("what_changed", "What changed", snapshots, [["snapshot-prior", "last week", ["last week", "prior snapshot"]], ["snapshot-current", "current snapshot", ["current", "today"]]], ["What changed since last week?"], ["COMPARE_FINANCIAL_SNAPSHOTS"]),
  contextual_correction: build("contextual_correction", "Contextual correction", correction, [["payment", "payment", ["payment", "this payment"]], ["visa", "Visa", ["visa"]], ["mastercard", "Mastercard", ["mastercard"]], ["repair", "car repair", ["car", "repair"]]], ["No, I meant the Visa, not the Mastercard."], ["CORRECT_REFERENCE"]),
};
export function createGoldenSession(id: GoldenJourneyId) { const fixture = goldenJourneys[id]; return createCovarifySession({ sessionId: `golden:${id}`, entities: fixture.entities, facts: fixture.facts }); }
