import { goldenJourneys, type GoldenJourneyId } from "./golden-journeys.ts";
import { assertTurnInvariants, confirmationFor, type CovarifyTurn, type FactValue, type InputModality, type PresentationDepth, type SemanticAction, type StateChange } from "./turn-contract.ts";

export type HeadlessSession = { sessionId: string; sequence: number; journeyId: GoldenJourneyId; facts: FactValue[]; presentationDepth: PresentationDepth; pendingChange: StateChange | null; undo: StateChange | null; stopped: boolean };
export type TurnInput = { modality: InputModality; statement?: string; action?: { id: string; payload?: Record<string, string | number | boolean | null> }; now?: string };

export function createHeadlessSession(journeyId: GoldenJourneyId, sessionId = `golden:${journeyId}`): HeadlessSession { const journey = goldenJourneys[journeyId]; return { sessionId, sequence: 0, journeyId, facts: journey.facts.map((item) => ({ ...item, evidenceIds: [...item.evidenceIds] })), presentationDepth: "GUIDED", pendingChange: null, undo: null, stopped: false }; }
const normalize = (value: string) => value.trim().replace(/\s+/g, " ");
const action = (id: string, type: SemanticAction["type"], label: string, consequence: SemanticAction["consequence"], payload: SemanticAction["payload"] = {}, reversible = false): SemanticAction => ({ id, type, label, consequence, confirmation: confirmationFor(consequence), reversible, payload });
const fact = (state: HeadlessSession, entity: string, field: string) => state.facts.find((item) => item.entityId === entity && item.field === field);
const replaceFact = (state: HeadlessSession, change: StateChange) => { state.facts = state.facts.map((item) => item.entityId === change.entityId && item.field === change.field ? { ...item, value: change.after, status: "confirmed" } : item); };
const statementFor = (input: TurnInput) => normalize(input.statement || "");

export function runHeadlessTurn(state: HeadlessSession, input: TurnInput): CovarifyTurn {
  const stateBefore = state.facts.map((item) => ({ ...item, evidenceIds: [...item.evidenceIds] }));
  state.sequence += 1;
  const raw = input.modality === "guided_action" ? null : input.statement || "";
  const statement = statementFor(input);
  let intent = "unsupported"; let primary = "I can’t apply that request in this controlled journey."; let rationale: string | null = null; let question: string | null = null; let ambiguity: string | null = null; let recommendation = goldenJourneys[state.journeyId].initialRecommendation; let status: CovarifyTurn["decision"]["status"] = recommendation ? "preliminary" : "not_applicable"; let event: CovarifyTurn["telemetry"]["event"] = "turn_understood"; let proposed: StateChange[] = []; let accepted: StateChange[] = []; let actions: SemanticAction[] = []; let memory: CovarifyTurn["memory"] = { disposition: "session_only", proposal: null }; let resolvedReferences: CovarifyTurn["understanding"]["resolvedReferences"] = [];

  const guidedId = input.action?.id;
  const amount = Number((statement.match(/\$?([\d,]+(?:\.\d{1,2})?)/)?.[1] || input.action?.payload?.amount || "").toString().replaceAll(",", ""));
  const depth = /(?:just tell me|go faster|keep it simple)/i.test(statement) ? "CONCISE" : /(?:show me everything|show me the math)/i.test(statement) ? "DETAILED" : /walk me through it/i.test(statement) ? "GUIDED" : null;
  if (depth || guidedId === "presentation.change") { state.presentationDepth = depth || input.action?.payload?.depth as PresentationDepth || state.presentationDepth; intent = "change_presentation_depth"; primary = `Presentation changed to ${state.presentationDepth.toLowerCase()}.`; recommendation = null; status = "not_applicable"; actions = [action("presentation.change", "CHANGE_PRESENTATION_DEPTH", "Change explanation depth", "SESSION_REVERSIBLE", { depth: state.presentationDepth }, true)]; }
  else if (guidedId === "session.stop" || /stop here|done for now/i.test(statement)) { state.stopped = true; intent = "stop_for_now"; primary = "Stopped for now. Your session context is preserved on this device for this preview."; event = "stopped_for_now"; actions = [action("session.resume", "RESUME", "Resume", "SESSION_REVERSIBLE", {}, true)]; }
  else if (guidedId === "session.resume" || /^resume$/i.test(statement)) { state.stopped = false; intent = "resume"; primary = "Resumed where you stopped."; event = "resumed"; actions = [action("session.stop", "STOP_FOR_NOW", "Stop for now", "SESSION_REVERSIBLE", {}, true)]; }
  else if (guidedId === "correction.apply" && state.pendingChange) { const change = { ...state.pendingChange, status: "accepted_session" as const }; replaceFact(state, change); state.undo = { ...change, before: change.after, after: change.before, changeId: `undo:${change.changeId}` }; state.pendingChange = null; intent = "apply_correction"; primary = `Applied the correction to ${change.entityId} ${change.field}.`; accepted = [change]; event = "correction_applied"; actions = [action(`undo.${change.entityId}.${change.field}`, "UNDO", `Undo ${change.entityId} ${change.field} change`, "SESSION_REVERSIBLE", { changeId: change.changeId }, true)]; }
  else if (guidedId === "correction.undo" && state.undo) { const change = { ...state.undo, status: "accepted_session" as const }; replaceFact(state, change); state.undo = null; intent = "undo"; primary = `Undid the ${change.entityId} ${change.field} change.`; accepted = [change]; event = "undo_used"; }
  else if (state.journeyId === "competing_cash_needs" && (guidedId === "repair.estimate.propose" || /(?:car|repair|that amount).*(?:\$?\d)|(?:\$?\d).*(?:car|repair)/i.test(statement))) { const current = fact(state, "repair", "estimate")!; const change: StateChange = { changeId: `repair.estimate:${state.sequence}`, entityId: "repair", field: "estimate", before: current.value, after: amount, status: "proposed", reversible: true }; state.pendingChange = change; intent = "correct_fact"; primary = `Review changing the repair estimate from $${current.value} to $${amount}.`; question = "Apply this session-only correction?"; proposed = [change]; event = "correction_proposed"; actions = [action("correction.apply", "APPLY_CORRECTION", `Apply $${amount} repair estimate`, "SESSION_REVERSIBLE", { changeId: change.changeId }, true), action("correction.cancel", "CANCEL_CORRECTION", "Cancel correction", "READ_ONLY")]; resolvedReferences = [{ phrase: /that amount/i.test(statement) ? "that amount" : "repair", entityId: "repair", confidence: "high" }]; }
  else if (state.journeyId === "contextual_correction" && (guidedId === "payment.account.propose" || /visa.*not.*mastercard|meant the visa/i.test(statement))) { const current = fact(state, "payment", "account")!; const change: StateChange = { changeId: `payment.account:${state.sequence}`, entityId: "payment", field: "account", before: current.value, after: "visa", status: "proposed", reversible: true }; state.pendingChange = change; intent = "correct_reference"; primary = "Review changing the payment account from Mastercard to Visa."; question = "Apply this correction?"; proposed = [change]; event = "correction_proposed"; actions = [action("correction.apply", "APPLY_CORRECTION", "Use Visa", "SESSION_REVERSIBLE", { changeId: change.changeId }, true), action("correction.cancel", "CANCEL_CORRECTION", "Keep Mastercard", "READ_ONLY")]; resolvedReferences = [{ phrase: "the Visa", entityId: "visa", confidence: "high" }]; }
  else if (state.journeyId === "transaction_meaning" && /target|back-to-school/i.test(statement)) { intent = "propose_transaction_meaning"; primary = "I matched the $312 Target charge and can propose back-to-school spending for Callie."; question = "Review the transaction meaning before applying it."; const proposedFact: FactValue = { entityId: "target-312", field: "meaning", value: "back-to-school for Callie", status: "unconfirmed", evidenceIds: ["fixture:target-312:amount"] }; memory = { disposition: "memory_proposal", proposal: { proposalId: `memory:${state.sequence}`, fact: proposedFact, sourceTurnId: `turn:${state.sequence}` } }; actions = [action("memory.propose", "PROPOSE_MEMORY", "Review memory proposal", "READ_ONLY")]; event = "correction_proposed"; }
  else if (state.journeyId === "expected_business_income" && /invoice|2,?500|friday/i.test(statement)) { intent = "assess_expected_income"; primary = "The $2,500 invoice is expected, not available cash. After $300 of materials, $2,200 may become owner-available only after receipt and business protections."; rationale = "Expected money cannot fund today’s plan before it is received."; status = "preliminary"; recommendation = "Keep the invoice outside current available cash."; }
  else if (state.journeyId === "goal_conflict" && !/\b(?:it|that|that amount|the other card|this payment)\b/i.test(statement)) { intent = "compare_goals"; primary = "Protect the time-sensitive camp deposit before accelerating the card payoff."; rationale = "The deposit has a nearer consequence of delay; optional extra card payoff remains reversible."; status = "final"; actions = [action("options.compare", "COMPARE_OPTIONS", "Compare options", "READ_ONLY")]; }
  else if (state.journeyId === "what_changed") { intent = "compare_snapshots"; primary = "Available cash is $300 lower than last week, and a utility obligation is now in view."; rationale = "The controlled snapshots changed from $1,200 to $900."; status = "final"; actions = [action("evidence.show", "SHOW_EVIDENCE", "Show evidence", "READ_ONLY"), action("calculation.show", "SHOW_CALCULATION", "Show calculation", "READ_ONLY")]; }
  else if (/\b(?:it|that|that amount|the other card|this payment)\b/i.test(statement)) { intent = "clarify_reference"; ambiguity = "More than one plausible entity is active."; primary = "Which item do you mean?"; question = "Choose the specific payment, account, or amount."; event = "clarification_requested"; actions = [action("clarification.answer", "ANSWER_QUESTION", "Choose an item", "READ_ONLY")]; }

  const turnId = `turn:${state.sessionId}:${state.sequence}`;
  const factsRead = stateBefore;
  const turn: CovarifyTurn = { contractVersion: 1, identity: { turnId, sessionId: state.sessionId, sequence: state.sequence, timestamp: input.now || new Date(0).toISOString(), modality: input.modality }, input: { rawStatement: raw, normalizedStatement: raw == null ? null : statement, guidedActionId: guidedId || null }, understanding: { intent, scope: state.journeyId, referencedEntityIds: resolvedReferences.map((item) => item.entityId), resolvedReferences, confidence: ambiguity ? "low" : intent === "unsupported" ? "low" : "high", ambiguity }, evidence: { references: factsRead.flatMap((item) => item.evidenceIds.map((id) => ({ id, provenance: "fixture" as const, freshness: "current" as const, confidence: "high" as const }))), missing: ambiguity ? ["reference.entity"] : [], stale: [] }, financialImpact: { factsRead, proposedChanges: proposed, acceptedSessionChanges: accepted, derivedCalculations: [], before: stateBefore, after: state.facts.map((item) => ({ ...item, evidenceIds: [...item.evidenceIds] })) }, decision: { decisionId: recommendation ? `decision:${state.journeyId}:${state.sequence}` : null, goal: null, constraints: state.journeyId === "expected_business_income" ? ["Expected income is unavailable until received"] : [], recommendation, rationale, alternatives: [], tradeoffs: [], consequenceOfDelay: null, confidence: status === "preliminary" ? "medium" : intent === "unsupported" ? "low" : "high", status }, response: { primaryMessage: primary, conciseRationale: rationale, blocks: [{ id: `${turnId}:primary`, type: question ? "question" : recommendation ? "recommendation" : state.stopped ? "stopping_state" : "answer", body: primary, emphasis: "primary", evidenceIds: [] }], question, correction: proposed[0] ? { changeId: proposed[0].changeId, message: primary } : null }, actions, next: { bestStep: question || (state.stopped ? "Resume when ready." : actions[0]?.label || "Stop when you have enough."), blocking: Boolean(question), stopped: state.stopped, waitingForEvidence: Boolean(ambiguity) }, memory, telemetry: { event, safeAttributes: { journey: state.journeyId, modality: input.modality, intent } } };
  return assertTurnInvariants(turn);
}
