import type { FinancialGoal } from "./goals.ts";
import type { FinancialPriority, TargetMode } from "./financial-triage.ts";

export type NextBestStepType = "no_action" | "view_evidence" | "answer_clarification" | "review_transaction" | "review_account" | "confirm_category" | "create_merchant_rule" | "review_recurring_commitment" | "refresh_connection" | "update_obligation" | "review_financial_gap" | "compare_options" | "confirm_strategy" | "review_plan_progress" | "adjust_plan" | "wait_for_data" | "escalate_to_human";
export type NextBestStep = { type: NextBestStepType; label: string; reason: string; evidenceIds: string[]; expectedBenefit: string; effort: "low" | "medium" | "high"; urgency: "now" | "soon" | "when_ready"; confidence: "high" | "medium" | "low"; confirmationRequired: boolean; reversible: boolean; capability: string | null; fallbackIfDeclined: string };

export function selectNextBestStep(input: { goal?: FinancialGoal | null; priority?: FinancialPriority | null; evidenceIds?: string[]; missingInputs?: string[]; stale?: boolean; goalConfirmationRequired?: boolean; transactionProposalReady?: boolean; targetMode?: TargetMode | null; fixedDateProvided?: boolean; timelineChoiceRequired?: boolean; proposedTargetReady?: boolean; optionsReady?: boolean; strategyReady?: boolean; activePlanStatus?: "on_track" | "ahead" | "behind" | "blocked_by_missing_data" | "needs_adjustment" | "completed" | "paused" | "canceled" | null }): NextBestStep {
  const evidenceIds = input.evidenceIds || [];
  if (input.transactionProposalReady) return { type: "review_transaction", label: "Review the proposed transaction update", reason: "The transaction meaning is ready for review, but nothing changes without confirmation.", evidenceIds, expectedBenefit: "Confirm the intended purpose and category while preserving source evidence.", effort: "low", urgency: "when_ready", confidence: "high", confirmationRequired: true, reversible: true, capability: "review_transaction", fallbackIfDeclined: "Keep the transaction unchanged." };
  if (input.goalConfirmationRequired) return { type: "answer_clarification", label: "Confirm the housing catch-up goal", reason: "Covarify needs a confirmed goal before generating or ranking recovery options.", evidenceIds, expectedBenefit: "Keep strategy generation aligned with the user’s chosen priority.", effort: "low", urgency: "soon", confidence: "high", confirmationRequired: true, reversible: true, capability: "review_financial_gap", fallbackIfDeclined: "Do not generate a recovery strategy." };
  if (input.stale) return { type: "wait_for_data", label: "Refresh connected activity", reason: "Current data is too stale for a reliable strategy.", evidenceIds, expectedBenefit: "A recommendation based on current balances and activity.", effort: "low", urgency: input.priority === "critical" ? "now" : "soon", confidence: "high", confirmationRequired: false, reversible: true, capability: "refresh_connection", fallbackIfDeclined: "Continue with a qualified partial answer." };
  if (input.missingInputs?.length) return { type: "answer_clarification", label: `Provide ${input.missingInputs[0]}`, reason: "This fact materially changes the gap and available options.", evidenceIds, expectedBenefit: "A correctly quantified gap.", effort: "low", urgency: input.priority === "critical" ? "now" : "soon", confidence: "high", confirmationRequired: false, reversible: true, capability: "review_financial_gap", fallbackIfDeclined: "Keep the gap uncalculated." };
  if (input.timelineChoiceRequired) return { type: "answer_clarification", label: "Choose how to set the recovery timeline", reason: "A fixed deadline is optional; Covarify can calculate realistic timelines from the whole financial picture.", evidenceIds, expectedBenefit: "A recovery path aligned with the user’s preferred timing approach.", effort: "low", urgency: "soon", confidence: "high", confirmationRequired: false, reversible: true, capability: "review_financial_gap", fallbackIfDeclined: "Keep the goal confirmed without selecting a timeline." };
  if (input.targetMode === "fixed_date" && !input.fixedDateProvided) return { type: "answer_clarification", label: "Provide target date", reason: "The user selected a fixed-date evaluation, so the date is needed to calculate the required pace.", evidenceIds, expectedBenefit: "A deadline-specific feasibility estimate.", effort: "low", urgency: "soon", confidence: "high", confirmationRequired: false, reversible: true, capability: "review_financial_gap", fallbackIfDeclined: "Switch to realistic timeline options without a fixed date." };
  if (input.targetMode === "fixed_date" && input.fixedDateProvided && !input.optionsReady) return { type: "review_financial_gap", label: "Review fixed-date feasibility", reason: "The deadline-specific calculation is ready and does not require additional levers when current modeled resources cover the gap.", evidenceIds, expectedBenefit: "A clear feasibility and required-pace review.", effort: "low", urgency: "soon", confidence: "high", confirmationRequired: false, reversible: true, capability: "review_financial_gap", fallbackIfDeclined: "Compare a flexible timeline instead." };
  if (input.targetMode === "monthly_contribution_target" && !input.optionsReady) return { type: "answer_clarification", label: "Choose or request a monthly contribution", reason: "A contribution amount or Covarify suggestion is needed to estimate completion timing.", evidenceIds, expectedBenefit: "A sustainable monthly recovery estimate.", effort: "low", urgency: "soon", confidence: "high", confirmationRequired: false, reversible: true, capability: "review_financial_gap", fallbackIfDeclined: "Switch to flexible timeline options." };
  if (input.activePlanStatus === "behind" || input.activePlanStatus === "needs_adjustment") return { type: "adjust_plan", label: "Compare plan adjustments", reason: "Actual progress differs from the confirmed milestones.", evidenceIds, expectedBenefit: "A revised option aligned with current activity.", effort: "medium", urgency: "soon", confidence: "high", confirmationRequired: true, reversible: true, capability: "adjust_plan", fallbackIfDeclined: "Keep monitoring the current plan." };
  if (input.proposedTargetReady) return { type: "confirm_strategy", label: "Review and confirm the proposed target", reason: "The suggested timing remains a proposal until the user explicitly confirms it.", evidenceIds, expectedBenefit: "A user-confirmed target without activating or saving a plan.", effort: "medium", urgency: input.priority === "critical" || input.priority === "urgent" ? "now" : "when_ready", confidence: "high", confirmationRequired: true, reversible: true, capability: "confirm_strategy", fallbackIfDeclined: "Keep the target unconfirmed and compare alternatives." };
  if (input.optionsReady && !input.strategyReady) return { type: "compare_options", label: "Compare recovery options", reason: "Multiple evidence-backed approaches are available for the confirmed goal.", evidenceIds, expectedBenefit: "A clear choice among timing and disruption tradeoffs.", effort: "medium", urgency: input.priority === "critical" || input.priority === "urgent" ? "now" : "when_ready", confidence: "high", confirmationRequired: false, reversible: true, capability: "compare_options", fallbackIfDeclined: "Save no plan and return to the factual answer." };
  if (input.strategyReady) return { type: "confirm_strategy", label: "Review the proposed strategy", reason: "The strategy is ready but cannot become active without confirmation.", evidenceIds, expectedBenefit: "A confirmed plan with measurable milestones.", effort: "medium", urgency: input.priority === "critical" || input.priority === "urgent" ? "now" : "when_ready", confidence: "high", confirmationRequired: true, reversible: true, capability: "confirm_strategy", fallbackIfDeclined: "Keep the proposal inactive." };
  return { type: "no_action", label: "No next step needed", reason: "No justified action follows from the current evidence.", evidenceIds, expectedBenefit: "Avoid unnecessary work or generic advice.", effort: "low", urgency: "when_ready", confidence: "high", confirmationRequired: false, reversible: true, capability: null, fallbackIfDeclined: "No change." };
}
