import { allocateNextDollar, founderAllocationFixture, type AllocationResult, type Confidence } from "./allocation-intelligence.ts";

export type CashIncomeState = "confirmed_received" | "confirmed_cash_on_hand" | "deposited" | "expected_high_confidence" | "historically_typical" | "user_estimate" | "possible_uncertain" | "partially_spent" | "fully_spent" | "protected";
export type CashIncome = { id: string; sourceType: string; period: { start: string; end: string }; expected: boolean; grossAmount: number; cashOnHand: number; deposited: number; alreadySpent: number; protectedAmount: number; availableForAllocation: number; recurring: boolean; confidence: Confidence; timing: string; source: "user" | "fixture" | "document"; evidenceIds: string[]; confirmed: boolean; scope: "personal" | "household" | "business"; freshness: string; state: CashIncomeState; correction: string | null; supersedesId: string | null; reconciliationKey: string };
export type CashReconciliation = { earned: number; received: number; cashOnHand: number; deposited: number; spent: number; protected: number; availableOffAccount: number; availableDeposited: number; totalAvailableContribution: number; countedKeys: string[]; explanation: string; durableWriteBlocked: true };
export type VariableCashRange = { low: number; typical: number; high: number; userOverride: number | null; planningEstimate: number; confidence: Confidence };

export type ReceivableState = "received_available" | "partially_received" | "scheduled_high_confidence" | "expected" | "overdue_uncertain" | "disputed" | "doubtful" | "written_off" | "canceled";
export type Receivable = { invoiceId: string; client: string; description: string; grossAmount: number; amountPaid: number; remainingAmount: number; issueDate: string; dueDate: string; expectedPaymentDate: string | null; paymentTerms: string; state: ReceivableState; disputed: boolean; clientHistory: "reliable" | "mixed" | "unknown"; collectionConfidence: Confidence; paymentSchedule: Array<{ date: string; amount: number }>; businessCosts: number; taxReserveRate: number; vendorObligations: number; businessProtected: number; ownerAvailableEstimate: number; scope: "business"; source: "fixture" | "user" | "document"; evidenceIds: string[]; freshness: string; confirmed: boolean; correction: string | null; supersedesId: string | null; reconciliationKey: string };
export type ReceivableReconciliation = { gross: number; received: number; remaining: number; businessCostsApplied: number; taxReserveApplied: number; vendorObligationsApplied: number; businessProtectedApplied: number; receivedOwnerAvailable: number; expectedOwnerAvailable: number; currentPersonalCash: number; futurePlanningAmount: number; includedInFutureWindow: boolean; confidence: Confidence; explanation: string; countedKeys: string[]; durableWriteBlocked: true };
export type OffAccountScenario<T> = { title: string; simulated: true; baseline: T; changedAssumptions: string[]; result: T; activated: false; memoryWriteBlocked: true };

const bounded = (value: number, max: number) => Math.max(0, Math.min(value, max));
const rounded = (value: number) => Math.round(value * 100) / 100;

export function conservativeCashEstimate(input: Omit<VariableCashRange, "planningEstimate" | "confidence">): VariableCashRange { return { ...input, planningEstimate: input.userOverride == null ? input.low : bounded(input.userOverride, input.high), confidence: input.userOverride == null ? "medium" : "high" }; }

export function reconcileCashIncome(item: CashIncome): CashReconciliation {
  const received = item.expected && !item.confirmed ? 0 : bounded(item.grossAmount, item.grossAmount);
  const spent = bounded(item.alreadySpent, received); const protectedAmount = bounded(item.protectedAmount, Math.max(0, received - spent));
  const remaining = Math.max(0, received - spent - protectedAmount); const deposited = bounded(item.deposited, remaining); const cashOnHand = bounded(item.cashOnHand, Math.max(0, remaining - deposited));
  const reconciledAvailable = Math.min(remaining, deposited + cashOnHand);
  return { earned: item.grossAmount, received, cashOnHand, deposited, spent, protected: protectedAmount, availableOffAccount: cashOnHand, availableDeposited: deposited, totalAvailableContribution: reconciledAvailable, countedKeys: reconciledAvailable ? [item.reconciliationKey] : [], explanation: item.expected && !item.confirmed ? `${item.grossAmount} is expected and is not available today.` : `${reconciledAvailable} remains allocable after ${spent} spent and ${protectedAmount} protected; depositing it does not create new income.`, durableWriteBlocked: true };
}

export function cashIncomeFixture(overrides: Partial<CashIncome> = {}): CashIncome { return { id: "tips-aug-08", sourceType: "Bartending tips", period: { start: "2026-08-08", end: "2026-08-08" }, expected: true, grossAmount: 200, cashOnHand: 0, deposited: 0, alreadySpent: 0, protectedAmount: 0, availableForAllocation: 0, recurring: true, confidence: "medium", timing: "before 2026-08-20", source: "fixture", evidenceIds: ["user-reported-tip-pattern"], confirmed: false, scope: "personal", freshness: "2026-08-04", state: "historically_typical", correction: null, supersedesId: null, reconciliationKey: "cash-income:tips:2026-08-08", ...overrides }; }

export function allocationWithOffAccountCash(cash: CashIncome, protectUtility = false): AllocationResult { const reconciliation = reconcileCashIncome(cash); const fixture = founderAllocationFixture(); fixture.resources[0] = { ...fixture.resources[0], amount: 900 + reconciliation.totalAvailableContribution, evidenceIds: [...fixture.resources[0].evidenceIds, ...cash.evidenceIds], deduplicationKey: `cash-combined:${reconciliation.countedKeys.join("|") || "connected-only"}` }; return allocateNextDollar({ fixture, repairRequiredForWork: true, protectUtility }); }

export function allocationWithReceivedOwnerFunds(receivable: ReceivableReconciliation): AllocationResult { const fixture = founderAllocationFixture(); fixture.resources[0] = { ...fixture.resources[0], amount: 900 + receivable.currentPersonalCash, evidenceIds: [...fixture.resources[0].evidenceIds, ...receivable.countedKeys], deduplicationKey: `owner-funds:${receivable.countedKeys.join("|") || "none"}` }; return allocateNextDollar({ fixture, repairRequiredForWork: true }); }

export function ownerAvailable(input: { gross: number; businessCosts: number; taxReserveRate: number; vendorObligations?: number; businessProtected?: number }) { const taxReserve = rounded(input.gross * input.taxReserveRate); const amount = Math.max(0, rounded(input.gross - input.businessCosts - taxReserve - (input.vendorObligations || 0) - (input.businessProtected || 0))); return { gross: input.gross, businessCosts: input.businessCosts, taxReserve, vendorObligations: input.vendorObligations || 0, businessProtected: input.businessProtected || 0, ownerAvailable: amount }; }

export function receivableFixture(overrides: Partial<Receivable> = {}): Receivable { const estimate = ownerAvailable({ gross: 2500, businessCosts: 300, taxReserveRate: .25 }); return { invoiceId: "invoice-1042", client: "Reliable fixture client", description: "Sole-proprietor project invoice", grossAmount: 2500, amountPaid: 0, remainingAmount: 2500, issueDate: "2026-07-24", dueDate: "2026-08-07", expectedPaymentDate: "2026-08-07", paymentTerms: "Net 14", state: "scheduled_high_confidence", disputed: false, clientHistory: "reliable", collectionConfidence: "high", paymentSchedule: [{ date: "2026-08-07", amount: 2500 }], businessCosts: 300, taxReserveRate: .25, vendorObligations: 0, businessProtected: 0, ownerAvailableEstimate: estimate.ownerAvailable, scope: "business", source: "fixture", evidenceIds: ["invoice-1042", "materials-1042", "confirmed-tax-reserve"], freshness: "2026-08-04", confirmed: true, correction: null, supersedesId: null, reconciliationKey: "receivable:invoice-1042", ...overrides }; }

export function reconcileReceivable(invoice: Receivable, analysisWindow: { start: string; end: string }): ReceivableReconciliation {
  const excluded = invoice.disputed || ["doubtful", "written_off", "canceled", "overdue_uncertain"].includes(invoice.state); const paid = bounded(invoice.amountPaid, invoice.grossAmount); const remaining = Math.max(0, invoice.grossAmount - paid);
  const receivedDeductions = ownerAvailable({ gross: paid, businessCosts: Math.min(invoice.businessCosts, paid), taxReserveRate: invoice.taxReserveRate, vendorObligations: Math.min(invoice.vendorObligations, paid), businessProtected: Math.min(invoice.businessProtected, paid) });
  const totalEstimate = ownerAvailable({ gross: invoice.grossAmount, businessCosts: invoice.businessCosts, taxReserveRate: invoice.taxReserveRate, vendorObligations: invoice.vendorObligations, businessProtected: invoice.businessProtected });
  const expectedDate = invoice.expectedPaymentDate || invoice.dueDate; const inWindow = !excluded && Boolean(expectedDate >= analysisWindow.start && expectedDate <= analysisWindow.end);
  return { gross: invoice.grossAmount, received: paid, remaining, businessCostsApplied: receivedDeductions.businessCosts, taxReserveApplied: receivedDeductions.taxReserve, vendorObligationsApplied: receivedDeductions.vendorObligations, businessProtectedApplied: receivedDeductions.businessProtected, receivedOwnerAvailable: receivedDeductions.ownerAvailable, expectedOwnerAvailable: totalEstimate.ownerAvailable, currentPersonalCash: invoice.state === "received_available" || invoice.state === "partially_received" ? receivedDeductions.ownerAvailable : 0, futurePlanningAmount: inWindow ? Math.max(0, totalEstimate.ownerAvailable - receivedDeductions.ownerAvailable) : 0, includedInFutureWindow: inWindow, confidence: excluded ? "low" : invoice.collectionConfidence, explanation: excluded ? "This receivable is excluded from active expected income because collection is delayed, disputed, doubtful, canceled, or written off." : paid ? `Only received owner-available funds are current; the remaining receivable stays future and separate.` : `The estimated owner-available amount is future business income, not current personal cash.`, countedKeys: paid ? [`${invoice.reconciliationKey}:payment:${paid}`] : [], durableWriteBlocked: true };
}

export function simulateReceivable(baseline: Receivable, kind: "pays_friday" | "two_weeks_late" | "half_paid" | "disputed" | "keep_in_business"): OffAccountScenario<ReceivableReconciliation> {
  const window = { start: "2026-08-04", end: "2026-08-20" }; const original = reconcileReceivable(baseline, window); let changed = baseline; let label = "";
  if (kind === "pays_friday") { changed = { ...baseline, amountPaid: 2500, remainingAmount: 0, state: "received_available" }; label = "The full payment is received Friday."; }
  if (kind === "two_weeks_late") { changed = { ...baseline, expectedPaymentDate: "2026-08-21", state: "overdue_uncertain", collectionConfidence: "low" }; label = "The expected date moves two weeks later and confidence falls."; }
  if (kind === "half_paid") { changed = { ...baseline, amountPaid: 1250, remainingAmount: 1250, state: "partially_received" }; label = "Only half of the gross invoice is received."; }
  if (kind === "disputed") { changed = { ...baseline, disputed: true, state: "disputed", collectionConfidence: "low" }; label = "The client disputes the invoice."; }
  if (kind === "keep_in_business") { changed = { ...baseline, businessProtected: 1000 }; label = "$1,000 remains protected in the business."; }
  return { title: kind.replaceAll("_", " "), simulated: true, baseline: original, changedAssumptions: [label], result: reconcileReceivable(changed, window), activated: false, memoryWriteBlocked: true };
}

export function reconcileDeposit(input: { sourceKey: string; receiptAmount: number; depositAmount: number; transferAmount?: number }) { const deposited = bounded(input.depositAmount, input.receiptAmount); return { economicInflow: input.receiptAmount, depositMovement: deposited, transferMovement: bounded(input.transferAmount || 0, deposited), countedIncome: input.receiptAmount, countedKeys: [input.sourceKey], duplicatesPrevented: [deposited ? "deposit" : null, input.transferAmount ? "transfer" : null].filter(Boolean), explanation: "Receipt, deposit, and any business-to-personal transfer share one source key and count as one economic inflow." }; }

export function offAccountMemoryMapping() { const fields = ["type", "scope", "source", "period", "expectedVersusReceived", "amount", "remainingAvailable", "confidence", "evidence", "confirmation", "effectiveDate", "status", "correction", "revocation", "supersession"]; return { temporary: ["estimated cash", "expected tips", "inferred range", "unconfirmed amount remaining", "provisional receivable timing", "collection probability", "provisional owner-available amount"], durableCandidatesAfterConfirmation: ["received cash", "cash on hand", "confirmed deposit or spending", "invoice status", "received payment", "business cost", "tax-reserve preference", "owner-available amount", "dispute status"], neverCanonical: ["raw voice transcript", "unsupported estimate", "abandoned scenario", "unconfirmed recurring pattern", "ambiguous invoice parsing", "low-confidence client behavior"], requiredFields: fields, persistenceImplemented: false }; }
