import { allocateNextDollar, founderAllocationFixture, type AllocationResult, type Confidence } from "./allocation-intelligence.ts";

export type CashIncomeState = "confirmed_received" | "confirmed_cash_on_hand" | "deposited" | "expected_high_confidence" | "historically_typical" | "user_estimate" | "possible_uncertain" | "partially_spent" | "fully_spent" | "protected";
export type CashIncome = { id: string; sourceType: string; period: { start: string; end: string }; expected: boolean; grossAmount: number; cashOnHand: number; deposited: number; alreadySpent: number; protectedAmount: number; availableForAllocation: number; recurring: boolean; confidence: Confidence; timing: string; source: "user" | "fixture" | "document"; evidenceIds: string[]; confirmed: boolean; scope: "personal" | "household" | "business"; freshness: string; state: CashIncomeState; correction: string | null; supersedesId: string | null; reconciliationKey: string };
export type CashReconciliation = { earned: number; received: number; cashOnHand: number; deposited: number; spent: number; protected: number; availableOffAccount: number; availableDeposited: number; totalAvailableContribution: number; countedKeys: string[]; explanation: string; durableWriteBlocked: true };
export type VariableCashRange = { low: number; typical: number; high: number; userOverride: number | null; planningEstimate: number; confidence: Confidence };

export type ReceivableState = "received_available" | "partially_received" | "scheduled_high_confidence" | "expected" | "overdue_uncertain" | "disputed" | "doubtful" | "written_off" | "canceled";
export type Receivable = { invoiceId: string; client: string; description: string; grossAmount: number; amountPaid: number; remainingAmount: number; issueDate: string; dueDate: string; expectedPaymentDate: string | null; paymentTerms: string; state: ReceivableState; disputed: boolean; clientHistory: "reliable" | "mixed" | "unknown"; collectionConfidence: Confidence; paymentSchedule: Array<{ date: string; amount: number }>; businessCosts: number; taxReserveRate: number; vendorObligations: number; businessProtected: number; ownerAvailableEstimate: number; scope: "business"; source: "fixture" | "user" | "document"; evidenceIds: string[]; freshness: string; confirmed: boolean; correction: string | null; supersedesId: string | null; reconciliationKey: string };
export type ReceivableReconciliation = { gross: number; received: number; remaining: number; businessCostsApplied: number; taxReserveApplied: number; vendorObligationsApplied: number; businessProtectedApplied: number; receivedOwnerAvailable: number; expectedOwnerAvailable: number; currentPersonalCash: number; futurePlanningAmount: number; includedInFutureWindow: boolean; confidence: Confidence; explanation: string; countedKeys: string[]; durableWriteBlocked: true };
export type OffAccountScenario<T> = { title: string; simulated: true; baseline: T; changedAssumptions: string[]; result: T; activated: false; memoryWriteBlocked: true };
export type NormalizedCashAmount = { ok: true; amount: number; approximate: boolean; source: "numeric" | "words" | "fraction" | "full" | "none" } | { ok: false; error: string };
export type CashActionKind = "received" | "remaining" | "spent" | "deposited" | "protected";
export type CashFieldContext = "cash_received" | "cash_remaining" | "cash_spent" | "cash_deposited" | "cash_protected";
export type ParserContext = "money_amount" | "time" | "date" | "percentage" | "account_ending" | "general_text";
export type MoneyParseCandidate = { ok: true; rawTranscript: string; normalizedCandidate: number; approximate: boolean; confidence: "high" | "medium" | "low"; parserContext: "money_amount"; correctionProvenance: "browser_transcript" | "typed" | "user_accepted"; reviewRequired: boolean; reason: string | null } | { ok: false; rawTranscript: string; parserContext: "money_amount"; error: string; suggestedAmount?: number; reviewRequired: true };
export type ContextualParseResult = MoneyParseCandidate | { ok: true; rawTranscript: string; parserContext: Exclude<ParserContext, "money_amount">; normalizedCandidate: string | number; confidence: "high" | "medium" | "low"; reviewRequired: boolean } | { ok: false; rawTranscript: string; parserContext: Exclude<ParserContext, "money_amount">; error: string; reviewRequired: true };
export type CashFieldConflict = { activeField: CashFieldContext; spokenField: CashFieldContext; amount: number; approximate: boolean };
export type ParsedCashAction = { ok: true; kind: CashActionKind; field: CashFieldContext; amount: number; approximate: boolean; original: string; candidate: MoneyParseCandidate & { ok: true } } | { ok: false; error: string; candidate?: MoneyParseCandidate; fieldConflict?: CashFieldConflict };
export type CashValues = { received: number | null; remaining: number | null; deposited: number | null; protected: number | null };

const bounded = (value: number, max: number) => Math.max(0, Math.min(value, max));
const rounded = (value: number) => Math.round(value * 100) / 100;
const wordValues: Record<string, number> = { zero: 0, one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7, eight: 8, nine: 9, ten: 10, eleven: 11, twelve: 12, thirteen: 13, fourteen: 14, fifteen: 15, sixteen: 16, seventeen: 17, eighteen: 18, nineteen: 19, twenty: 20, thirty: 30, forty: 40, fifty: 50, sixty: 60, seventy: 70, eighty: 80, ninety: 90 };

function wordsToNumber(text: string): number | null { const tokens = text.toLowerCase().replace(/-/g, " ").split(/\s+/).filter((token) => token in wordValues || token === "hundred" || token === "thousand"); if (tokens.length === 2 && wordValues[tokens[0]] > 0 && wordValues[tokens[0]] < 10 && wordValues[tokens[1]] >= 20) return wordValues[tokens[0]] * 100 + wordValues[tokens[1]]; let total = 0; let current = 0; let found = false; for (const token of tokens) { if (token in wordValues) { current += wordValues[token]; found = true; } else if (token === "hundred" && current > 0) { current *= 100; found = true; } else if (token === "thousand" && current > 0) { total += current * 1000; current = 0; found = true; } } return found ? total + current : null; }

export function normalizeCashAmount(text: string, baseAmount?: number | null): NormalizedCashAmount {
  const normalized = text.trim().toLowerCase(); if (!normalized) return { ok: false, error: "Enter an amount before applying this update." }; const approximate = /\b(?:about|around|approximately|roughly)\b/.test(normalized);
  if (/(?:-|−)\s*\$?\s*\d/.test(normalized)) return { ok: false, error: "Cash amounts cannot be negative." };
  if (/\b(?:none|nothing|zero)\b/.test(normalized)) return { ok: true, amount: 0, approximate, source: "none" };
  const percentage = normalized.match(/(\d+(?:\.\d+)?)\s*%/); if (percentage) return baseAmount == null ? { ok: false, error: "I need the base amount before I can calculate a percentage." } : Number(percentage[1]) > 100 ? { ok: false, error: "The percentage cannot exceed 100%." } : { ok: true, amount: rounded(baseAmount * Number(percentage[1]) / 100), approximate, source: "fraction" };
  const timeLike = normalized.match(/\b(\d{1,3}):(\d{2})\b/); if (timeLike) return { ok: true, amount: Number(`${timeLike[1]}${timeLike[2]}`), approximate, source: "numeric" };
  const numeric = normalized.replace(/,/g, "").match(/(?:\$\s*)?(\d+(?:\.\d{1,2})?)/); if (numeric) return { ok: true, amount: Number(numeric[1]), approximate, source: "numeric" };
  if (/\b(?:all|all of it|the rest)\b/.test(normalized)) return baseAmount == null ? { ok: false, error: "I need the referenced amount before I can use ‘all.’" } : { ok: true, amount: baseAmount, approximate, source: "full" };
  const fraction = normalized.match(/\b(?:half|one half)\b/); if (fraction) return baseAmount == null ? { ok: false, error: "I need the base amount before I can calculate half." } : { ok: true, amount: rounded(baseAmount * .5), approximate, source: "fraction" };
  const cents = normalized.match(/\band\s+([a-z-]+(?:\s+[a-z-]+)?)\s+cents?\b/); const dollarText = cents ? normalized.slice(0, cents.index) : normalized; const words = wordsToNumber(dollarText); const centAmount = cents ? wordsToNumber(cents[1]) : 0; return words == null || centAmount == null || centAmount > 99 ? { ok: false, error: "I couldn’t confirm a dollar amount. Enter a number or a phrase such as ‘about ninety.’" } : { ok: true, amount: rounded(words + centAmount / 100), approximate, source: "words" };
}

export function parseContextualValue(text: string, context: ParserContext, input: { baseAmount?: number | null; provenance?: "browser_transcript" | "typed" | "user_accepted" } = {}): ContextualParseResult {
  const rawTranscript = text.trim();
  if (context === "time") { const time = rawTranscript.match(/\b(?:[01]?\d|2[0-3]):[0-5]\d\b/); return time ? { ok: true, rawTranscript, parserContext: context, normalizedCandidate: time[0], confidence: "high", reviewRequired: false } : { ok: false, rawTranscript, parserContext: context, error: "I couldn’t confirm a time.", reviewRequired: true }; }
  if (context !== "money_amount") return rawTranscript ? { ok: true, rawTranscript, parserContext: context, normalizedCandidate: rawTranscript, confidence: "medium", reviewRequired: false } : { ok: false, rawTranscript, parserContext: context, error: `I couldn’t confirm a ${context.replace("_", " ")}.`, reviewRequired: true };
  const lower = rawTranscript.toLowerCase();
  const ambiguousCompactWords = /\b(?:one|two|three|four|five|six|seven|eight|nine)\s+(?:twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety)\s+(?:one|two|three|four|five|six|seven|eight|nine)\b/.test(lower);
  const normalized = normalizeCashAmount(rawTranscript, input.baseAmount);
  if (!normalized.ok) return { ok: false, rawTranscript, parserContext: context, error: normalized.error, reviewRequired: true };
  const multipleClauses = /\b(?:and\s+(?:spent|used|kept|protected|deposited)|plus)\b/.test(lower);
  const consequential = /\b(?:deposit|protect|reserve|keep|allocate|use .* for|for rent|for groceries)\b/.test(lower);
  const multipleNumeric = (lower.match(/\$?\d+(?:\.\d{1,2})?/g) || []).length > 1 && !/\d{1,3}:\d{2}/.test(lower);
  const incomplete = /\b(?:something|some|maybe)\b/.test(lower);
  if (multipleClauses || ambiguousCompactWords || multipleNumeric || incomplete) return { ok: false, rawTranscript, parserContext: context, error: "I found a possible amount, but it needs review before it changes cash state.", suggestedAmount: normalized.amount, reviewRequired: true };
  return { ok: true, rawTranscript, normalizedCandidate: normalized.amount, approximate: normalized.approximate, confidence: "high", parserContext: context, correctionProvenance: input.provenance || "typed", reviewRequired: consequential, reason: consequential ? "This instruction materially affects the plan and requires review." : null };
}

const fieldForKind: Record<CashActionKind, CashFieldContext> = { received: "cash_received", remaining: "cash_remaining", spent: "cash_spent", deposited: "cash_deposited", protected: "cash_protected" };
const kindForField: Record<CashFieldContext, CashActionKind> = { cash_received: "received", cash_remaining: "remaining", cash_spent: "spent", cash_deposited: "deposited", cash_protected: "protected" };

export function parseCashAction(text: string, input: { expectedKind?: CashActionKind; activeField?: CashFieldContext; receivedAmount?: number | null; remainingAmount?: number | null }): ParsedCashAction {
  const activeField = input.activeField || fieldForKind[input.expectedKind || "received"]; const activeKind = kindForField[activeField];
  const spokenKind: CashActionKind | null = /\b(?:made|earned|received|got)\b/i.test(text) ? "received" : /\b(?:spent|used)\b/i.test(text) ? "spent" : /\b(?:still have|have all|remaining|left|none left)\b/i.test(text) ? "remaining" : /\bdeposit/i.test(text) ? "deposited" : /\b(?:keep|protect|reserve)\b/i.test(text) ? "protected" : null;
  const base = activeKind === "spent" || activeKind === "remaining" ? input.receivedAmount : activeKind === "deposited" || activeKind === "protected" ? input.remainingAmount : null; const candidate = parseContextualValue(text, "money_amount", { baseAmount: base });
  if (candidate.parserContext !== "money_amount") return { ok: false, error: "The active question did not request a money amount." }; if (!candidate.ok) return { ok: false, error: candidate.error, candidate };
  if (spokenKind && spokenKind !== activeKind) return { ok: false, error: `The wording answers ${fieldForKind[spokenKind].replace("cash_", "cash ")}, not the active ${activeField.replace("cash_", "cash ")} question.`, candidate, fieldConflict: { activeField, spokenField: fieldForKind[spokenKind], amount: candidate.normalizedCandidate, approximate: candidate.approximate } };
  return { ok: true, kind: activeKind, field: activeField, amount: candidate.normalizedCandidate, approximate: candidate.approximate, original: text, candidate };
}

export function validateCashAction(action: ParsedCashAction, current: { received: number | null; remaining: number | null; deposited: number | null; protected: number | null }): { ok: true } | { ok: false; error: string } {
  if (!action.ok) return action; if (action.amount < 0) return { ok: false, error: "Cash amounts cannot be negative." };
  if (action.kind === "received") return { ok: true }; if (current.received == null) return { ok: false, error: "Record the amount received first." };
  if ((action.kind === "spent" || action.kind === "remaining") && action.amount > current.received) return { ok: false, error: `${action.kind === "spent" ? "Spent" : "Remaining"} cash cannot exceed the amount received.` };
  const remaining = current.remaining ?? current.received; if (action.kind === "deposited" && action.amount > remaining) return { ok: false, error: "The deposit cannot exceed the cash still remaining." }; if (action.kind === "protected" && action.amount > remaining) return { ok: false, error: "The protected amount cannot exceed the cash still remaining." }; return { ok: true };
}

export function applyCashUpdate(current: CashValues, action: ParsedCashAction): { ok: true; values: CashValues; kind: CashActionKind; amount: number; noOp: boolean } | { ok: false; error: string } {
  const validation = validateCashAction(action, current); if (!validation.ok || !action.ok) return { ok: false, error: validation.ok ? "Unable to confirm amount." : validation.error };
  const { kind, amount } = action; const currentAmount = kind === "spent" ? (current.received != null && current.remaining != null ? current.received - current.remaining : null) : current[kind]; if (currentAmount === amount) return { ok: true, kind, amount, values: current, noOp: true };
  if (kind === "received") return { ok: true, kind, amount, values: { received: amount, remaining: /still have\s+(?:all|the rest)|all of it/i.test(action.original) ? amount : null, deposited: null, protected: null }, noOp: false };
  if (kind === "remaining") return { ok: true, kind, amount, values: { ...current, remaining: amount, deposited: null, protected: null }, noOp: false };
  if (kind === "spent") return { ok: true, kind, amount, values: { ...current, remaining: Math.max(0, (current.received || 0) - amount), deposited: null, protected: null }, noOp: false };
  if (kind === "deposited") return { ok: true, kind, amount, values: { ...current, deposited: amount }, noOp: false };
  return { ok: true, kind, amount, values: { ...current, protected: amount }, noOp: false };
}

export function conservativeCashEstimate(input: Omit<VariableCashRange, "planningEstimate" | "confidence">): VariableCashRange { return { ...input, planningEstimate: input.userOverride == null ? input.low : bounded(input.userOverride, input.high), confidence: input.userOverride == null ? "medium" : "high" }; }

export function reconcileCashIncome(item: CashIncome): CashReconciliation {
  const received = item.expected && !item.confirmed ? 0 : bounded(item.grossAmount, item.grossAmount);
  const spent = bounded(item.alreadySpent, received); const protectedAmount = bounded(item.protectedAmount, Math.max(0, received - spent));
  const remaining = Math.max(0, received - spent - protectedAmount); const deposited = bounded(item.deposited, remaining); const cashOnHand = bounded(item.cashOnHand, Math.max(0, remaining - deposited));
  const reconciledAvailable = Math.min(remaining, deposited + cashOnHand);
  return { earned: item.grossAmount, received, cashOnHand, deposited, spent, protected: protectedAmount, availableOffAccount: cashOnHand, availableDeposited: deposited, totalAvailableContribution: reconciledAvailable, countedKeys: reconciledAvailable ? [item.reconciliationKey] : [], explanation: item.expected && !item.confirmed ? `${item.grossAmount} is expected and is not available today.` : `${reconciledAvailable} remains allocable after ${spent} spent and ${protectedAmount} protected; depositing it does not create new income.`, durableWriteBlocked: true };
}

export function cashIncomeFixture(overrides: Partial<CashIncome> = {}): CashIncome { return { id: "tips-aug-08", sourceType: "Bartending tips", period: { start: "2026-08-08", end: "2026-08-08" }, expected: true, grossAmount: 200, cashOnHand: 0, deposited: 0, alreadySpent: 0, protectedAmount: 0, availableForAllocation: 0, recurring: true, confidence: "medium", timing: "before 2026-08-20", source: "fixture", evidenceIds: ["user-reported-tip-pattern"], confirmed: false, scope: "personal", freshness: "2026-08-04", state: "historically_typical", correction: null, supersedesId: null, reconciliationKey: "cash-income:tips:2026-08-08", ...overrides }; }

export function allocationWithOffAccountCash(cash: CashIncome, protectUtility = false): AllocationResult { const reconciliation = reconcileCashIncome(cash); const fixture = founderAllocationFixture(); fixture.resources[0] = { ...fixture.resources[0], amount: 900 + reconciliation.totalAvailableContribution, evidenceIds: [...fixture.resources[0].evidenceIds, ...cash.evidenceIds], deduplicationKey: `cash-combined:${reconciliation.countedKeys.join("|") || "connected-only"}` }; return allocateNextDollar({ fixture, repairRequiredForWork: true, protectUtility }); }

export function allocationWithReceivedOwnerFunds(receivable: ReceivableReconciliation): AllocationResult { const fixture = founderAllocationFixture(); fixture.resources[0] = { ...fixture.resources[0], amount: 900 + receivable.currentPersonalCash, evidenceIds: [...fixture.resources[0].evidenceIds, ...receivable.countedKeys], deduplicationKey: `owner-funds:${receivable.countedKeys.join("|") || "none"}` }; return allocateNextDollar({ fixture, repairRequiredForWork: true }); }

export function ownerAvailable(input: { gross: number; businessCosts: number; taxReserveRate: number; vendorObligations?: number; businessProtected?: number }) { const taxReserve = rounded(input.gross * input.taxReserveRate); const amount = Math.max(0, rounded(input.gross - input.businessCosts - taxReserve - (input.vendorObligations || 0) - (input.businessProtected || 0))); return { gross: input.gross, businessCosts: input.businessCosts, taxReserve, vendorObligations: input.vendorObligations || 0, businessProtected: input.businessProtected || 0, ownerAvailable: amount }; }

export function receivableFixture(overrides: Partial<Receivable> = {}): Receivable { const estimate = ownerAvailable({ gross: 2500, businessCosts: 300, taxReserveRate: .25 }); return { invoiceId: "invoice-1042", client: "Reliable fixture client", description: "Sole-proprietor project invoice", grossAmount: 2500, amountPaid: 0, remainingAmount: 2500, issueDate: "2026-07-24", dueDate: "2026-08-07", expectedPaymentDate: "2026-08-07", paymentTerms: "Net 14", state: "scheduled_high_confidence", disputed: false, clientHistory: "reliable", collectionConfidence: "high", paymentSchedule: [{ date: "2026-08-07", amount: 2500 }], businessCosts: 300, taxReserveRate: .25, vendorObligations: 0, businessProtected: 0, ownerAvailableEstimate: estimate.ownerAvailable, scope: "business", source: "fixture", evidenceIds: ["invoice-1042", "materials-1042", "confirmed-tax-reserve"], freshness: "2026-08-04", confirmed: true, correction: null, supersedesId: null, reconciliationKey: "receivable:invoice-1042", ...overrides }; }

export function reconcileReceivable(invoice: Receivable, analysisWindow: { start: string; end: string }): ReceivableReconciliation {
  const excluded = invoice.disputed || ["doubtful", "written_off", "canceled", "overdue_uncertain"].includes(invoice.state); const paid = bounded(invoice.amountPaid, invoice.grossAmount); const remaining = Math.max(0, invoice.grossAmount - paid);
  const receivedDeductions = ownerAvailable({ gross: paid, businessCosts: Math.min(invoice.businessCosts, paid), taxReserveRate: invoice.taxReserveRate, vendorObligations: Math.min(invoice.vendorObligations, paid), businessProtected: Math.min(invoice.businessProtected, paid) });
  const totalEstimate = ownerAvailable({ gross: invoice.grossAmount, businessCosts: invoice.businessCosts, taxReserveRate: invoice.taxReserveRate, vendorObligations: invoice.vendorObligations, businessProtected: invoice.businessProtected });
  const expectedDate = invoice.expectedPaymentDate || invoice.dueDate; const inWindow = !excluded && Boolean(expectedDate >= analysisWindow.start && expectedDate <= analysisWindow.end);
  return { gross: invoice.grossAmount, received: paid, remaining, businessCostsApplied: receivedDeductions.businessCosts, taxReserveApplied: receivedDeductions.taxReserve, vendorObligationsApplied: receivedDeductions.vendorObligations, businessProtectedApplied: receivedDeductions.businessProtected, receivedOwnerAvailable: receivedDeductions.ownerAvailable, expectedOwnerAvailable: totalEstimate.ownerAvailable, currentPersonalCash: invoice.state === "received_available" || invoice.state === "partially_received" ? receivedDeductions.ownerAvailable : 0, futurePlanningAmount: inWindow ? Math.max(0, totalEstimate.ownerAvailable - receivedDeductions.ownerAvailable) : 0, includedInFutureWindow: inWindow, confidence: excluded ? "low" : invoice.collectionConfidence, explanation: excluded ? "This receivable is excluded from active expected income because collection is delayed, disputed, doubtful, canceled, or written off." : paid ? `Only received owner-available funds are current; the remaining receivable stays future and separate.` : `The estimated owner-available amount is future business income, not current personal cash.`, countedKeys: paid ? [`${invoice.reconciliationKey}:payment:${paid}`] : [], durableWriteBlocked: true };
}

export function simulateReceivable(baseline: Receivable, kind: "pays_friday" | "two_weeks_late" | "half_paid" | "disputed" | "keep_in_business"): OffAccountScenario<ReceivableReconciliation> {
  const window = { start: "2026-08-04", end: "2026-08-20" }; const original = reconcileReceivable(baseline, window); let changed = baseline; let label = "";
  if (kind === "pays_friday") { changed = { ...baseline, amountPaid: 2500, remainingAmount: 0, state: "received_available" }; label = "The full payment is received Friday."; }
  if (kind === "two_weeks_late") { changed = { ...baseline, expectedPaymentDate: "2026-08-21", state: "overdue_uncertain", collectionConfidence: "low" }; label = "The expected date moves two weeks later and confidence falls."; }
  if (kind === "half_paid") { changed = { ...baseline, amountPaid: 1250, remainingAmount: 1250, state: "partially_received" }; label = "Only half of the gross invoice is received."; }
  if (kind === "disputed") { changed = { ...baseline, disputed: true, state: "disputed", collectionConfidence: "low" }; label = "The client disputes the invoice."; }
  if (kind === "keep_in_business") { changed = { ...baseline, businessProtected: 1000 }; label = "$1,000 remains protected in the business."; }
  return { title: kind.replaceAll("_", " "), simulated: true, baseline: original, changedAssumptions: [label], result: reconcileReceivable(changed, window), activated: false, memoryWriteBlocked: true };
}

export function reconcileDeposit(input: { sourceKey: string; receiptAmount: number; depositAmount: number; transferAmount?: number }) { const deposited = bounded(input.depositAmount, input.receiptAmount); return { economicInflow: input.receiptAmount, depositMovement: deposited, transferMovement: bounded(input.transferAmount || 0, deposited), countedIncome: input.receiptAmount, countedKeys: [input.sourceKey], duplicatesPrevented: [deposited ? "deposit" : null, input.transferAmount ? "transfer" : null].filter(Boolean), explanation: "Receipt, deposit, and any business-to-personal transfer share one source key and count as one economic inflow." }; }

export function offAccountMemoryMapping() { const fields = ["type", "scope", "source", "period", "expectedVersusReceived", "amount", "remainingAvailable", "confidence", "evidence", "confirmation", "effectiveDate", "status", "correction", "revocation", "supersession"]; return { temporary: ["estimated cash", "expected tips", "inferred range", "unconfirmed amount remaining", "provisional receivable timing", "collection probability", "provisional owner-available amount"], durableCandidatesAfterConfirmation: ["received cash", "cash on hand", "confirmed deposit or spending", "invoice status", "received payment", "business cost", "tax-reserve preference", "owner-available amount", "dispute status"], neverCanonical: ["raw voice transcript", "unsupported estimate", "abandoned scenario", "unconfirmed recurring pattern", "ambiguous invoice parsing", "low-confidence client behavior"], requiredFields: fields, persistenceImplemented: false }; }
