import type { AmbiguityCandidate, CanonicalDecisionResult, PresentationBlock, PresentationDepth, StateChange } from "./turn-contract.ts";
const money = (value: unknown) => typeof value === "number" ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value) : String(value);
export function presentTurn(input: { turnId: string; decision: CanonicalDecisionResult; depth: PresentationDepth; proposal: StateChange | null; ambiguity: { message: string; candidates: AmbiguityCandidate[] } | null; outOfScope?: boolean; sessionMessage?: string | null }) {
  let primary = input.sessionMessage || input.decision.answer?.summary || input.decision.recommendation?.summary || "I can help with your financial picture and decisions."; let question: string | null = null;
  const blocks: PresentationBlock[] = [];
  if (input.outOfScope) primary = "I’m focused on helping with your financial picture and decisions.";
  if (input.ambiguity) { primary = input.ambiguity.message; question = input.ambiguity.message; blocks.push({ id: `${input.turnId}:clarification`, type: "question", body: primary, emphasis: "primary", evidenceIds: [] }); }
  else if (input.proposal) { primary = `Review changing ${input.proposal.entityId} ${input.proposal.field.replaceAll("_", " ")} from ${money(input.proposal.before)} to ${money(input.proposal.after)}.`; question = "Apply this session-only correction?"; blocks.push({ id: `${input.turnId}:correction`, type: "correction_review", body: primary, emphasis: "primary", evidenceIds: [] }); }
  else blocks.push({ id: `${input.turnId}:primary`, type: input.decision.recommendation ? "recommendation" : "answer", body: primary, emphasis: "primary", evidenceIds: [] });
  const rationale = input.decision.recommendation ? rationaleFromDecision(input.decision) : null;
  if (rationale && input.depth !== "CONCISE") blocks.push({ id: `${input.turnId}:rationale`, type: "rationale", body: rationale, emphasis: "supporting", evidenceIds: input.decision.factsConsidered.flatMap((fact) => fact.evidenceIds) });
  if (input.depth === "DETAILED" && input.decision.reconciliation) blocks.push({ id: `${input.turnId}:reconciliation`, type: "reconciliation", body: `Available ${money(input.decision.reconciliation.available)}; allocated ${money(input.decision.reconciliation.allocated)}; remaining ${money(input.decision.reconciliation.remaining)}.`, emphasis: "detail", evidenceIds: [] });
  return { primaryMessage: primary, conciseRationale: rationale, blocks, question, correction: input.proposal ? { changeId: input.proposal.changeId, message: primary } : null };
}
export function rationaleFromDecision(decision: CanonicalDecisionResult) { if (!decision.recommendation) return null; if (decision.type === "ALLOCATION") return `This uses the same ${money(decision.reconciliation?.available || 0)} represented in the allocation and preserves ${decision.constraints.length ? decision.constraints.join(" and ") : "the confirmed priorities"}.`; if (decision.type === "EXPECTED_RESOURCE") return decision.constraints.join(" "); if (decision.type === "GOAL_PRIORITY") return decision.consequenceOfDelay || decision.tradeoffs[0] || decision.recommendation.summary; if (decision.type === "SNAPSHOT_CHANGE") return decision.quantified.map((item) => `${item.label}: ${money(item.value)}.`).join(" "); return decision.recommendation.summary; }
