import { orchestrateConversation } from "./orchestrator.ts";
import type { CanonicalFinancialTruth } from "./financial-truth.ts";
import type { ConversationContext, ConversationResponse } from "./types.ts";
import type { CanonicalDecisionResult, CapabilityId, FactValue, IntentId, MemoryDisposition, SemanticAction } from "./turn-contract.ts";
export type TransactionAdapterRequest = { statement: string; sessionId: string; selectedTransactionId?: string | null; context?: ConversationContext | null; activePeriod?: { label: string; start: string; end: string }; dataMode?: "connected" | "fixture"; now?: Date };
export type TransactionAdapterResult = { decision: CanonicalDecisionResult; legacy: ConversationResponse; intent: IntentId; capability: CapabilityId; facts: FactValue[]; entityIds: string[]; evidenceIds: string[]; actions: SemanticAction[]; memory: { disposition: MemoryDisposition; proposal: { proposalId: string; fact: FactValue; sourceTurnId: string } | null } };
const answerType = (response: ConversationResponse): NonNullable<CanonicalDecisionResult["answer"]>["type"] => response.intent.type === "transaction_count" ? "TRANSACTION_COUNT" : response.intent.type === "transaction_total" ? "TRANSACTION_TOTAL" : response.intent.type === "transaction_list" ? "TRANSACTION_LIST" : response.intent.type === "account_question" ? "ACCOUNT_SUMMARY" : response.proposal ? "PROPOSAL" : "CLARIFICATION";
export function runTransactionUnderstandingAdapter(input: { truth: CanonicalFinancialTruth; request: TransactionAdapterRequest }): TransactionAdapterResult {
  const selectedTransactionId = input.request.selectedTransactionId && input.truth.transactions.some((item) => item.id === input.request.selectedTransactionId) ? input.request.selectedTransactionId : null;
  const context = input.request.context?.userId === input.truth.subject.userId && input.request.context.sessionId === input.request.sessionId ? input.request.context : null;
  const legacy = orchestrateConversation({ text: input.request.statement, userId: input.truth.subject.userId, sessionId: input.request.sessionId, selectedTransactionId, context, activePeriod: input.request.activePeriod, transactions: input.truth.transactions, dataMode: input.request.dataMode, now: input.request.now });
  const evidenceIds = legacy.evidence?.transactionIds || legacy.context?.transactionIds || legacy.proposal?.transactionIds || []; const entityIds = [...new Set(evidenceIds)]; const facts = input.truth.facts.filter((fact) => entityIds.includes(fact.entityId));
  const intent: IntentId = legacy.intent.type === "transaction_count" ? "TRANSACTION_COUNT" : legacy.intent.type === "transaction_total" ? "TRANSACTION_TOTAL" : legacy.intent.type === "transaction_list" ? "TRANSACTION_LIST" : legacy.intent.type === "account_question" ? "ACCOUNT_QUESTION" : legacy.proposal ? "TRANSACTION_MEANING" : "UNRESOLVED"; const capability: CapabilityId = legacy.proposal ? "PROPOSE_MEMORY" : legacy.intent.capability ? "READ_FINANCIAL_STATE" : "OUT_OF_SCOPE";
  const quantified = [{ label: "Transaction count", value: legacy.context?.count || evidenceIds.length, unit: "count" as const }, ...(legacy.context?.total != null ? [{ label: "Transaction total", value: legacy.context.total, unit: "USD" as const }] : [])];
  const decision: CanonicalDecisionResult = { decisionId: `transaction:${input.request.sessionId}:${legacy.intent.type}`, type: legacy.proposal ? "TRANSACTION_MEANING" : "TRANSACTION_UNDERSTANDING", goal: null, constraints: [], factsConsidered: facts, answer: { type: answerType(legacy), summary: legacy.message }, recommendation: null, quantified, allocation: [], reconciliation: null, alternatives: [], tradeoffs: [], consequenceOfDelay: null, uncertainty: legacy.kind === "clarification_question" ? legacy.intent.unresolvedFields : [], confidence: legacy.intent.confidence, status: legacy.proposal || legacy.kind === "clarification_question" ? "preliminary" : "final", affectedEntityIds: entityIds };
  const actions: SemanticAction[] = (legacy.actions || []).map((item) => ({ id: `transaction.evidence.${item.transactionIds.join(".")}`, type: "SHOW_EVIDENCE", label: item.label, consequence: "READ_ONLY", confirmation: "none", reversible: false, payload: { kind: "show_evidence", evidenceGroupId: item.transactionIds.join(":") } }));
  const proposedFact: FactValue | null = legacy.proposal ? { entityId: legacy.proposal.transactionIds[0] || "transaction-context", entityType: "TRANSACTION", field: "meaning", value: legacy.proposal.values.map((item) => `${item.label}: ${item.value}`).join("; "), status: "unconfirmed", evidenceIds: legacy.proposal.evidence } : null;
  return { decision, legacy, intent, capability, facts, entityIds, evidenceIds, actions, memory: proposedFact ? { disposition: "memory_proposal", proposal: { proposalId: `transaction-memory:${input.request.sessionId}`, fact: proposedFact, sourceTurnId: "pending-turn" } } : { disposition: "session_only", proposal: null } };
}
