import "server-only";
import { createSupabaseAdminClient } from "../../supabase/admin";
import type { PlaidProductionRepository } from "./repositories";
import type { PlaidItemRecord } from "./domain";
const fail=(error:{message?:string}|null)=>{if(error)throw new Error("Plaid persistence operation failed.")};
type DbPlaidItem={id:string;user_id:string;plaid_item_id:string;institution_id:string|null;institution_name:string|null;environment:PlaidItemRecord["environment"];encrypted_access_token:string;token_key_version:string;status:PlaidItemRecord["status"];consent_id:string;created_at:string;updated_at:string;last_successful_sync_at:string|null;last_webhook_at:string|null;error_code:string|null;needs_update_mode:boolean;disconnected_at:string|null};
const item=(r:DbPlaidItem):PlaidItemRecord=>({id:r.id,userId:r.user_id,profileId:r.user_id,plaidItemId:r.plaid_item_id,institutionId:r.institution_id,institutionName:r.institution_name,environment:r.environment,encryptedAccessToken:r.encrypted_access_token,tokenKeyVersion:r.token_key_version,status:r.status,consentId:r.consent_id,createdAt:r.created_at,updatedAt:r.updated_at,lastSuccessfulSyncAt:r.last_successful_sync_at,lastWebhookAt:r.last_webhook_at,errorCode:r.error_code,needsUpdateMode:r.needs_update_mode,disconnectedAt:r.disconnected_at});
export function createSupabasePlaidRepository():PlaidProductionRepository { const db=createSupabaseAdminClient(); return {
  async findItemByPlaidId(id){const {data,error}=await db.from("plaid_items").select("*").eq("plaid_item_id",id).maybeSingle();fail(error);return data?item(data as DbPlaidItem):null;},
  async findOwnedItem(id,userId){const {data,error}=await db.from("plaid_items").select("*").eq("id",id).eq("user_id",userId).maybeSingle();fail(error);return data?item(data as DbPlaidItem):null;},
  async createConnection({item:i,accounts,syncState,consent}){const {error:c}=await db.from("consent_records").insert({id:consent.id,user_id:consent.userId,consent_version:consent.consentVersion,products_requested:consent.productsRequested,purposes:consent.dataPurposes,accepted_at:consent.acceptedAt,revoked_at:consent.revokedAt});fail(c);const {error:pi}=await db.from("plaid_items").insert({id:i.id,user_id:i.userId,plaid_item_id:i.plaidItemId,institution_id:i.institutionId,institution_name:i.institutionName,environment:i.environment,encrypted_access_token:i.encryptedAccessToken,token_key_version:i.tokenKeyVersion,status:i.status,consent_id:i.consentId});fail(pi);await this.upsertAccounts(accounts);await this.updateSyncState(syncState);},
  async upsertAccounts(accounts){if(!accounts.length)return;const rows=accounts.map(a=>({id:a.id,user_id:a.userId,plaid_item_id:a.plaidItemId,plaid_account_id:a.plaidAccountId,persistent_account_id:a.persistentAccountId,name:a.name,official_name:a.officialName,type:a.type,subtype:a.subtype,mask:a.mask,currency:a.currency,current_balance:a.currentBalance,available_balance:a.availableBalance,active_status:a.status,updated_at:a.observedAt}));const {error}=await db.from("plaid_accounts").upsert(rows,{onConflict:"plaid_item_id,plaid_account_id"});fail(error);},
  async updateSyncState(s){const {error}=await db.from("transaction_sync_states").upsert({plaid_item_id:s.plaidItemId,cursor:s.cursor,sync_status:s.status,retry_count:s.retryCount,last_error:s.lastErrorCode,last_sync_started_at:s.lastSyncStartedAt,last_sync_completed_at:s.lastSyncCompletedAt},{onConflict:"plaid_item_id"});fail(error);},
  async applyTransactionDelta({added,modified,removedIds,removedAt}){const rows=[...added,...modified].map(t=>({id:t.id,user_id:t.userId,plaid_item_id:t.plaidItemId,plaid_account_id:t.plaidAccountId,plaid_transaction_id:t.plaidTransactionId,pending_transaction_id:t.pendingTransactionId,amount:t.amount,currency:t.currency,merchant_name:t.merchantName,transaction_name:t.name,category_data:t.rawCategory,transaction_date:t.date,authorized_date:t.authorizedDate,pending:t.pending,removed_at:t.removedAt,updated_at:t.sourceUpdatedAt}));if(rows.length){const {error}=await db.from("plaid_transactions").upsert(rows,{onConflict:"plaid_item_id,plaid_transaction_id"});fail(error);}if(removedIds.length){const {error}=await db.from("plaid_transactions").update({removed_at:removedAt}).in("plaid_transaction_id",removedIds);fail(error);}},
  async markDisconnected(id,at){const {error}=await db.from("plaid_items").update({status:"disconnected",disconnected_at:at}).eq("id",id);fail(error);}, async clearEncryptedToken(id){const {error}=await db.from("plaid_items").update({encrypted_access_token:null,token_key_version:null}).eq("id",id);fail(error);},
  async recordWebhook(e){const {error}=await db.from("plaid_webhook_events").insert({id:e.id,event_hash:e.bodyHash,webhook_type:e.webhookType,webhook_code:e.webhookCode,verification_status:"verified",processing_status:"received",received_at:e.receivedAt,processed_at:e.processedAt});if(error?.code==="23505")return "duplicate";fail(error);return "created";}
};}
