import "server-only";
import { createSupabaseAdminClient } from "../../supabase/admin";
import type { PlaidProductionRepository, PlaidSyncQueue, PlaidSyncWorkerRepository } from "./repositories";
import type { PlaidItemRecord, PlaidSyncJobRecord, TransactionSyncStateRecord } from "./domain";
const fail=(error:{message?:string}|null)=>{if(error)throw new Error("Plaid persistence operation failed.")};
type DbPlaidItem={id:string;user_id:string;plaid_item_id:string;institution_id:string|null;institution_name:string|null;environment:PlaidItemRecord["environment"];encrypted_access_token:string;token_key_version:string;status:PlaidItemRecord["status"];consent_id:string;created_at:string;updated_at:string;last_successful_sync_at:string|null;last_webhook_at:string|null;error_code:string|null;needs_update_mode:boolean;disconnected_at:string|null};
const item=(r:DbPlaidItem):PlaidItemRecord=>({id:r.id,userId:r.user_id,profileId:r.user_id,plaidItemId:r.plaid_item_id,institutionId:r.institution_id,institutionName:r.institution_name,environment:r.environment,encryptedAccessToken:r.encrypted_access_token,tokenKeyVersion:r.token_key_version,status:r.status,consentId:r.consent_id,createdAt:r.created_at,updatedAt:r.updated_at,lastSuccessfulSyncAt:r.last_successful_sync_at,lastWebhookAt:r.last_webhook_at,errorCode:r.error_code,needsUpdateMode:r.needs_update_mode,disconnectedAt:r.disconnected_at});
type DbSyncState={plaid_item_id:string;cursor:string|null;sync_status:TransactionSyncStateRecord["status"];retry_count:number;last_error:string|null;last_sync_started_at:string|null;last_sync_completed_at:string|null};
const syncState=(r:DbSyncState):TransactionSyncStateRecord=>({plaidItemId:r.plaid_item_id,cursor:r.cursor,status:r.sync_status,retryCount:r.retry_count,lastErrorCode:r.last_error,lastSyncStartedAt:r.last_sync_started_at,lastSyncCompletedAt:r.last_sync_completed_at,triggeringWebhookCode:null});
const changed=(value:unknown)=>{if(value!==true)throw new Error("Plaid sync job lease was lost.")};
export function createSupabasePlaidRepository():PlaidProductionRepository & PlaidSyncQueue & PlaidSyncWorkerRepository { const db=createSupabaseAdminClient(); return {
  async findItemByPlaidId(id){const {data,error}=await db.from("plaid_items").select("*").eq("plaid_item_id",id).maybeSingle();fail(error);return data?item(data as DbPlaidItem):null;},
  async findOwnedItem(id,userId){const {data,error}=await db.from("plaid_items").select("*").eq("id",id).eq("user_id",userId).maybeSingle();fail(error);return data?item(data as DbPlaidItem):null;},
  async findItemById(id){const {data,error}=await db.from("plaid_items").select("*").eq("id",id).maybeSingle();fail(error);return data?item(data as DbPlaidItem):null;},
  async getSyncState(id){const {data,error}=await db.from("transaction_sync_states").select("*").eq("plaid_item_id",id).maybeSingle();fail(error);return data?syncState(data as DbSyncState):null;},
  async createConnection({item:i,accounts,syncState,consent}){const {error:c}=await db.from("consent_records").insert({id:consent.id,user_id:consent.userId,consent_version:consent.consentVersion,products_requested:consent.productsRequested,purposes:consent.dataPurposes,accepted_at:consent.acceptedAt,revoked_at:consent.revokedAt});fail(c);const {error:pi}=await db.from("plaid_items").insert({id:i.id,user_id:i.userId,plaid_item_id:i.plaidItemId,institution_id:i.institutionId,institution_name:i.institutionName,environment:i.environment,encrypted_access_token:i.encryptedAccessToken,token_key_version:i.tokenKeyVersion,status:i.status,consent_id:i.consentId});fail(pi);await this.upsertAccounts(accounts);await this.updateSyncState(syncState);},
  async upsertAccounts(accounts){if(!accounts.length)return;const rows=accounts.map(a=>({id:a.id,user_id:a.userId,plaid_item_id:a.plaidItemId,plaid_account_id:a.plaidAccountId,persistent_account_id:a.persistentAccountId,name:a.name,official_name:a.officialName,type:a.type,subtype:a.subtype,mask:a.mask,currency:a.currency,current_balance:a.currentBalance,available_balance:a.availableBalance,active_status:a.status,updated_at:a.observedAt}));const {error}=await db.from("plaid_accounts").upsert(rows,{onConflict:"plaid_item_id,plaid_account_id"});fail(error);},
  async updateSyncState(s){const {error}=await db.from("transaction_sync_states").upsert({plaid_item_id:s.plaidItemId,cursor:s.cursor,sync_status:s.status,retry_count:s.retryCount,last_error:s.lastErrorCode,last_sync_started_at:s.lastSyncStartedAt,last_sync_completed_at:s.lastSyncCompletedAt},{onConflict:"plaid_item_id"});fail(error);},
  async applyTransactionDelta({added,modified,removedIds,removedAt}){const changes=[...added,...modified];const externalIds=[...new Set(changes.map(t=>t.plaidAccountId))];const {data:accounts,error:accountError}=externalIds.length?await db.from("plaid_accounts").select("id,plaid_account_id").in("plaid_account_id",externalIds):{data:[],error:null};fail(accountError);const ids=new Map((accounts||[]).map(a=>[a.plaid_account_id,a.id]));const rows=changes.map(t=>{const accountId=ids.get(t.plaidAccountId);if(!accountId)throw new Error("Plaid transaction account ownership mapping failed.");return {id:t.id,user_id:t.userId,plaid_item_id:t.plaidItemId,plaid_account_id:accountId,plaid_transaction_id:t.plaidTransactionId,pending_transaction_id:t.pendingTransactionId,amount:t.amount,currency:t.currency,merchant_name:t.merchantName,transaction_name:t.name,category_data:t.rawCategory,transaction_date:t.date,authorized_date:t.authorizedDate,pending:t.pending,removed_at:t.removedAt,updated_at:t.sourceUpdatedAt};});if(rows.length){const {error}=await db.from("plaid_transactions").upsert(rows,{onConflict:"plaid_item_id,plaid_transaction_id"});fail(error);const posted=rows.filter(t=>!t.pending&&t.pending_transaction_id).map(t=>t.pending_transaction_id as string);if(posted.length){const {error:p}=await db.from("plaid_transactions").update({removed_at:removedAt}).in("plaid_transaction_id",posted);fail(p);}}if(removedIds.length){const {error}=await db.from("plaid_transactions").update({removed_at:removedAt}).in("plaid_transaction_id",removedIds);fail(error);}},
  async markDisconnected(id,at){const {error}=await db.from("plaid_items").update({status:"disconnected",disconnected_at:at}).eq("id",id);fail(error);}, async clearEncryptedToken(id){const {error}=await db.from("plaid_items").update({encrypted_access_token:null,token_key_version:null}).eq("id",id);fail(error);},
  async recordWebhook(e){const {error}=await db.from("plaid_webhook_events").insert({id:e.id,source_plaid_item_id:e.plaidItemId,event_hash:e.bodyHash,webhook_type:e.webhookType,webhook_code:e.webhookCode,verification_status:"verified",processing_status:"received",received_at:e.receivedAt,processed_at:e.processedAt});if(error?.code==="23505")return "duplicate";fail(error);return "created";},
  async enqueue({plaidItemId,webhookCode,deduplicationKey}){const {data:found,error:findError}=await db.from("plaid_items").select("id").eq("plaid_item_id",plaidItemId).maybeSingle();fail(findError);if(!found)return;const {error}=await db.from("plaid_sync_jobs").insert({plaid_item_id:found.id,idempotency_key:deduplicationKey,webhook_code:webhookCode,status:"queued"});if(error?.code==="23505"){const {data:duplicate,error:duplicateError}=await db.from("plaid_sync_jobs").select("id").eq("idempotency_key",deduplicationKey).maybeSingle();fail(duplicateError);if(duplicate)return;const {error:coalesceError}=await db.from("plaid_sync_jobs").update({resync_requested:true,webhook_code:webhookCode,updated_at:new Date().toISOString()}).eq("plaid_item_id",found.id).in("status",["queued","running","retry"]);fail(coalesceError);return;}fail(error);},
  async claimSyncJob(){const {data,error}=await db.rpc("claim_plaid_sync_job");fail(error);const row=Array.isArray(data)?data[0]:null;if(!row)return null;return {id:row.id,plaidItemId:row.plaid_item_id,webhookCode:row.webhook_code,attemptCount:row.attempt_count,leaseToken:row.lease_token} as PlaidSyncJobRecord;},
  async completeSyncJob(job){const {data,error}=await db.rpc("complete_plaid_sync_job",{job_id:job.id,job_lease_token:job.leaseToken});fail(error);changed(data);},
  async retrySyncJob(job,input){const {data,error}=await db.rpc("retry_plaid_sync_job",{job_id:job.id,job_lease_token:job.leaseToken,retry_at:input.availableAt,error_code:input.safeErrorCode});fail(error);changed(data);},
  async failSyncJob(job,errorCode){const {data,error}=await db.rpc("fail_plaid_sync_job",{job_id:job.id,job_lease_token:job.leaseToken,error_code:errorCode});fail(error);changed(data);}
};}
